### ISSUE TITLE
Premium Shop

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#10]
A configurable web-shop where you can buy character and pet cards.

Should be put on the web-server, but the data has to come from the user folder somehow, so it can be modified without touching the system folder.

**Comment by exectails** [comment]
One reason I haven't tackled this yet, is that I'm not sure how to handle the data. After some consideration I now came to the conclusion that storing the goods in the MySQL database would be best.

With a database we can set a few defaults, but also provide a simple UI to modify the data, in an admin panel that's integrated into the shops. This is very straight forward, even for newbies, and already gives us the ability to save how often something was bought, etc, to display popular items.

The alternative I was thinking about was a script, with `AddProduct` calls, that could be copied and overriden from the user folder, to allow admins to modify the goods. That would be in line with how we usually handle these kind of things, but I feel like newbies might have a hard time with that, and we will need some kind of database anyway, to save the information mentioned above.

The only disadvantage I can think of is that the data is in the database, and you can't just wipe the entire db without losing the shop data. To solve this problem I'd propose an import/export function in the admin panel, so admins can save and restore the shops.

**Comment by Cosrnos** [comment]
Is this overbuilding for a version one? Perhaps v1 is that aura comes shipped with the db values in place and if you want to add/remove items you manage the database yourself. I think providing a web UI to add/remove items is a nice concept/idea but I think right now aura should focus on having a great core and API, let someone else build the web interface ;)

**Comment by QewQew** [comment]
>let someone else build the web interface ;)

I volunteer Alex.

**Comment by exectails** [comment]
>let someone else build the web interface

As you know, we have a chronic lack of "someone elses"^^ I wonder if we even have someone who understands web development, our web server, inter server communication, and the required packets.

I see your point, the shops aren't really needed yet, and one might argue that even in v1 it would not be something the core would need, but given the integration of the shops into the game (buttons, "in-game" browser), and the user's expectation to be able to get cards and items there, we can just as well add a simple one.

As for the timing, I recently added support for Nao Stones and just thought I'd get these two issues out of the way =< I admit though, I've been thinking about doing other things all day.

![ss 2016-02-10 at 09 42 12](https://cloud.githubusercontent.com/assets/5593920/12961170/5cf22bb6-d03f-11e5-886f-a3fb3086fa52.png)

**Comment by exectails** [comment]
I just realized something... we can implement premium shops all we want, but if people can't get *points*, they can't buy anything in there... This makes adding them kinda pointless. Maybe I misunderstood you, and that's what you meant, @Cosrnos =|

As is, the shop would only be useful for players that get points from a GM, but that GM could just as well give them the cards or items they want.

In an actual game, you would buy the points in the web portal of the game. Said portal would usually also have the shop, all integrated into one. I'm starting to wonder if we should even put premium shops into the core. They would be barely usable like this, and they'd have to replaced anyway?

**Comment by Cosrnos** [comment]
Actually the points aren't the part I was talking about. Let people emulating aura decide how they want to give points, whether it is through in game exchange or manually adding the points to the user's accounts. Leave the shop, the buying part of it in the core feature.

I'm saying you shouldn't create an admin panel to manage the items in the shop.

Also when I say "Someone else," that someone else could be you in the future after aura v1 is complete. I think it's important to build the pages & items for the core but don't build any sort of admin panel for the items.

**Comment by exectails** [comment]
>I'm saying you shouldn't create an admin panel to manage the items in the shop.

Why would I add a shop but not a simple way to manage the goods? o.o

**Comment by Cosrnos** [comment]
Because it's scope creep of the feature. AGILE AGILE AGILE

![](https://media.giphy.com/media/xTiTnjFNBP5xYOeyTS/giphy.gif)

**Comment by exectails** [comment]
>it's scope creep

How so? The shop has clear requirements, the admin panel would just be a UI to edit the shop table. Wouldn't the shop be even less useful if admins don't have a way to modify it? A dev can build his own panel of course, or edit the database directly, but that's not a great solution for newbie level users.

**Comment by Cosrnos** [comment]
From a player perspective (non gm, the primary thing we're emulating) does this add more value to the product?

IDK about you but I don't think it's worth spending time spoon feeding people who want to run this server locally. I think you should focus on building the core as fast as possible. If the DB is hard to manipulate to make things custom and the person REALLY wants something custom they should either learn to customize it or have someone do it for them.

You shouldn't be catering to newbie level users who have no chance of giving back to the project right now. You should spend your time catering to users who have a drive to give back to the project in a legitimate way, meaning the content they create is that of the original product.

You can always backfill these things and make that panel once you have more time and the emulator is more finished. Right now it's little value add IMO

**Comment by exectails** [comment]
You've got a point, but if I added a shop without a way to modify the goods, I feel like it would be useless for both players *and* admins. The players can't buy anything without the admin adding a way to get points and the admin can't modify the goods, so he has no control over the cards, pets, and items that are sold.

I try to see Aura as a software product for anybody, pro or newbie, that's supposed to be as easy to use as possible, with it giving users the ability to quickly set up and manager a server. If I am to add a shop, I naturally want it to offer what its users expect, which would, imo, include a way to manage the goods. It's simply part of the feature for me.

>IDK about you but I don't think it's worth spending time spoon feeding people who want to run this server locally.

That's exactly it, I wonder if putting a shop in, in whatever fashion, would be a waste of time, when anybody who's remotely serious about running a game would set up their own website, shop, etc. Same as our registration page, which nobody will ever use seriously, because it lacks things that you can't build in. And those who run local servers for themselves or 2.5 friends can just use GM commands. We might want to move the card distribution into scripts, so they're easier to modify, but that's a different topic.

**Comment by Cosrnos** [comment]
Honestly I would table this feature in favor of something else. Like you said if someone was serious about running a game they would set up their own shop. Hell when I ran chainogi I custom built the point system myself.

**Comment by exectails** [comment]
I've added poll on the forum, to see what the community thinks: http://aura-project.org/forum/topic/183-premium-shop/

**Comment by DeleteIT** [comment]
Have a web server that can communicate with the DB and other servers (for guilds and such?), and then leave people to get on with it.
If people can't (or don't have the drive to) work out how to use the DB reading/writing functions in Aura, and how to serve a webpage with the web server, they're not the target for that functionality.

*Someone* can always add in an extremely basic webpage/shop at a later date, if *anyone* gets around to it, but ultimately, not your problem, functionality is there.
