### ISSUE TITLE
Adv. dungeon pass ->Normal dungeon

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#102]
Dropping an advanced pass takes you to a regular dungeon. In this case I tried to drop a Ciar Adv pass, but ended up in a normal Ciar. Aren't advanced dungeons implemented yet?

**Comment by Sairii** [comment]
If you really mean advanced then yes they arent implemented yet.
They are not G1.

https://docs.google.com/spreadsheets/d/1y612YbDSfozuNfsE6UHqljNq0RiyL7fbqWv9XrHvws0/edit#gid=717848693

old list of mine with generation and stuff

**Comment by Pegwald** [comment]
Then I understand ^^
Thanks! I will have a look at your document as well.

**Comment by exectails** [comment]
While the reason is obvious when you know it, we should probably add a notice or something to make it clear.
