### ISSUE TITLE
No pick up restriction for other players drops

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#103]
Whenever you're in a party or on your own and you finish a mob and it drops something, any player will be able to pick it up (without any restriction) and laugh at how easy getting AR page 8 was. This has been very fun for most people on my server (including myself), but we know that this is not how it should work.

**Comment by exectails** [comment]
I don't remember the exact rules, what can you pick up, and what's restricted? Is everything dropped from "your" monster yours? Is there a time limit on it? And is it different in a party? Don't know what to search for on the Wiki ~_~

**Comment by Pegwald** [comment]
Mostly anything, I believe. Mob drops, even if in party or not, books, drops from harvesting. I have not tested spirit weapon yet. That would be silly if you could trade spirit weapons.

**Comment by DeleteIT** [comment]
***All*** drops (even lamp post/prop ones) are for the player that caused them to be created, and they remain that player's for exactly the length of time it takes a mob's body to turn into a smoke poof.

It's the same in a party.

Certain items cannot be picked up by other players though, Black Orb pieces when slapped out of the prop in the final room for example, will never allow a different player to pick them up, but are trade-able.

**Comment by exectails** [comment]
> will never allow a different player to pick them up, but are trade-able

Hm, maybe because of the `quest_item` tag. Lost Earring has the same tags as Black Orb Fragments, is that item tradeable as well? And can you pick it up when someone else hits the snowman?

**Comment by DeleteIT** [comment]
They're not, you can't trade or pick them unless you caused them to exist.

**Comment by exectails** [comment]
>They're not, you can't trade or pick them unless you caused them to exist.

But you can trade fragments, which are "Static Item"s, unlike the earring, which is a "Character Personal Item". Makes sense I guess.

**Comment by exectails** [comment]
What about players dropping items, are there differences there? Like, others can't pick up the fragments after they drop from the prop, but can you pick them up if a player drops them?

And about AR pages... are those really protected...? They don't have any special tags or action, and I don't remember pages being protected.

**Comment by DeleteIT** [comment]
No, the fragments can only be traded.

AR pages are protected like any drop, with the timer I mentioned.

On 19 Nov 2015 1:23 p.m., exec <notifications@github.com> wrote:

What about players dropping items, are there differences there? Like, others can't pick up the fragments after they drop from the prop, but can you pick them up if a player drops them?

And about AR pages... are those really protected...? They don't have any special tags or action, and I don't remember pages being protected.

**Comment by Sairii** [comment]
I thought the timer differs? Like it does with fishing items.
Item worth alot = long timer
crap item = short timer

**Comment by DeleteIT** [comment]
That's the evaporation timer. The pick up timer is the time it takes for a vanquished mob to turn to smoke.

On 19 Nov 2015 3:36 p.m., Sairii <notifications@github.com> wrote:

I thought the timer differs? Like it does with fishing items.
Item worth alot = long timer
crap item = short timer

**Comment by exectails** [comment]
>That's the evaporation timer. The pick up timer is the time it takes for a vanquished mob to turn to smoke.

I wonder about that... right now we're using 20 seconds as disappear time for monsters. I don't remember it that's based on actual research, but it doesn't feel like much of a protection.

**Comment by DeleteIT** [comment]
It's definitely the time it takes for a mob the killing player delivered the final blow to, to disappear, because I've noticed on *MANY* occasions that the mob disappeared, and that's the moment I could pick up the item.

**Comment by xeroplz** [comment]
I steal peoples items that they don't pick up on NA if they fail to get them before the monster poofs. It's just how it goes. I'm not sure how the evaporation timer goes, but :+1: @DeleteIT , monster poof = fair game for everyone.

**Comment by exectails** [comment]
Okay. I just find it weird because @Pegwald said this would make getting AR8 much easier, but if pages aren't special, and are only protected for say 20 seconds, why would it be *easier* on Aura atm?

**Comment by DeleteIT** [comment]
>*any player will be able to pick it up (without any restriction)* and laugh at how easy getting AR page 8 was.

It's a joke.
He's saying that you wait for someone else to make the kill, then dash in before the player can even move.

**Comment by exectails** [comment]
Oh. Hm o,o

**Comment by exectails** [comment]
Alright, this should be fixed now. Consider it a quick fix, I'm sure there are more cases that will need to be handled in the future. For now, normal items are protected for X seconds (configurable) and personal items, like the ones mentioned here before, are protected forever, so nobody else can pick them up.
