### ISSUE TITLE
Walter's empty sewing patterns

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#106]
Are those sewing patterns unimplemented? They are empty at least, but is Walter the only NPC who is selling empty sewing patterns? I just find it weird that Nora is the only NPC selling a few patterns when tailoring has just been implemented.

**Comment by QewQew** [comment]
Shops have to explicitly be set to show the item that the manual is for. Since Walter's script hasn't been updated since the dictionary info for items was implemented, it won't show up.

**Comment by Pegwald** [comment]
I see. There will be a time for that later then, I guess

**Comment by exectails** [comment]
The reason Nora has hers is that I added them, I had to buy them somewhere during testing after all^^ Though I guess we can consider it a bug that Walter's are empty, they shouldn't even be there in this state.
