### ISSUE TITLE
Gold Pouch Vanishing / Bug

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#107]
There are currently 2 Bugs / Issues with the Gold Pouches.

Issue 1 Vanishing Gold Pouches:
-> Gold Pouch 1 has 1Gold, Gold Pouch 2 has 1Gold.
Drag Gold Pouch 2 ontop of Gold Pouch 1.
Now Gold Pouch 1 has 2Gold but Gold Pouch 2 vanished.

This only happens if Gold Pouch 2 gets completely emptied.

Issue 2 Server Offense:
-> Gold Pouch 1 has 1Gold, Gold Pouch 2 has 0Gold.
Drag Gold Pouch 2 ontop of Gold Pouch 1.
After one or two clicks the connection gets closed with the server throwing up the following exception:
CharacterName just commited a Server offense. Incident report: GetItemSafe: Creature does not have a Item 0x50F00000000370

After logging back in Gold Pouch 2 vanished and you have Gold Pouch 1 in your hands / on cursor.

**Comment by exectails** [comment]
Thanks for the report. Coincidentally these two were related, but if you're not sure if multiple problems have something to do with each other it would be better to create separate issues in the future, makes it cleaner.
