### ISSUE TITLE
Error after updating build.

### ISSUE THREAD

**Issue by majorcyto** [aura-project/aura#107]
__     __  __  _ __    __
                        /'__`\  /\ \/\ \/\`'__\/'__`\
                       /\ \L\.\_\ \ \_\ \ \ \//\ \L\.\_
                       \ \__/.\_\\ \____/\ \_\\ \__/.\_\
                        \/__/\/_/ \/___/  \/_/ \/__/\/_/

                         by the Aura development team
________________________________________________________________________________

[Info] - Reading configuration...
[Info] - Initializing database...
[Info] - Loading data...
[Info] -   done loading 167 entries from features.txt
[Info] -   done loading 20 entries from ancient_drops.txt
[Info] -   done loading 550 entries from races.txt
[Info] -   done loading 3 entries from stats_base.txt
[Info] -   done loading 3 entries from stats_levelup.txt
[Info] -   done loading 3 entries from stats_ageup.txt
[Info] -   done loading 55 entries from motions.txt
[Info] -   done loading 9 entries from charcards.txt
[Info] -   done loading 107 entries from colormap.dat
[Info] -   done loading 15554 entries from items.txt
[Info] -   done loading 35 entries from chairs.txt
[Info] -   done loading 560 entries from skills.txt
[Info] -   done loading 387 entries from regions.txt
[Info] -   done loading 392 entries from regioninfo.dat
[Info] -   done loading 607 entries from shamala.txt
[Info] -   done loading 3 entries from prop_drops.txt
[Info] -   done loading 200 entries from exp.txt
[Info] -   done loading 302 entries from pets.txt
[Info] -   done loading 13 entries from weathertables.txt
[Info] -   done loading 27 entries from weather.txt
[Info] -   done loading 4556 entries from keywords.txt
[Info] -   done loading 779 entries from titles.txt
[Info] -   done loading 2362 entries from itemupgrades.txt
[Info] -   done loading 6394 entries from props.txt
[Info] -   done loading 1736 entries from prop_defaults.dat
[Info] -   done loading 165 entries from collecting.txt
[Info] -   done loading 27 entries from fish.txt
[Info] -   done loading 6 entries from fishing_grounds.txt
[Info] -   done loading 17 entries from dungeon_blocks.txt
[Info] -   done loading 27 entries from dungeons.txt
[Info] -   done loading 1321 entries from cutscenes.txt
[Info] -   done loading 264 entries from actors.txt
[Info] -   done loading 216 entries from production.txt
[Error] - Error while loading data.
[Exception] - System.Runtime.Serialization.SerializationException: Cannot deseri
alize member 'UInt16 AttackMin' of type 'Aura.Data.Database.ItemData'. ---> MsgP
ack.MessageTypeException: Cannot convert 'System.UInt16' type value from type 'F
ixedRaw'(0xA8).
   at MsgPack.ItemsUnpacker.ReadSubtreeNullableUInt16(Nullable`1& result)
   at MsgPack.SubtreeUnpacker.ReadNullableUInt16(Nullable`1& result)
   at MsgPack.Serialization.UnpackHelpers.UnpackNullableUInt16Value(Unpacker unp
acker, Type objectType, String memberName)
   --- End of inner exception stack trace ---
   at MsgPack.Serialization.UnpackHelpers.UnpackNullableUInt16Value(Unpacker unp
acker, Type objectType, String memberName)
   at MsgPack.Serialization.EmittingSerializers.Generated.Aura_Data_Database_Ite
mDataSerializer15.UnpackFromCore(Unpacker )
   at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker
)
   at MsgPack.Serialization.EmittingSerializers.Generated.Aura_Data_Database_Man
ualDataSerializer62.UnpackFromCore(Unpacker )
   at MsgPack.Serialization.DefaultSerializers.System_Collections_Generic_List_1
MessagePackSerializer`1.UnpackToCore(Unpacker unpacker, List`1 collection, Int32
 count)
   at MsgPack.Serialization.DefaultSerializers.System_Collections_Generic_List_1
MessagePackSerializer`1.UnpackFromCore(Unpacker unpacker)
   at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker
)
   at MsgPack.Serialization.AutoMessagePackSerializer`1.UnpackFromCore(Unpacker
unpacker)
   at MsgPack.Serialization.MessagePackSerializer`1.UnpackFrom(Unpacker unpacker
)
   at MsgPack.Serialization.MessagePackSerializer`1.Unpack(Stream stream)
   at Aura.Data.DatabaseBase`2.LoadFromCache(String path) in D:\Jerrod\Github\au
ra\src\Data\Database.cs:line 136
   at Aura.Data.DatabaseBase`2.Load(String[] files, String cache, Boolean clear)
 in D:\Jerrod\Github\aura\src\Data\Database.cs:line 110
   at Aura.Shared.ServerMain.LoadDb(IDatabase db, String path, Boolean reload, B
oolean log) in D:\Jerrod\Github\aura\src\Shared\ServerMain.cs:line 264
   at Aura.Shared.ServerMain.LoadData(DataLoad toLoad, Boolean reload) in D:\Jer
rod\Github\aura\src\Shared\ServerMain.cs:line 221
[Info] - Press Enter to exit.

=====================

I pulled all the latest changes, it compiled fine and when starting, all of the server sections start fine except channel. o.o...

**Comment by QewQew** [comment]
Delete your cache.

**Comment by exectails** [comment]
https://github.com/aura-project/aura#errors-after-updates

**Comment by QewQew** [comment]
If you want people to read your README's, you gotta name them DONTREADME.

**Comment by majorcyto** [comment]
TBH, i didn't even realize the cache folder existed sorry about that lol.
