### ISSUE TITLE
Material loss fixed at 5?

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#116]
Whenever I use a production skill such as weaving and I queue the production, I notice I always lose a fixed amount at the time, being 5. However, it is differen't at the last queued item being processed.

Here's an example. Pegwald wants to make 5 thick thread balls which cost 5 wool each. Pegwald has 25 wool (yay). Pegwald queues the production of 5 thick thread balls.
1st thick thread is a fail. He loses 5 wool. 2nd fails and he looses another 5 wool. 3rd is a success, but the 4th attempt fails as well. he loses another 5. Then the final one fails too, but this time Pegwald only looses 2 wool.
Here's the question. Isn't this a bit harsh for poor, unlucky Pegwald?

**Comment by QewQew** [comment]
>				// On fail of non-queued productions you lose 1~amount of
				// materials randomly

Where exactly did you get this, @exectails?

**Comment by QewQew** [comment]
The "non-queued" portion, that is.

**Comment by exectails** [comment]
Personal experience and what people told me. I clearly remember not always loosing all mats. @Pegwald then told me that on queue, all mats are supposed be used (#61). Unless I misunderstood something there o,o

The reason you don't lose a fixed amount on the last try is that in the eyes of the server, the last try isn't queued. The client resends the Prepare packet over and over, reducing the amount to produce, so on the first of 5 tries, the server gets "produce 5", then it gets a packet saying "produce 4", and so on. On the last one it gets 1, which is the same as unqueued... I guess I'm missing something here, if the rules really are as stated =/

**Comment by QewQew** [comment]
Queued up 22 Wools for 4 Thick Threads. 
![image](https://cloud.githubusercontent.com/assets/11168098/11460306/a6879c78-969e-11e5-960f-b1570c5b4bd6.png)

1st: Fail, 18 Wool left
![image](https://cloud.githubusercontent.com/assets/11168098/11460308/b4829346-969e-11e5-8014-d03c4f2516e6.png)

2nd: Fail, 15 Wool left
![image](https://cloud.githubusercontent.com/assets/11168098/11460309/ba924ea2-969e-11e5-8302-3556ca4e93b1.png)

3rd: Fail, 11 Wool left
![image](https://cloud.githubusercontent.com/assets/11168098/11460311/bf19872e-969e-11e5-845a-05760e9be0c1.png)

4th: Success, 6 Wool left
![image](https://cloud.githubusercontent.com/assets/11168098/11460312/c5d4da64-969e-11e5-89ca-9b743aa70cde.png)

Holy crap, you can paste+upload into this. Never read that bottom tip.

**Comment by Pegwald** [comment]
I should try recording it when I get my hands on some more wool ^^

**Comment by exectails** [comment]
So it's always random? Hum. Then I guess this is fixed.

**Comment by Pegwald** [comment]
> @Pegwald then told me that on queue, all mats are supposed be used (#61).

This was regarding potion making. It is very odd, but potion making is the only skill I know of that can mass produce all materials at once, instead of one by one. When making 20 potions and unqueue, they will all be made at the same time. If you fail, some material is lost, if success, all potions are made successfully.

I think i got off track there, but what I meant there was when you're failing at making a potion that require 1 base herb and 1 some-other-herb, you will lose at least 1. If it cost 2 herbs, it would cost at least 1, but have a chance of costing you 2.

**Comment by exectails** [comment]
So that was specific to Potion Making? Okay =| We should still double-check and confirm that on NA I guess.

**Comment by Pegwald** [comment]
You mean the mass production of potions? I can do that.

**Comment by exectails** [comment]
The mass production, and how much you lose in which cases.

**Comment by QewQew** [comment]
>potion making is the only skill I know of that can mass produce all materials at once, instead of one by one. 

I'm not sure how that is different from any other production skill? You just uncheck queue items and you will create all at once, rather than one at a time.

>I think i got off track there, but what I meant there was when you're failing at making a potion that require 1 base herb and 1 some-other-herb, you will lose at least 1. If it cost 2 herbs, it would cost at least 1, but have a chance of costing you 2.

I'm don't see what's different here either.

**Comment by Pegwald** [comment]
> I'm not sure how that is different from any other production skill? You just uncheck queue items and you will create all at once, rather than one at a time.

I have tried this with other skills, like weaving and handicraft, but when I uncheck queue, it only produces 1 item.

**Comment by QewQew** [comment]
>I have tried this with other skills, like weaving and handicraft, but when I uncheck queue, it only produces 1 item.

![image](https://cloud.githubusercontent.com/assets/11168098/11460594/0f4c4e48-96a4-11e5-88f2-33ea9fe4cc9e.png)
![image](https://cloud.githubusercontent.com/assets/11168098/11460597/159d860e-96a4-11e5-9c22-26789866e710.png)
Yes, I tossed out the stuff I had earlier.

**Comment by Pegwald** [comment]
I couldn't manage to fail at mass producing (due to my awesome levek skills, ofc). However, I did manage to render some footage of me mass producing those pots.
My expirience is that whenever I fail at mass producing for example 5 pots at once, I will lose a random amount of materials used, from 1-5. This means I can lose like 5 mana herbs and 2 base herbs, or even just one of each.

When making big potions, mp 100 or so, I spend 50 mana all at once. Then I get to know if i either successfully crafted the potions or not. I spend 50 whatever happens, basically.

**Comment by QewQew** [comment]
That sounds right, but that seems to be an entirely different topic from this issue.

The issue in this issue is the item loss in a queued production, where you previously stated that you would lose ***all*** items of an attempt in a failure.

**Comment by Pegwald** [comment]
Yeah, I sort of got off track again, but I just felt like I had to post my response and result of the request  exec made earlier here.

The fixed subtraction of materials-issue is at least fixed for now.
