### ISSUE TITLE
Unable to finish crafting an item using blacksmith

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#117]
When crafting an item using blacksmithing, you can't really finish the item. At 99.9%, the skill window closes and the character is frozen, forcing you to relog. This was reported by one of my friends on the server, so I have not yet experienced this bug myself.

**Comment by exectails** [comment]
Another one I can't reproduce =/ We really need more information for these kind of bugs. What blueprint, what finish, any errors in the logs or the console? Everything that could go wrong in Blacksmithing *should* have an error message for the log, the player, or both.

**Comment by Pegwald** [comment]
I will try to recreate this bug myself. I know He was using bolt heads blueprints and regular arrowhead blueprints.

**Comment by Pegwald** [comment]
I managed to capture it myself - https://youtu.be/lelUtankiBY

**Comment by exectails** [comment]
The problem was that arrow heads don't require a finish, the server couldn't handle that, which resulted in a long and clear exception message in the log^^ Afterwards you would be stuck of course, because after an exception no response to the skill packet is sent.

**Comment by Pegwald** [comment]
oh, I couldn't remember that myself. Good job! ^^
