### ISSUE TITLE
Certain actions with eiry result in a disconnect.

### ISSUE THREAD

**Issue by epicmiro** [aura-project/aura#118]
Some handling with eiry results in you getting a force kick.

The only method i discovered so far is by choosing Ask a Question -> What is a quest
and then clicking the X button in the eiry dialogue.

**Comment by exectails** [comment]
Any errors in the channel server? Let's hope that's not a client issue...

**Comment by epicmiro** [comment]
I havent tested it on my local server and its not up to date so I can't really check atm.

**Comment by tygarimew** [comment]
2/22/2015 8:39:29 PM [Warning] - Client '-' : Account '-' (Controlling 'Sheep Lord') just committed a Moderate offense. Incident report: EnsureValid: Invalid NPC session
