### ISSUE TITLE
Weapon repair cost is unaccurate

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#123]
I tried repairing some bastard swords at Nerys shop today. It was listed that she would fix 1 point for 970g or something, but she took way more gold for that 1 repair. I suspect this is because my sword is upgraded and this may have something to do with it, unless the repair price is already wrong on a basic bastard sword.
I can also record it and share it if that's preferred.

**Comment by QewQew** [comment]
Exactly how much was taken? Where was the sword from? (store bought, >item?) What upgrades?

**Comment by Pegwald** [comment]
I believe it was bought from Elen, then upgraded at Nerys once (Nerys Bastard Sword Enhancement), then a couple of weight adjustments at Ferghus (2 and 3). The repair would cost me 948g, but 1896 was subtracted instead. That's actually twice the amount.

**Comment by Pegwald** [comment]
She actually failed the repair once too, subtracting the regular amount

**Comment by exectails** [comment]
13 minutes! I wonder if that's a new record o.o

**Comment by Pegwald** [comment]
![applause-gif-tumblr-43_zps4e464b19](https://cloud.githubusercontent.com/assets/13089450/11543924/8589872c-993f-11e5-94f5-2759166f855c.gif)
