### ISSUE TITLE
Tag check evaluator

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#127]
Our current tag checks use regex, to check if a given tag matches an item or race. For the enchants we need proper evaluation though, as the strings are more complicated. For example:
```
*/equip/*&*/glove/*|(*/equip/*&*/bracelet/*)|(*/equip/*&*/ophelia_glove/*)
```
We could adjust the current function a little again, to support that, but we might want something real, so we don't have to constantly fix that function when something new comes around.

We don't necessarily need this to finish enchants, but for the security checks.

**Comment by exectails** [comment]
So far so good.
https://gist.github.com/exectails/a6d65028406d06abd29d

**Comment by QewQew** [comment]
Since it's in the,  are there really xors in any of the client files?

**Comment by exectails** [comment]
@QewQew I haven't seen any yet, and I wouldn't expect it, but it wouldn't surprise me either =<
