### ISSUE TITLE
[Request] Support for loading scripts from dll

### ISSUE THREAD

**Issue by ImaBrokeDude** [aura-project/aura#129]
I was wonderiny if it would be possible to support loading scripts from dll files. Some apps I have used allowed me to use single files or dlls for extensibility stuff. Not trying to be extra difficult.

**Comment by exectails** [comment]
https://github.com/aura-project/aura/blob/master/src/Shared/Scripting/ScriptManager.cs#L240

We support that already. I remember there being problems... maybe with reloading, but it should load a DLL listed in the script lists just fine.

**Comment by ImaBrokeDude** [comment]
Ah somehow I missed that. I knew I should have asked in the chat first.

**Comment by exectails** [comment]
*Somehow*!? It's completely undocumented and hidden deep in a Shared class, I'd wager nobody but me knew these 2 lines existed^^" An issue was absolutely fine, the forum would've been even better, it would've been easier to find for others in the future.
