### ISSUE TITLE
Moongates

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#13]
*G1* Moongates, if possible. Ideally with an option to switch between the two systems. Special attention must be payed to the changes based on features and available places, e.g. the Emain MG must not be available while the town is sealed off.

**Old**
- http://wiki.mabinogiworld.com/index.php?title=Moon_Gate&oldid=33556
- http://wiki.mabinogiworld.com/view/Moongate_Timetable

**New**
- http://wiki.mabinogiworld.com/view/Moon_Gate

**Checklist**
- [X] New gates
- [x] Old gates

**Comment by xCryptic** [comment]
This should be done pretty soon too. Once you setup a base, I can go around logging them all and (hopefully) add them in. :+1:

**Comment by exectails** [comment]
We have some data in Legacy, I believe I actually even had them implemented, but I think that was before some new/old ones were (re)added.
