### ISSUE TITLE
AI doesn't react unless you move.

### ISSUE THREAD

**Issue by DeleteIT** [aura-project/aura#130]
If you telewalk into an enemy's visual range (from outside of it), it'll ignore you, unless you take a normal step.

http://puu.sh/gjhKQ/5188f2898b.png
On the upside, we're BFFs now, for as long as I don't move.

GMCP map click counts as movement though, apparently.

**Comment by exectails** [comment]
I can't reproduce this issue, if I telewalk into a wolf's range it aggros me as normal.

**Comment by DeleteIT** [comment]
Odd. Maybe it got resolved with a later update, I think I was a couple of revs behind.

I'll check it again and make sure.

**Comment by DeleteIT** [comment]
No, this still happens.

Turn on telewalk, and teleport from one side of the wolves to the other, using only telewalk, and the mobs don't activate.

**Comment by exectails** [comment]
Oh~ now I get it, the AIs aren't active! We only activate them when you walk into range. I guess I should add that to the command.
