### ISSUE TITLE
Party Error (2)

### ISSUE THREAD

**Issue by RashataanVuul** [aura-project/aura#133]
I'm sorry. Uhm, I tested it see if it was fixed and, I got the same results but a different error.
http://puu.sh/lPWYQ/d40ced0fd2.png

**Comment by Pikachews** [comment]
And that happens exactly when someone tries to join a party?

**Comment by RashataanVuul** [comment]
oh, sorry. I was waiting for Exec. Here: https://github.com/aura-project/aura/issues/132#issuecomment-162835928

**Comment by Pikachews** [comment]
That looks like the same error..? But all I'm getting out of it is that someone disconnected.

**Comment by exectails** [comment]
@Pikachews I explained what happened in the commit that was supposed to fix it, the clients froze/dced because of a bug, which then caused those errors.

@RashataanVuul I can't reproduce this anymore after my fix o.o Are you sure you updated and recompiled?

**Comment by RashataanVuul** [comment]
@exectails oh I'm terribly sorry. I thought I updated Aura correctly but it would have seem that I've forgottened to recompile. Everything is fine now. Thanks

**Comment by exectails** [comment]
Alright^^
