### ISSUE TITLE
incorrect durability on tools

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#135]
Pickaxe, gathering knife and gathering axe have this one bug in common. Whenever it is being used it will sometimes stop losing durability after a while if you are gathering materials. I have used an pickaxe that reached 1/10 durability on two entire Barri runs without it burning out. However, upon relogging the durability on those tools seems to synchronize with it's true durability, making that pickaxe from earlier 0/10.

I have also discovered that if I try to fix a tool bugged like this, it will repair the true durability, so if i had that pickaxe 1/10 and repaired one point, it would be 1/10.

I'm not sure if I managed to make any sense out of this, but something is at least wrong with being able to gather 'infinite' wool, wood and ore.

**Comment by exectails** [comment]
Well, no wonder, looks like no durability update is ever sent when gathering =< Like, the durability won't change at all while *only* gathering. Does that match your findings?

**Comment by Pegwald** [comment]
That's pretty much it. You're the best ^^

**Comment by exectails** [comment]
It would've been, but I wanted to go to bed last night, and didn't want to wait for your confirmation, so I didn't commit it^^
