### ISSUE TITLE
Item drop placing from gathering

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#136]
How come I haven't noticed this before now? When gathering material like wool and herbs, I've noticed that sometimes the item will drop just out of reach so your character has to move to pick it up. That's not really how it works in official. When gathering something in official, the item will always drop right under your character, unless there's something already there. What I mean about this is that the drop placement is not supposed to be random, and certainly not out of reach.

**Comment by exectails** [comment]
It's a little random... isn't it?

**Comment by Pegwald** [comment]
first drop is fixed to be directly under the character. If the item is picked up, next one will also drop right below like the first one. If the first one is not picked up, then the second one will be dropped somewhere else, sometimes out of reach.

**Comment by QewQew** [comment]
Normal behavior.

**Comment by exectails** [comment]
>first drop is fixed

Didn't want to believe if, but it does seem that way o~o Problem is, I'm not sure how to code that, we'd have to check if an item, specifically wool, is sitting in a specific spot in the region. While possible, that seems really inefficient to me. Though I can certainly fix them dropping out of range.

**Comment by exectails** [comment]
How about we drop them in a random radius around a spot between player and resource (sheep, herb, etc)?

**Comment by exectails** [comment]
Actually... it might not be so inefficient after all. Since the character and the sheep don't move, the position onto which the item drops will always be the same. So we just have to iterate over the items on the floor and check their X and Y values. If an item is found at that exact spot, it's dropped somewhere else.

**Comment by exectails** [comment]
Alright, the way I did this now is that I calculate a position a few cm away from the gatherer as the drop position. If there is another item on that exact position already, I generate random positions until a free one was found.

It feels good to me, give it a try and tell me if it's still off.
