### ISSUE TITLE
no windmill crit on multiple enemies

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#137]
When fighting those 'AI-less' monsters in dungeons, I've noticed that every time I critical hit with windmill, only one of the mobs will take the critical hit. In official I know for a fact that if it is a critical wm, all the enemies within the AoE will take the critical hit. I'm not sure if it is supposed to be like this, if wm really had this function before or this simply haven't been implemented yet.

**Comment by exectails** [comment]
Yea, I think you're right. Right now we handle crits separately for every target. The check whether a crit should occur has to be moved outside the target loop, and the crit has to be handled for every target if one occurred.

**Comment by exectails** [comment]
Can anyone else confirm that that's how WM is supposed to work? Just to make sure.

**Comment by superjeffreyc** [comment]
Either all the targets from WM get crit or none get crit.

**Comment by exectails** [comment]
Thanks.
