### ISSUE TITLE
Defense>dual wield

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#141]
Whenever you attack someone using defense, you are supposed to realize it being a bad idea, but the case is not the same if you're equipped with two swords. First strike will trigger defense, but this does not stun your character for the second strike from the other sword. The one using defense will be stunned instead and then be messed up really bad.  I am pretty sure if you have two swords and strike a foe using defense, your character will swing one sword and be stunned from the defense. Right now it is just useless for one to charge defense against someone with two swords.

**Comment by exectails** [comment]
Oh. Well, this *is* implemented, but due to a change a few weeks ago, the check for it currently checks the wrong thing.
