### ISSUE TITLE
KR client say "Service period expired."

### ISSUE THREAD

**Issue by Willowslab** [aura-project/aura#144]
it's problem is only private develop Mabinogi MOD server issue.
 i thought this issue made by Payment Service (KR Name : Premium Plus Package).

(why i using KR Client, KR Client "Package" Validate procedure skipped.)

how do i passing this procedure?

**Comment by exectails** [comment]
I don't know that error, but regardless of that, Aura doesn't support the KR client right now. You'll have to get the latest, updated NA client.

**Comment by Willowslab** [comment]
@exectails 

msg.etc.no_connect_timeout << is Client Localization Codename : Local\Code\Interface.(SERVICEAREA).txt

(KR Language File content is "플레이 제한시간이 초과되어 게임에 접속할 수 없습니다.")

Applying the NA client until these issues will be resolved. 
I would appreciate if this issue has given nerve to be resolved.

**Comment by Fuhhue** [comment]
the issue wont be resolved.. Compatibility to all major versions but NA was dropped on 2013-09-13 (Aura Legacy). Since that time, Aura is kept compatible only to the latest update of NA.

**Comment by exectails** [comment]
We would like to support other versions again at some point, like KR and EU, but it's too time consuming at this point. It will take a while.
