### ISSUE TITLE
Windmill training

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#146]
I have heard from others on my private server that ranking windmill has been very tricky on higher ranks. Like, defeating several powerful enemies doesn't work on awful mobs, but suddenly triggers on mimics and goblins who are similar ranked. I have not experienced this myself, but this is just something I picked up recently.

**Comment by exectails** [comment]
Hm. It might have something to do with this:
```
// "When training multiple hits/kills, the player must hit four or more targets.
// To fulfill the "kill" condition, the player must finish all four targets simultaneously.
// At least one must be "Strong" while the rest are either lower or equal in power or else you will not receive the points."
// http://wiki.mabinogiworld.com/view/Windmill#Training_Method
```
The way we implemented it is that we check if one of the targets has *exactly* the required rating, for example "Normal" or "Strong", and then whether we have 4 or more targets that have that or a lower rank. For rE-D that would mean:
```
if at least 1 strong target and 3 others that are strong or below then:
    train skill
```
It doesn't count creatures that are above the required rating, that's how I interpreted the Wiki. Is that incorrect? You said "awful", but I don't see a training requirement for several awfuls (very powerful) on the Wiki, only for strongs (powerful)

**Comment by Pegwald** [comment]
Oh, I meant strong enemies, not awful. However, I already know it doesn't count enemies who are stronger than powerful (if training several powerful), but it was somehow possible to train it on less powerful mobs, like weak and similar ranked enemies.

**Comment by exectails** [comment]
I haven't tested this yet, but it should work. The old code was really weird, no wonder that didn't work...

**Comment by DeleteIT** [comment]
I seem to recall that the "group level" is brought to the single highest creature you kill, meaning that
`>= 4 strong + 1 awful = awful group`.

**Comment by xKamuna** [comment]
Yup, @DeleteIT is correct.

**Comment by exectails** [comment]
Isn't that exactly what we're doing? o,o

**Comment by DeleteIT** [comment]
>var multipleEnemies = (matches.Count() >= 4 && matches.Any(a => aAction.Creature.GetPowerRating(a) == PowerRating.Strong));

Doesn't that mean "if any are strong" as opposed to "the strongest mob == group level" ?

**Comment by exectails** [comment]
It means what I said above, "if there are 4 <= strong and at least one is actually strong". That means if you were to hit 4 mobs of which one is awful, it wouldn't train the skill, because one isn't <= strong. *But*, you could train the skill by hitting 4 strongs + 1 awful, as there are enough strongs.

**Comment by DeleteIT** [comment]
Which is wrong, as I said above.

**Comment by exectails** [comment]
You've actually tested this? If you hit 5 monster, of which 4 are strong and 1 is awful, you don't get the training for multiple strongs?

**Comment by DeleteIT** [comment]
On official, that's how it works. The highest strength monster in a group is the strength of that group.

At the very least, that's how it works for windmill, I remember being perplexed as to why my group of strong kills didn't count, until I realised I'd killed a boss mob as well.

**Comment by exectails** [comment]
Well, I'm not really convinced. But both would make sense, in different ways. Anyone else who will testify to that? If you kill *5 monsters*, one being awful and 4 being strong or below, do you get the multi hit training for strongs? (Same goes for awful+boss and normal+strong of course.)

**Comment by QewQew** [comment]
Delete is right.
