### ISSUE TITLE
Dungeon boss-room generation bug

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#147]
It has happened twice now that whenever I am about to do a boss of a dungeon, I am greeted with an already open boss door, but no boss. I was not able to find any key and the treasure room is still locked. If it's necessary, I do have some footage of it that I can share with you.

**Comment by Pegwald** [comment]
After managing to glitch through the door, I found no reward chests. I was able to use the statue to get out, however.

**Comment by exectails** [comment]
Which dungeon? And were there any errors in the log files?

**Comment by Pegwald** [comment]
Happened in Barri once, then once more in Alby int for 2

**Comment by exectails** [comment]
Well, first of all, let's summon @Tachiorz , because he coded that and might have an idea.

You probably don't know when it happened anymore, do you? So you can check the log files? What you're describing should hopefully not happen without error log.

**Comment by Tachiorz** [comment]
So boss door in the last section wasn't locked and thus boss wasn't spawned. I'll try to figure out what happened there.
@exectails I think we should log dungeon name, item and seed to debug cases like this.

**Comment by exectails** [comment]
Yea, that's probably a good idea, I'll add it.

**Comment by Pegwald** [comment]
Ok, here's the log on the alby int for 2 run.

[ChannelServer.txt](https://github.com/aura-project/aura/files/68624/ChannelServer.txt)

The run I had in Barri was a while ago, so I'm affraid I can't find that one. Hopefully this should be enough ^^

**Comment by exectails** [comment]
Quite a few warning/debug messages, but I don't see anything related to dungeons. Too bad =/ And I guess I should actually play Aura a little, I'm concerned about those lock debug messages I see there =<

**Comment by DeleteIT** [comment]
Is it possible that those boss rooms were orb sealed, and the orbs failed to spawn?

**Comment by DeleteIT** [comment]
Oh, but that would leave the treasure door open..

**Comment by Tachiorz** [comment]
I can see a situation that could lead to this. Barri last section is a dodgy place, it have 2-4 puzzles and 2 cases with ores, which means there could be only ores and boss door without a key. Haven't seen this on official server, it does good job placing puzzles, I guess it rerolls section (or entry floor) if it sees that puzzles were placed a way that boss door remained unlocked.
I do not reroll. `collectprop_test.cs` that places ores have `ReserveDoors();` call that guarantees that doors of that place won't be used for anything. **If it's called for last room - boss door would be in open state.**
Proposed solutions:
1. `ReserveDoors()` shouldn't be called in `collectprop_test.cs`. There are plenty of ores in passways. This way, `Dungeon.InitFloorRegion()` will add missing boss door.
2. check and fix boss door state in `Dungeon.InitFloorRegion()`
3. both 1 and 2
4. make an exception for boss door in `ReserveDoors()` leave it closed.
5. ugliest hack possible. Make a list of puzzles that declare locked place and call one of them first for the last section, to guarantee locked boss door.

**Comment by exectails** [comment]
Does that only apply to Barri, or to Alby Int 2 as well?

**Comment by Pegwald** [comment]
In Barri I've also noticed that ores only spawn in rooms and never in the corridors. Does the orespawn have something to do with... perhaps ruining or glitching the other rooms? Overwriting them?
