### ISSUE TITLE
Knuckle Animation delays Final Hit

### ISSUE THREAD

**Issue by xeroplz** [aura-project/aura#147]
When finishing off a monster using knuckles while the Final Hit skill is activated, the game waits for the animation to finish, THEN goes to the next monster you click. This shouldn't happen. The animation should be cut off at any point to be able to move to the next monster, maximizing the speed of your attacks.

**Comment by xeroplz** [comment]
Update: It also appears that it happens using any 1 hand item. 1 Dagger, Staff, etc

**Comment by exectails** [comment]
Really? You can continue instantly if you're not dual wielding?

**Comment by xeroplz** [comment]
It's not instant with normal 1 handed weapons, but with knuckles, yes.
Some things like Cylinders hit faster with final hit than bare hands or normal 1 handed weapons. It's pretty weird.
