### ISSUE TITLE
Premium System

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#15]
Related to #10, features like VIP inventory and Style tab have to be disabled until they're activated, for example, by acquiring premium services.

**Comment by exectails** [comment]
I need a log of buying access to the style tab, if you plan to purchase it, consider logging the process.

I guess it's actually a general purpose buy handler, did anyone see it anywhere else?

```text
Op: 000096D5 ?, Id: 0010000000000002
001 [........00000001] Int    : 1
002 [........FFFFFFFF] Int    : -1
003 [........000165E1] Int    : 91617
004 [................] String : Style Tab (30 days)
005 [0000000000000000] Long   : 0
```

![ss 2016-02-26 at 01 59 54](https://cloud.githubusercontent.com/assets/5593920/13352973/50a1627e-dc91-11e5-8e6e-4d3a2ee0a1e4.jpg)

**Comment by exectails** [comment]
The Merchandise List uses "pawnshop.xml" to look up the prices of the stuff you send. I assume the first int is the number of elements, the third int is the id in pawnshop.

**Comment by boilerplate5** [comment]
Logged the purchasing and availability of the style shop.
[Style Purchased.txt](https://github.com/aura-project/aura/files/331814/Style.Purchased.txt)

**Comment by exectails** [comment]
Oh, now that I'm seeing that screenshot again, the dressing room probably uses the same packets, and that space on the right is for coupons.

**Comment by exectails** [comment]
I've decided to not implement the "merchandise shop" for now, since it's not a feature we need for G1, and the style tab can be enabled via the VIP service, which is currently on by default. The only reason you might want to be able to buy the style tab, is if you want players to pay for the style tab, and no other premium stuff.
