### ISSUE TITLE
Error when running the server.

### ISSUE THREAD

**Issue by Jedzkie** [aura-project/aura#154]
Hi i'm new in aura, I got this error when running the emulator. I apply already the main.sql in MySQL. Thanks!

Im using Windows 7 Professional 32bit

![aura error](https://cloud.githubusercontent.com/assets/4826387/11996043/94d37a04-aa96-11e5-93dd-c0ff988b978d.PNG)

**Comment by exectails** [comment]
Weird error. You just set the options in database.conf and ran the main.sql, right? It's working fine for me, so I assume it's not our files, even though the internet suggests that it's a problem with a foreign key o~o

http://stackoverflow.com/questions/1457305/mysql-creating-tables-with-foreign-keys-giving-errno-150

Could you do what's recommended in the first answer there, to get a more detailed error message?

**Comment by Jedzkie** [comment]
@exectails I fix the log_security thru manual execution of script in mysql, now i have this error in same sql upgrade.

![error 2](https://cloud.githubusercontent.com/assets/4826387/11996372/4242e166-aa9c-11e5-9100-38ddcb8fae33.PNG)

**Comment by exectails** [comment]
You're not supposed to run the updates manually^^" The login server runs them automatically, and keeps track of which it ran in the "updates" table. If you run them yourself, you have to add them to that table manually as well.

**Comment by Jedzkie** [comment]
but still i got errors -_-, still can't play offline.

**Comment by Sairii** [comment]
maybe a screenshot of your mysql sheme would help
please show an overview of the database with the tables that the error is about.
i think exec already wrote the solution

**Comment by Jedzkie** [comment]
@exectails @Sairii nvm guys i already ficed it, thanks to both of you!
