### ISSUE TITLE
Items don't stack when switching with equipped item

### ISSUE THREAD

**Issue by QewQew** [aura-project/aura#159]
steps to reproduce:
1. equip non-full stack of fishing bait.
2. try to switch it with a another stack of fishing bait (full or not full)

what happens:
the stack on your cursor switches place with the equipped stack

expected:
the stack on your cursor should attempt to fill the equipped stack

**Comment by exectails** [comment]
The reason is that InventoryPocketSingle's TryAdd method doesn't handle stackables, it simply swaps them, because I didn't take magazines into account when writing that^^
