### ISSUE TITLE
Lag causes forced disconnection

### ISSUE THREAD

**Issue by QewQew** [aura-project/aura#160]
when performing actions while lagging, you the client may send the same packet twice. this will often lead to some security violation exceptions which will get you kicked off the server. for example, trying to drop an item while the item is in the cursor and clicking multiple times on the floor will send the itemdrop packet twice to the server, which will kick you.

**Comment by exectails** [comment]
And that's why I was against security violations =/

**Comment by QewQew** [comment]
just don't want them in certain places. other than that, what's wrong with them?

**Comment by exectails** [comment]
I should clarify, I was against throwing them automatically everywhere, because we don't know nearly enough about what the client does yet. Like this, where it might send a packet twice. That means every handler that uses GetItemSafe is now potentially a problem.

**Comment by exectails** [comment]
I've changed the code for all obvious item handlers in the fishing branch, that should fix this.
