### ISSUE TITLE
Field Spawns

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#161]
Field spawns.
http://aura-project.org/forum/topic/120-creature-spawners/

- [x] Tir
- [x] Dugald
- [x] Dunbarton
- [x] Gairech
- [x] Tir Na Nog
- [x] Tir Beginner
- [x] Sidhe

Optionally
- [x] Emain
- [x] Sen Mag
- [x] Ceo
- [x] Osna Snail

**Comment by exectails** [comment]
Currently being worked on by me and @Sairii.

**Comment by Sairii** [comment]
I think i have all of them except tir na nog.
My pull request only holds gairech atm because you said my coords are off which I cannot see.
After resolving the issue with gairech I'll look at the others again and make them pull ready.

**Comment by exectails** [comment]
Almost done with the optionals, just gotta add the Sprite AIs.
