### ISSUE TITLE
Making a check can ban you

### ISSUE THREAD

**Issue by Xcelled** [aura-project/aura#162]
Due to the +5% with checks, it's possible for someone to be banned by attempting to take a check out for the maximum in their bank. See https://github.com/aura-project/aura/blob/master/src/ChannelServer/Network/Handlers/NPCs.cs#L443

On NA, you get a message to the effect of "insufficient gold to cover the fee", but on Aura, you'd get a ban.

**Comment by exectails** [comment]
Did you actually test this? The message is client sided, and you get it on Aura as well.

**Comment by Xcelled** [comment]
Oh hm. You're right. I wonder what I did to NOT get it... Anyway, we might want to make it a mild exception? Since it'd be pretty easy to mod that box away.

**Comment by exectails** [comment]
If you actually mod it away you probably deserve the Moderate, if you didn't you don't deserve either =/  Maybe we should just test for it and ignore it if something's wrong, since we don't know how you triggered it.

**Comment by DeleteIT** [comment]
Ban them for trying to create an economic crisis.
