### ISSUE TITLE
Enchant scrolls from treasure rooms the same?

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#164]
I am only getting the same enchant scroll over and over. Prefix "Restful" rank E. Also, am I wrong when I say there are sometimes random treasure rooms showing up in dungeons they are not supposed to?

**Comment by exectails** [comment]
The enchant scrolls that can drop in the treasure rooms are these: Restful (chance: 40%), Foggy (30%), Giant (20%), and Healer (10%). They should drop randomly, so if you've only gotten Restful so far, there are 2 possibilities, 1) there is a bug after all, or 2) you've been lucky/unlucky. How many times has this happened?

What do you mean by "not supposed to"? Our dungeon db is based on the client's dungeon db, which specifies which "puzzles" (rooms) are supposed to appear in which dungeon. If a treasure appears in Aura, there should be a chance for it to appear in NA as well.

**Comment by Pegwald** [comment]
oooh, I see. So far I've gotten it 3-4 times. Must have been bad luck :l

**Comment by exectails** [comment]
I guess I'll close this for now, until a bug is suspected.
