### ISSUE TITLE
AIs

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#170]
While most field monsters should have a working AI now, some monsters are still missing one, especially in dungeons.

- [x] Goblins
- [x] Kobolds
- [x] Succubus
- [x] Trolls
- [x] Imps
- [x] Hellhound
- [x] Boars
- [x] Ogres
- [x] Argus
- [x] Gorgons
- [x] Gremlins
- [x] Lycanthrope
- [x] Werewolves
- [x] Flying Swords
- [x] Cow
- [x] Dire Wolves
- [x] Meek Bat
- [x] Grizzly Bears
- [x] Black Wizard

**Comment by exectails** [comment]
**Imp chat research**

```text
?
---------------------------------------
What are you?
Growl..
What's your business...
Are you human?
Ha ha
Gah!
Here I come!
Please wait.
Set your items.
Do you have this?
Rubbish...
Fool.
Mmph!
Can I really use the Smash skill?
Go get lost.
My mouse got dirty.

Idle
---------------------------------------
Booyah!
Ha ha
Hahaha
Growl..
What?
Why have you come?

Attack
---------------------------------------
Attack!

Defense
---------------------------------------
Do you know how to use the Smash skill?
Do you know how to use magic?
Let's see what you've got!

Counter
---------------------------------------
Do you know how to use the Smash skill?
Do you know how to attack?

Before Lb
---------------------------------------
There is something under the keyboard!
You like that?
Please, I need guidance.
Do you know how to use this?
Hey, wait.
Ran out of cash...

Before Lb x2
---------------------------------------
What is your IP?

Smash
---------------------------------------
Imp Smash!
Here comes a Smash!
Why don't you start over again.

OnHit
---------------------------------------
Umph...

OnKnockDown (countered)
---------------------------------------
Ouch!
Are you a noob?
It hurts.
```

**Comment by Sairii** [comment]
IMP and Wisp AI are both fairly the same.
Both official AIs use magic charges BUT NEVER ACTUALLY fire them.
I guess this is pretty much the same as ranged attack?
Anyways its missing...

**Comment by exectails** [comment]
I think they load but don't fire them to confuse the enemy.

**Comment by Sairii** [comment]
Good thing there are only like 5 Goblin AI's left ^^"

**Comment by exectails** [comment]
xD"

**Comment by Sairii** [comment]
And I thought it was called Meek Bat...
*cough*

**Comment by exectails** [comment]
I totally don't know what you're talking about.

**Comment by Sairii** [comment]
*cough*
Isn't Black Wizard missing?
*cough*

**Comment by exectails** [comment]
That's a good question, we should probably find out.

**Comment by exectails** [comment]
Black Wizard + Wisps is a G0S0 group, so it's safe to assume that they're G1.

**Comment by Sairii** [comment]
Troll AI probably needs a little overhaul.
It cancels the attack animation because of no wait after the do(attack());

**Comment by exectails** [comment]
>Troll AI probably needs a little overhaul.
It cancels the attack animation because of no wait after the do(attack());

Maybe we need a little delay after Attack internally, wouldn't want to put a Wait after each one, in every script.
