### ISSUE TITLE
Humans can equip shields with two-handers

### ISSUE THREAD

**Issue by Xcelled** [aura-project/aura#171]
What it says on the tin.

Noticed it with a Tethra and Shield of Avon.

**Comment by Crypting** [comment]
You mean humans and dual wield shields.. like wear two shields? o.o

**Comment by Xcelled** [comment]
![](http://puu.sh/iwO7X/09ad15e587.png)

**Comment by Crypting** [comment]
Oh, yeah that makes sense.. xD

**Comment by Xcelled** [comment]
This still needs work. Shields don't behave correctly with 1 handers either. The shield should not unequip when equipping or unequipping a 1hander:

![](http://i.imgur.com/oltTNL6.gif)

**Comment by exectails** [comment]
I hate the inventory.
