### ISSUE TITLE
G1 Mainstream

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#172]
Split off from #5, as this will be a large topic in itself.

References: http://wiki.mabinogiworld.com/index.php?title=Generation_1:_Advent_of_the_Goddess&oldid=61442

**Quests**
- [x] Finding the Lost Earring
- [x] The Three Missing Warriors
- [x] RP Quest - The Third Warrior
- [x] The Story of Goddess Turned into a Stone
- [x] The Land of Eternity, Tir Na Nog
- [x] Brown Fomor Pass
- [x] Medal of Priests
- [x] Goro's Ring
- [x] RP Quest - Succubus
- [x] Book of Evil Part 1
- [x] Book of Evil Part 2
- [x] The Book of Revenge
- [x] RP Quest - Mores
- [x] Wizard's Note
- [x] The Book of Revenge, Volume II
- [x] Investigation of the third volume of the Book of Revenge
- [x] Investigation of the third volume of Book of the Revenge
- [x] Book of the Revenge, Volume III
- [x] Embodiment of Destruction, Glass Ghaibhleann
- [x] Magic Powder of Preservation
- [x] RP Quest - Rabbie Dungeon
- [x] The Pendant from Goddess
- [x] RP Quest - Shiela's Memory
- [x] Kristell's Request
- [x] The Seal Breaker of Another World
- [x] Bind Magic
- [x] Collecting Pieces of Black Orb
- [x] Black Orb Dungeon
- [x] Glas Ghaibhleann

**Comment by exectails** [comment]
Reminder. Implement these titles #281:
- the Seal-Breaker of Another World
- who Saved the Goddess

**Comment by RageNTonic** [comment]
something to note: during a later part of G1 their is an RP dungeon where a character knows fireball i noticed it wasn't implemented. im sure the dungeon would still run fine though just seeing the skill sit there unusable can be a bit bothersome

**Comment by exectails** [comment]
Ohhh, you're right, I totally forgot about that o,o Thanks for the reminder.

**Comment by Pegwald** [comment]
You're talking about Mores, right? After from what I can remember, Mores doesn't have fireball in the first version of G1. After the Genesis update he does.

_"Mores is an incredibly powerful Druid who has rank 1 of Icebolt, Firebolt & Lightning Bolt. In addition, he has the ability to Chain Cast bolts."_

source: http://wiki.mabinogiworld.com/view/Generation_1:_Advent_of_the_Goddess_(Pre-Genesis)

**Comment by exectails** [comment]
Yea, @Pegwald is right, that explains why I didn't remember it =P

http://wiki.mabinogiworld.com/index.php?title=Mores&oldid=141553

**Comment by RageNTonic** [comment]
oh yeah that's my bad i remember that dungeon more from my later play throughs and i guess i just assumed it had always been that way

**Comment by Pegwald** [comment]
O.O
