### ISSUE TITLE
Treasure Key gets dropped during cutscene in beginnner dungeon

### ISSUE THREAD

**Issue by epicmiro** [aura-project/aura#172]
When you finish trefor's beginner dungeon (the one with the npc), You will enter a cutscene and be transported to the treasure room at the ending of the dungeon, however, your key will be dropped at the place where you defeated the boss, and you have to walk back to retrieve it.

Repo steps: (100% 1/1)
1. Log in
2. Make new character (or get the beginner pass)
3. defeat boss
4. go trough cutscenes

Result: key is dropped at previous location before the cutscene's triggered
Expected result: key is still in inventory to open chest.

**Comment by exectails** [comment]
Fixed in 51e3dba0fdc0294ef8ceda9fc9347aca3dc7f4e3.
