### ISSUE TITLE
Going deadly in defense won't knock back

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#177]
It's all pretty much here. While taking damage in defense and going into a critically deadly state,  you will not get knocked back.

https://www.youtube.com/watch?v=z_exXZfQBGU

**Comment by Sairii** [comment]
Is that a bug?
I dont know... i rarely use defense and I rarely go into deadly.

**Comment by Pegwald** [comment]
I believe it is, even if you use defense or not, the character is supposed to be knocked back when entering a deadly status. I might be wrong, however, because it's a long time since I played the official mabi ^^ ''

**Comment by Pegwald** [comment]
I suddenly get the feeling I am very wrong about this... I have to check this out now.

**Comment by FlandreScarlet-xx** [comment]
im pretty sure getting put into deadly should always knock you back

**Comment by Pegwald** [comment]
That's what I also believe, but I haven't confirmed it yet. :/

**Comment by Pegwald** [comment]
Ok, so I managed to get knocked back by a single lightning bolt while using defense. That pretty much covers it, right?

**Comment by exectails** [comment]
Yea, that sounds about right. But then the question is, do you take full damage, because the attack broke your Defense, or is it still the lowered amount? Or maybe something in between? Because you couldn't fully defend?

**Comment by Pegwald** [comment]
Hmm... I actually don't know. It would make sense both ways actually, but would it even matter? Unless negative amount of health matters, I would say it wouldn't be a big deal. Blocked or not blocked, you're still in a deadly state :p

**Comment by Pegwald** [comment]
"When active, it boosts the Defense and Protection of the user, and allows the user to block one enemy attack." - Wiki.
We can agree on when entering a deadly state, you lose the ability to block the attack, right?
I would say you still get the passive of the ability that adds defense and protection to the user, no matter if you successfully block the attack or not. That's how I understand it at least.
