### ISSUE TITLE
Error appeared in MsgrServer every time login and unable to use the friend list(blank) 

### ISSUE THREAD

**Issue by garryrry** [aura-project/aura#179]
This appear every time i login to the server and unable to use the friend list. Sorry for the Chinese and it just said "Unable to find the access point."

>29/12/2015 21:35:03 [Warning] - Using the default inter server password is risky, please change it in 'inter.conf'.
29/12/2015 21:35:03 [Info] - Initializing database...
29/12/2015 21:35:03 [Status] - Server ready, listening on 0.0.0.0:8002.
29/12/2015 21:35:03 [Info] - Type 'help' for a list of console commands.
29/12/2015 21:37:45 [Info] - Connection established from '192.168.1.138:7503.
29/12/2015 21:37:46 [Error] - While receiving data from '192.168.1.138:7503'.
29/12/2015 21:37:46 [Exception] - System.EntryPointNotFoundException: 找不到進入點。
   於 MySql.Data.MySqlClient.IDriver.get_ServerStatus()
   於 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   於 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   於 Aura.Msgr.Database.MsgrDb.GetOrCreateContact(String accountId, Int64 characterEntityId, String characterName, String server, String channelName) 於 c:\Auraserver\aura\src\MsgrServer\Database\MsgrDb.cs: 行 41
   於 Aura.Msgr.Network.MsgrServerHandlers.Login(MsgrClient client, Packet packet) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrHandlers.cs: 行 94
   於 Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) 於 c:\Auraserver\aura\src\Shared\Network\PacketHandlerManager.cs: 行 72
   於 Aura.Msgr.Network.MsgrServerHandlers.Handle(MsgrClient client, Packet packet) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrHandlers.cs: 行 37
   於 Aura.Msgr.Network.MsgrServerServer.HandleBuffer(MsgrClient client, Byte[] buffer) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrServerServer.cs: 行 67
   於 Aura.Shared.Network.BaseServer`1.OnReceive(IAsyncResult result) 於 c:\Auraserver\aura\src\Shared\Network\BaseServer.cs: 行 190
29/12/2015 21:38:44 [Info] - Connection established from '192.168.1.138:7518.
29/12/2015 21:38:44 [Error] - While receiving data from '192.168.1.138:7518'.
29/12/2015 21:38:44 [Exception] - System.EntryPointNotFoundException: 找不到進入點。
   於 MySql.Data.MySqlClient.IDriver.get_ServerStatus()
   於 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   於 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   於 Aura.Msgr.Database.MsgrDb.GetOrCreateContact(String accountId, Int64 characterEntityId, String characterName, String server, String channelName) 於 c:\Auraserver\aura\src\MsgrServer\Database\MsgrDb.cs: 行 41
   於 Aura.Msgr.Network.MsgrServerHandlers.Login(MsgrClient client, Packet packet) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrHandlers.cs: 行 94
   於 Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) 於 c:\Auraserver\aura\src\Shared\Network\PacketHandlerManager.cs: 行 72
   於 Aura.Msgr.Network.MsgrServerHandlers.Handle(MsgrClient client, Packet packet) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrHandlers.cs: 行 37
   於 Aura.Msgr.Network.MsgrServerServer.HandleBuffer(MsgrClient client, Byte[] buffer) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrServerServer.cs: 行 67
   於 Aura.Shared.Network.BaseServer`1.OnReceive(IAsyncResult result) 於 c:\Auraserver\aura\src\Shared\Network\BaseServer.cs: 行 190
29/12/2015 21:39:44 [Info] - Connection established from '192.168.1.138:7533.
29/12/2015 21:39:44 [Error] - While receiving data from '192.168.1.138:7533'.
29/12/2015 21:39:44 [Exception] - System.EntryPointNotFoundException: 找不到進入點。
   於 MySql.Data.MySqlClient.IDriver.get_ServerStatus()
   於 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   於 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   於 Aura.Msgr.Database.MsgrDb.GetOrCreateContact(String accountId, Int64 characterEntityId, String characterName, String server, String channelName) 於 c:\Auraserver\aura\src\MsgrServer\Database\MsgrDb.cs: 行 41
   於 Aura.Msgr.Network.MsgrServerHandlers.Login(MsgrClient client, Packet packet) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrHandlers.cs: 行 94
   於 Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) 於 c:\Auraserver\aura\src\Shared\Network\PacketHandlerManager.cs: 行 72
   於 Aura.Msgr.Network.MsgrServerHandlers.Handle(MsgrClient client, Packet packet) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrHandlers.cs: 行 37
   於 Aura.Msgr.Network.MsgrServerServer.HandleBuffer(MsgrClient client, Byte[] buffer) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrServerServer.cs: 行 67
   於 Aura.Shared.Network.BaseServer`1.OnReceive(IAsyncResult result) 於 c:\Auraserver\aura\src\Shared\Network\BaseServer.cs: 行 190
29/12/2015 21:40:44 [Info] - Connection established from '192.168.1.138:7537.
29/12/2015 21:40:44 [Error] - While receiving data from '192.168.1.138:7537'.
29/12/2015 21:40:44 [Exception] - System.EntryPointNotFoundException: 找不到進入點。
   於 MySql.Data.MySqlClient.IDriver.get_ServerStatus()
   於 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   於 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   於 Aura.Msgr.Database.MsgrDb.GetOrCreateContact(String accountId, Int64 characterEntityId, String characterName, String server, String channelName) 於 c:\Auraserver\aura\src\MsgrServer\Database\MsgrDb.cs: 行 41
   於 Aura.Msgr.Network.MsgrServerHandlers.Login(MsgrClient client, Packet packet) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrHandlers.cs: 行 94
   於 Aura.Shared.Network.PacketHandlerManager`1.Handle(TClient client, Packet packet) 於 c:\Auraserver\aura\src\Shared\Network\PacketHandlerManager.cs: 行 72
   於 Aura.Msgr.Network.MsgrServerHandlers.Handle(MsgrClient client, Packet packet) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrHandlers.cs: 行 37
   於 Aura.Msgr.Network.MsgrServerServer.HandleBuffer(MsgrClient client, Byte[] buffer) 於 c:\Auraserver\aura\src\MsgrServer\Network\MsgrServerServer.cs: 行 67
   於 Aura.Shared.Network.BaseServer`1.OnReceive(IAsyncResult result) 於 c:\Auraserver\aura\src\Shared\Network\BaseServer.cs: 行 190

**Comment by exectails** [comment]
Someone reported this recently on the chat, when trying to run Aura on a Surface =/ Apparently it's some problem with the MySQL DLL, but it seems to affect only very, *very* few people. I guess we should get to the bottom of this.

What operating system are you using?

**Comment by garryrry** [comment]
Window 10 and i am using Aura Frontend by Xcelled to start the server

**Comment by exectails** [comment]
After doing another search, apparently it's possible for another MySQL dll to take priority over our dll in Aura's directory under certain conditions. I've updated our dll, which should give it priority again in theory.

Please try to update Aura and see if this fixed the issue.

**Comment by garryrry** [comment]
It fixed. No error appeared and the friend list work normally again. Thanks
