### ISSUE TITLE
Client Side Character Creation Limit

### ISSUE THREAD

**Issue by ImaBrokeDude** [aura-project/aura#179]
One of my users currently only has two characters. When attempting to create a third character they get the following message:

Notice:
Character creation failed.
* You can only create 20 characters per race.

http://puu.sh/iGQP3/0caad37296.jpg

**Comment by xKamuna** [comment]
Did you check the login server for an error?
Usually that means you gave them a card that's not in the database, but it could also mean:
Your server is missing.
Invalid face or hair.
Race not allowed.
Unable to find age info for race.
Invalid name.
Failed for unknown reasons.

**Comment by ImaBrokeDude** [comment]
-_- I didnt notice them before. Thanks, Missing card (21) or race not allowed (9001).

**Comment by xKamuna** [comment]
Give them a Free Card.  It's card number 147.
9001 is a female elf, for future reference.

**Comment by ImaBrokeDude** [comment]
Thanks, I will go back through Aura (which I should have done) to prevent more things like this. Thanks.
