### ISSUE TITLE
"stackmagic_attack" skill_id="30101" charge="1"

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#182]
The official stackmagic_attack works like the one in their Pet AIs.

If you have charges:
- Attack right away without charging new

Without charges:
- Charge 1 time and immediatly attack

**Comment by exectails** [comment]
Basically it works just like `Attack` and `RangedAttack`, but with the ability to specify the skill to load, unlike the other two, which will default to Combat Mastery and Ranged Attack respectively.

I guess this would be a nice enhancement, even if we could live without it.

**Comment by Sairii** [comment]
ye and I'll have to redo wisp, imp and succubus AI once this is a thing

**Comment by exectails** [comment]
I've added a stack parameter to `PrepareSkill`, so you can load multiple stacks, and I've added `StackAttack`, which does what is described here. Both of these have been tested briefly, but if you notice anything post here.

If you call `PrepareSkill` repeatedly now, it will add one stack every time. If you call it with stack parameter, it will add that amount of stacks. The stack count is basically the amount of times PrepareSkill should run.

```
PrepareSkill(SkillId.Icebolt); // First stack
PrepareSkill(SkillId.Icebolt); // Second stack
PrepareSkill(SkillId.Icebolt, 2); // Third and Fourth stack

PrepareSkill(SkillId.Icebolt, 5); // Charge all 5 stacks
```

`StackAttack` will charge the skill until the given amount of stacks is reached, and then attack until the stacks are 0 or the timeout is reached.

```
StackAttack(SkillId.Lightningbolt); // Charge once or attack if it's loaded already

StackAttack(SkillId.Lightningbolt, 3); // Charge until there are 3 stacks and attack
```
