### ISSUE TITLE
Spawns inside props

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#188]
Related to #176 and #149.

Just like creatures aren't supposed to walk into props, they aren't supposed to spawn in them either. Right now it's possible for monsters to spawn inside props, which makes them stuck there, because they can't walk out of them, which the clients lets players do. (Does the NPC client allow this as well?)

Similarly, a player could warp into a prop, which would make them stuck, _if_ we activated player collision detection, without checking if they're inside a prop, because they wouldn't be able to cross the collision lines.

I can think of three solutions to this particular problem.
1. Check if the planned spawn position is inside a prop, and keep looking for another one if it is. Not elegant, but simple.
2. Make sure the spawn areas don't include props. A _lot_ of work, as we would have to place all spawn areas manually, and basically without official references. It could also mess with the monster distribution.
3. Let them walk out of props. This would still let them _spawn_ in props, and if a monster did get into a prop somehow, it might leave into a direction it isn't supposed to go, say, the other side of a door in a dungeon.

Option 1 seems like the best to me, but it would require changes to our collision manager. There are potentially a _lot_ of props in one region to check. Every house, every tree, every shrub, every pole. Iterating over all of them would take a while, on every respawn. We would want to utilize the quadtree for this.

**Comment by DeleteIT** [comment]
>(Does the NPC client allow this as well?)

No.
I've seen enough wolves stuck in places they shouldn't even be to firmly, and categorically state this.

**Comment by RageNTonic** [comment]
pets also can get summoned inside walls

**Comment by exectails** [comment]
Oh, right. Thanks for the reminder.

**Comment by Pegwald** [comment]
It recently happened again that I had to enter someone else's dungeon to get rid of a skeleton that spawned inside a wall. A fix sooner or later would be very nice ouo''

**Comment by exectails** [comment]
Dungeons are actually a different topic, and it shouldn't be possible for monsters to *spawn* inside props there o.o Though it shouldn't be possible for them to walk into them anymore either... I guess I'm wrong about one of those two o~o It is different though, because in dungeons there are no random props that you could accidentally hit, the rooms and alleys are defined very clearly, and you know where the free space is.

**Comment by exectails** [comment]
@Pegwald Is there a particular dungeon where this keeps happening? I haven't been able to make out a problem with either the spawning or the collision detection in dungeons yet.

Spawning area: http://puu.sh/slVQh/54fb40511b.jpg
After some free roaming: http://puu.sh/slVQS/794636bd82.jpg

**Comment by exectails** [comment]
Damn it... they are able to walk through some walls in some dungeons. In Rabbie it seems to be relatively easy to find "holes". I'm so tired of this collision crap, every time I think we finally got it, there's another problem. So... tired...

**Comment by exectails** [comment]
I think I know where the problem lies, but I have no idea how to fix it. As you can see in the following image, there are "collision boxes" that overlap. It seems to me like the monsters are able to pass through some of those lines, like the marked ones. Somehow our intersection function seems to be failing there, but I don't understand *how*.

![unbenannt](https://cloud.githubusercontent.com/assets/5593920/20417915/2196fe92-ad49-11e6-8d06-3862547cb62e.PNG)

**Comment by exectails** [comment]
I managed to fix it, thanks for the report guys. Please update and try it, to confirm that monsters won't walk through walls anymore now.

**Comment by exectails** [comment]
>Option 1 seems like the best to me, but it would require changes to our collision manager. There are potentially a lot of props in one region to check. Every house, every tree, every shrub, every pole. Iterating over all of them would take a while, on every respawn. We would want to utilize the quadtree for this.

Today I worked on changing the quadtree, but I encountered some issues with the collisions after my changes, which once again, seem completely random... collisions are so terribly hard to debug ~_~

However, I actually gave iterating over all props a chance, just to see how the performance would be, and to my surprise I didn't notice any delay. It does take 1ms+ to iterate over all props in a full region, but it seems like a viable hot-fix.
