### ISSUE TITLE
Final Hit does Knock Down

### ISSUE THREAD

**Issue by ImaBrokeDude** [aura-project/aura#191]
When I use Final hit I know it is not supposed to do knockdown, however it does for me:

http://www.imabrokedude.com/fh.gif

**Comment by QewQew** [comment]
http://imgur.com/QeCWp9r

Jfc, a gif? Really?

**Comment by ImaBrokeDude** [comment]
Reading helps... sorry. XD

**Comment by Sairii** [comment]
Uhm you should keep this open tho...
You are not supposed to be able to attack it until it gets up right?
Well I can keep golem in the air....

**Comment by QewQew** [comment]
Does that match the title of the issue?

**Comment by Sairii** [comment]
IT DOES kinda
...
the knockdown is.... kinda buggy?
