### ISSUE TITLE
Monster Ranged Attack feels too weak.

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#195]
Uhm something is wrong with the monsters ranged attack damage.
I already noticed it while doing goblin archers.
The damage is not official, it is really low.
10-60 damage is a kobold archer supposed to do. But it crits for 23 and most of the time hits for only 9. It is really really puny dmg.

**Comment by exectails** [comment]
Let's see, right now we basically take the weapon's min and max attack stats, add the Dex bonus, and that's it. Kobold Archers use Composite Bows, which have 10~17 attack, add the stat bonus from their 10 Dex, which is 0, and the attack stays the same =< I'll admit, that does seem low, especially as their base attack is 12~33.

Now, if you added those two, the base attack affecting the ranged damage, you would get 24~50 without any modifications like Balance, Defense, or Crits, which seems much more in line with what the Wiki says.

One quick check... yup, that's it. If I increase my base attack, the client uses that value in the damage calculation when I equip a bow.
