### ISSUE TITLE
Parties

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#2]
Basic functionality:
* Creating parties
* Sharing exp
* Entering dungeons together

Currently being worked on at https://github.com/Whimsytech/aura/pull/3.

**Comment by DeleteIT** [comment]
All of that functionality is in place, the only things missing at this moment (that I can think of, at least?) are:

+ Girgashiy Raid parties
+ Finish rule application
+ Production bonuses
+ Party Board system

**Comment by exectails** [comment]
The party board system can be ignored for now in my opinion, since it's a G3 feature, same goes for Raid parties, we don't really need those yet, they just add unnecessary complexity.

**Comment by DeleteIT** [comment]
Oh, I'd actually already started party boards. I'll remove that for now then.
