### ISSUE TITLE
WM training bug (R7)

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#201]
Looks like I can't really attack several powerful enemies at once, but I am still able to defeat several powerful enemies at once. 
![wm](https://cloud.githubusercontent.com/assets/13089450/12236175/8f7d99fa-b878-11e5-8db1-162785cf1201.PNG)

**Comment by exectails** [comment]
Hum. Attacking actually works as expected, if you attack 4+ enemies in a strong group (meaning the strongest monster is strong, and the others whatever), you will get the attack several powerful training. What's bugged is the defeat training, as that one isn't limited to 4, but only counts whether it was a strong group and all targets were defeated, no matter how many there were.

**Comment by Pegwald** [comment]
That might be it. I just checked out the skill info after clearing a few rooms or something :>

**Comment by exectails** [comment]
I hope this is now finally official-like^^
