### ISSUE TITLE
Pet Locked if Desummoned While Using Rest.

### ISSUE THREAD

**Issue by ImaBrokeDude** [aura-project/aura#207]
If a pet is using rest when it is "Return!"ed, it will be stuck in rest when summoned again, and unable to come out of Rest, or attack or what have you, until the player logs in as the pet and manually takes it out of Rest

**Comment by exectails** [comment]
I can't reproduce this. I'm summoning a pet which I gave Rest, I make it lie down, and I unsummon it. When I summon it again everything works as expected.

**Comment by ImaBrokeDude** [comment]
Confirmed as it seemed to be a temporary issue resolved with a server restart. Closing Issue.
