### ISSUE TITLE
Ciar dungeon access

### ISSUE THREAD

**Issue by ImaBrokeDude** [aura-project/aura#211]
Can't seem to get into ciar dungeon after update D:

http://puu.sh/mwVG0/7570759a14.png

**Comment by ImaBrokeDude** [comment]
Seems to be caused by oriental_town.cs

**Comment by exectails** [comment]
>Seems to be caused by oriental_town.cs

What makes you think that some random custom script could in *any* way be related to you not being able to reach Ciar.......?

**Comment by QewQew** [comment]
Was the script even enabled?

**Comment by ImaBrokeDude** [comment]
The script I mentioned? Yes. Seemed to take me to ciar dungeon's portal but I think that was another kind of thing where a server restart fixed that.
