### ISSUE TITLE
Bandages

### ISSUE THREAD

**Issue by RashataanVuul** [aura-project/aura#212]
I know this isn't a bug but I just wanted to ask if you plan to fix the handmade bandages? They're suppose to mend better than normal bandages but right now, they seems to act the same as regular bandages

**Comment by DeleteIT** [comment]
Is this still an issue?
https://github.com/aura-project/aura/blob/master/src/ChannelServer/Skills/Life/FirstAid.cs#L33

**Comment by DeleteIT** [comment]
Sigh.

http://wiki.mabinogiworld.com/view/Handmade_Bandage
http://wiki.mabinogiworld.com/view/Fine_Handmade_Bandage
http://wiki.mabinogiworld.com/view/Finest_Handmade_Bandage

Does anyone happen to know what the actual healing values/properties are?

**Comment by QewQew** [comment]
It's in the item xml.

**Comment by DeleteIT** [comment]
I *literally* just noticed that xD

**Comment by exectails** [comment]
@RashataanVuul I would actually consider this a bug, as First Aid was added, the Bandages are used, but they don't do what they're supposed to do. Thanks for reporting it^^
