### ISSUE TITLE
Zombie damage

### ISSUE THREAD

**Issue by RashataanVuul** [aura-project/aura#213]
A 5 charge lightning bolt is VERY affective against zombies.

Just depending how much int you have for the damage output.
anyway, you can actually damage and kill zombies with lightning bolts

**Comment by QewQew** [comment]
Because Mana Deflector isn't implemented yet.

**Comment by exectails** [comment]
@QewQew https://github.com/aura-project/aura/blob/master/src/ChannelServer/Skills/Combat/ManaDeflector.cs

**Comment by RashataanVuul** [comment]
I was about to say "I'm pretty sure it is since I've been using it."

**Comment by exectails** [comment]
Hm... Zombies do have r1 Mana Deflector, and Ice Bolt correctly does only 1 damage, why is Lightning Bolt doing so much damage o.o

**Comment by QewQew** [comment]
Oh. Haven't been keeping up. Works for mobs, too?

**Comment by exectails** [comment]
@QewQew Yes^^

**Comment by exectails** [comment]
Though, as I'm IB spamming a Zombie, I guess it's not correct yet. I can knock back the Zombie, but it doesn't have a KB animation. I assume it's not supposed to be possible to knock it back. (Down, but not back.)
