### ISSUE TITLE
Unable to mend players

### ISSUE THREAD

**Issue by RashataanVuul** [aura-project/aura#216]
Mending yourself works fine but mending other players don't work. I've tested this with...

* Rank F -First Aid- (Haven't tested other ranks)
* Bandages
* Fine handmade bandages
* Finest handmade bandages

**Comment by exectails** [comment]
Whoops. That's what I get for rarely testing with multiple characters, but running multiple clients is so bothersome =|

First Aid actually did work, but the target's client side HP bar weren't updated.
