### ISSUE TITLE
Gm Commands

### ISSUE THREAD

**Issue by Joroko** [aura-project/aura#217]
I cannot for the life of me figure this out. How is it do you enter commands? >command? >>command? .command? /Command? //command? ive tryed all of these and nothing works! all i get is a " target not found when i type something with ">> command". Also what commands are there?

**Comment by exectails** [comment]
The "command.conf" file, where you can configure who can use which commands, lists all commands and a short description of what they do.

Normal commands use `>` as prefix, while `>>` is the prefix for "character" commands. Basically, you can use almost any command on someone else, by using `>>`, and the target's name as first parameter. For example, `>item apple` spawns an apple for you, while `>>item Someone apple` spawns an apple for "Someone".

This is also described in the file I mentioned above, and on our Wiki: https://github.com/aura-project/aura/wiki/GM-Commands

**Comment by Joroko** [comment]
Thank you for the quick response!! The command.conf file is confusing and none of the commands i tryed work, let alone that none of them have a ">" so i dont know whats what. Do i need to put the auth numbers every i make a command? I was able to spawn an apple like your example. But how do i do things like level up, or tele myself around?

**Comment by exectails** [comment]
By using the respective command o.o There is no level up command, but for warping you can use "warp", "go", and "jump".

```
// Warps to pre-defined locations
go : 1,50

// Warps to a specific region and position
warp : 50,50

// Warps to a specific position in the current region
jump : 50,50
```

You use them just like the item example I gave. What the file means is described in the header:

```
// The commands are using this format
//
//     <command> : <required_authority>,<required_authority>
```

**Comment by Joroko** [comment]
Thanks again, this clear a lot up for me.

**Comment by exectails** [comment]
Since this seems to be resolved, I'll close the issue.
