### ISSUE TITLE
Wisps have friendly fire enabled

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#218]
I think the case might be lightning bolt, but it just looks funny that a wisp can charge 2 lightning bolts and hit me + another wisp. I saved a little sequence if this will be needed.

**Comment by exectails** [comment]
Yea, it is Lightningbolt. Hm, does the "splash damage" go through walls? Thunder's does iirc, but does LB's as well?

**Comment by Pegwald** [comment]
I actually don't know... I think it can reach from around a cone, but wall? I have no idea.

**Comment by QewQew** [comment]
Not a cone. A circle.

**Comment by Pegwald** [comment]
I was talking about the actual prop, not an AoE

**Comment by QewQew** [comment]
A cone prop?

**Comment by Pegwald** [comment]
you know a cone, those there are normally 4 of in some dungeon rooms ^^

**Comment by exectails** [comment]
I think those are commonly referred to as "switches"^^

**Comment by Pegwald** [comment]
my bad ^^''
