### ISSUE TITLE
Trefor is a douche - Support shot

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#219]
I got excited when I heard support shot was added, but whenever I equip either short bow or cross bow, all he does telling me to go see Ranald. Even though I have ranged attack above Novice, he keeps giving me the same dialogue. I also tried this with my GM, but then I got the "Ranged Attack" keyword. Does this mean we have an overlap? Like, he only wants to give me ranged attack and not support shot?

**Comment by exectails** [comment]
The script explicitly checks if you have Ranged Attack *at all*, if not, it tells you to visit Ranald, otherwise it checks for Support Shot, which you can get then, if you don't have it already.

```
if (!HasSkill(SkillId.RangedAttack))
{
	// send to ranald
}
else if (!HasSkill(SkillId.SupportShot))
{
	// teach suport shot
}
else
{
	// ...
}
```

I feel a bit silly asking this, but are you certain that you had Ranged Attack? It's just, I don't see any error in the script, and I can't reproduce it.

**Comment by Pegwald** [comment]
I actaully have ranked attack r1 ^^

**Comment by Pegwald** [comment]
On the GM this was a different case since I used the command to get ranged attack, that's how I managed to obtain the keyword after.

**Comment by Pegwald** [comment]
I looked up in src/ChannelServer/ChannelServer.csproj and it looks like it didn't sync, because there's no support shot there o-o''

I have restarted aura and stuff, but I simply didn't get the update? What?

**Comment by exectails** [comment]
That shouldn't matter in terms of getting the skill, as long as the script updated. But I can't really help you with the updating, as I have no idea how Frontend works =| I assume redownlading would work, if Git messed up the upgrade somehow.

**Comment by exectails** [comment]
>On the GM this was a different case

Well, to the script it doesn't make a different *how* you got the skill, as long as you have it.

**Comment by Pegwald** [comment]
Yeah, I suppose I'll try that next. It must be the only way

**Comment by Pegwald** [comment]
Even though I hate troubleshooting like this, it always seems to work.

**Comment by exectails** [comment]
Weird. I wonder where the conflicts were o.o Too bad Frontend didn't tell us, @Xcelled =P
