### ISSUE TITLE
Novice support shot

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#222]
According to wiki:
Talk to Trefor with the Skills Keyword with at least Rank Novice Ranged Attack.
The skill is immediately set to Rank F upon learning the skill.

I only got it to Novice rank and now I'm stuck.

**Comment by exectails** [comment]
Meh. Are you okay with fixing it with commands, or should I build in a fix?

**Comment by Pegwald** [comment]
I got novice rank on my non-GM, so a fix would be great ^^

**Comment by Pegwald** [comment]
Yay gj ^^
