### ISSUE TITLE
/prop 0 and client crashes

### ISSUE THREAD

**Issue by tkiapril** [aura-project/aura#223]
After I issue the command `/prop 0`, the client immediately crashes. Afterwards, I cannot login to the same map I issued the command; I have to rebirth to somewhere where I did not issue the command. Moving to the map that I issued the command crashes the client once again.

**Comment by QewQew** [comment]
Don't create props the client can't handle.

**Comment by tkiapril** [comment]
@QewQew well, I thought the abillity to create some prop that client cannot handle is a bug.

**Comment by QewQew** [comment]
It's preventable, but not really the fault of the server for the crashing.

**Comment by ImaBrokeDude** [comment]
Remedy (Not Best) Restart Channel Server

**Comment by tkiapril** [comment]
@QewQew hmm... I understand, but would the official accept the fact that GM's could spawn props that would kill clients? eg. some GM could make a typo and accidentally create prop 0 not 10.

**Comment by exectails** [comment]
The server should definitely *not* let the player create props it doesn't even have in its database. Back when I wrote that command we simply didn't have a prop db yet xD"
