### ISSUE TITLE
Campfire position

### ISSUE THREAD

**Issue by garryrry** [aura-project/aura#227]
Seems like there is no distance checks between campfire and maybe props check? As i can do the followings:
![Alt Text](http://i.imgur.com/EOna0Fp.jpg)
![Alt Text](http://i.imgur.com/fIPMykd.jpg)

**Comment by exectails** [comment]
Oh, right... Hm, do we know the official rules? Right off the bat I can think of 3:
- Campfire can't enclose creatures (first image).
- The campfire's shape can't intersect with other props.
- You can't built "through" a collision line (second image).

However, in my memory the rules were much more strict, and you couldn't even be *near* ***anything***. This could turn out to be quite complicated.

For the first point we need to check the shape against nearby creatures. The second point might be solvable by checking the distance to all nearby props, which could result in the mentioned strict rules, but that doesn't work in dungeons, as the *rooms* are *props*... At least the last point would be straight forward though.

**Comment by Cosrnos** [comment]
I also remember certain roads were a factor. I spent way too much time trying to start a fire near ferghus's house
