### ISSUE TITLE
Grabbing Items from a distance

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#229]
This happend to me in a dungeon. I dont know if this is also possible outside of a dungeon.

How to reproduce:

1. item in a room
2. player hides behind or prop (i did it behind a opened door)
3. click on the item
4. item gets picked up while the player is still at the door frame

**Comment by exectails** [comment]
What's a toom? And why weren't you supposed to be able to pick it up?

**Comment by Sairii** [comment]
*room

i dont think you should be able to grab an item thats on the other end of a dungeon room.

**Comment by DeleteIT** [comment]
You should be told that the item is too far away after your character tries to move to it, and the range of picking up is probably a little more than melee attack ranges.

Also, there's a message for items not existing, when you try to pick up an item that is only visible client side (and isn't actually there).

**Comment by exectails** [comment]
We are checking the distance to gathering places, it's currently set to allow for a max distance of 400.
