### ISSUE TITLE
RP dungeons

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#24]
Roll-playing dungeons, where you control a dummy character instead of your own.

This will likely require some changes in the way characters are handled, since no research has gone into this so far.

**Comment by exectails** [comment]
This might be a little more annoying than initially thought, officials seem to initiate a reconnect to the channel to switch to the RP character in the next region oO Sending only what I would've deemed the "switch control" packets locks the character in place, but that's it.

**Comment by DeleteIT** [comment]
Currently in pull request #364 , by @DennouNeko

**Comment by exectails** [comment]
Now available on master for testing, in the the first G1 RP dungeon.

**Comment by junesalee** [comment]
The RP dungeon now does not give the keyword as the reward.

**Comment by exectails** [comment]
Closing, since they're all enabled now.
