### ISSUE TITLE
One-string intros

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#241]
All intros of all NPCs should be turned into only one string, for easier localization. Not only requires it less `L` calls, I imagine it would be kind of irritating, encountering half sentences in the generated localization files.

Right now `Intro` takes a variable amount of string parameters, that make up the lines, that are concatenated behind the scenes. Instead, we want one string, with the lines being separated with `<br/>`s.

**Example**
Dilys' intro would be changed from this

```
await Intro(
    "A tall, slim lady tinkers with various ointments, herbs, and bandages.",
    "She looks wise beyond her years, but it might just be the healer's dress",
    "and neatly combed hair."
);
```

to this

```
await Intro("A tall, slim lady tinkers with various ointments, herbs, and bandages.<br/>She looks wise beyond her years, but it might just be the healer's dress<br/>and neatly combed hair.");
```

**Comment by xCryptic** [comment]
Is this something that you want done now? I've got one more Tir NPC to do and then I can go back and change all the rest of the NPCs if you want.

I was already planning to go through all the NPCs and do the following
• check for base in class name
• add gift weights
• other savior title response (there's another one, forgot which)
• change npc name to <npcname/>

I can just add that to this list.

**Comment by exectails** [comment]
@xCryptic Sounds good :+1:

**Comment by exectails** [comment]
Just two more!

**Comment by exectails** [comment]
:+1:
