### ISSUE TITLE
Shutdown command

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#25]
A console/GM shutdown command, that gracefully shuts down the server, saving everything.

**Comment by Fuhhue** [comment]
i vote this owo

**Comment by Xcelled** [comment]
+1, as it's critical for anyone not doing dev work. As an aid, some things I can think of that will be needed:

- Delay Time, with some reasonable minimum.
- Message
- Command on channel should only shut down that channel
- Channels should set their status to maint and refuse connections X minutes before shutdown
- Login server should refuse new connections X minutes before it shuts down
- Force DC should be sent a short while before channel shutdown
- Once the time is up, kill remaining clients
- Special handling of GMs/admins so they can stay in game until the server actually closes?

**Comment by ImaBrokeDude** [comment]
I think there was someone working on this before, however I did write one myself.

I was able to accomplish the following:

[`ChannelConsoleCommand`]
* 5 minute delay
* TopRed Notice & MsgBox Notice
* command does only shutdown the channel it is executed on
* /!\ refuses new connects to the channel immediately by disconnecting from login server (which automatically places that channel in maintenance.)
* Kill remaining clients once time is up.

I have not:
* Gotten the force DC working (`RequestClientDisconnect`)
* Attempted any kind of special handling for GM/Admins

**Comment by DeleteIT** [comment]
>Special handling of GMs/admins so they can stay in game until the server actually closes?

Why? What use would this possibly have?
It seems like it would just be a potential hazard, since the server would be closing things, and any GM/Admin could mess that process up by using commands.

Not to mention that there is zero reason for it, the server could just use some kind of IM/email API to let you know when it's back up, or if there's an issue, and the admin can't possibly do anything useful in game, that they couldn't do from the console.

**Comment by exectails** [comment]
>refuses new connects to the channel immediately by disconnecting from login server

That isn't refusing connections, that's making it harder to connect, someone could still connect with a modified or custom client.

>command does only shutdown the channel it is executed on

Well, that's the easy the part. The more interesting one is making them *all* shut down.

**Comment by QewQew** [comment]
>Well, that's the easy the part. The more interesting one is making them all shut down.

That sounds like a job for internal communication!

**Comment by exectails** [comment]
>That sounds like a job for internal communication!

One of the least documented features ever added to Aura =P Another system I really want to clean up some time =<

**Comment by ImaBrokeDude** [comment]
>> refuses new connects to the channel immediately by disconnecting from login server

> That isn't refusing connections, that's making it harder to connect, someone could still connect with a modified or custom client.

Sorry technically I kill the connection to the LoginServer and then stop listening for new connections.

**Comment by ImaBrokeDude** [comment]
Alright is there anything else I should add before I submit a PR?

Got the force DC working, would disconnect a player in 4 minutes 30 seconds.

Should I just adjust the command to accept an argument for delay?

**Comment by superjeffreyc** [comment]
@ImaBrokeDude I didn't realize you were working on this too, sorry. I can leave the ChannelConsoleCommand for you to implement after I finish up what I have, since I'm only working on the LoginConsoleCommand and GmCommand.

**Comment by exectails** [comment]
Implemented in #208.
