### ISSUE TITLE
Register script.

### ISSUE THREAD

**Issue by krokogames** [aura-project/aura#260]
Hello Need help with registration.

need help with this code: $ password = hash ("sha256" md5 ($ password));
when you register so I can not connect to a game console, and we show an error.

Thank you for your help

sorry for my English I speak Czech lang :D

**Comment by exectails** [comment]
I'm afraid I don't understand the question. Please try again on our [forum](http://aura-project.org/forum/forum/34-support/) or the [chat](https://github.com/aura-project/aura).
