### ISSUE TITLE
"Unknown database 'aura'" Error.

### ISSUE THREAD

**Issue by Mewymew** [aura-project/aura#262]
I'm really not good at any form of coding, I seem to have done something wrong but I'm not sure what. I followed the guide here; https://github.com/aura-project/aura/wiki/Getting-started
Loosely at least.. Had a lot of issues so sorta improvised a bit.. Now getting this problem. http://i63.tinypic.com/102l0r5.png

I think that's what it wanted me to do for "Once you have finished compiling, simply open start_servers.bat and your server should be running." Or I could have messed something else up... 

Uhh.. I'll go into details where I improvised.. Because I'm not sure anyone could help with this otherwise..

"Afterwards, open <aura directory>/sql/main.sql in your query browser (e.g. HeideSQL) and run it, to create the basic structure for Aura." For this, I have it opened in HeideSQL but I was never able to find a "run" button.. 

I think I complied it right but not sure, that might partly rely on the HeideSQL thing, and I am an idiot, so naturally I still have Microsoft Visual Studio opened because I think I'm supposed to keep that open..

Sorry for the trouble and thanks for reading/replying.

**Comment by exectails** [comment]
You're getting that error because the database that characters and other information are saved in doesn't exist, because you didn't execute/run the main.sql file.

![unbenannt-1](https://cloud.githubusercontent.com/assets/5593920/14630370/7a9b2330-060d-11e6-8cd3-955fbc6d5de0.jpg)

**Comment by Mewymew** [comment]
Thank you very much! <33 I love you! That fixed it! But I still managed to break it, Mabi is still logging into Nexon servers..

Here's the only two things I can think of that it can be..

"Once you have finished compiling, simply open start_servers.bat and your server should be running." I didn't find this but I found the Start-all in the Aura folder, I think that works right? To note, all of those look good with no errors or anything.

With the other issue being "Create a shortcut to your client.exe (right-click client.exe > Create shortcut), right-click it, go to Properties, and modify the Target path to resemble this:"
I have this for it: C:\Nexon\Library\mabinogi\appdata\Mabinogi.exe code:1622 ver:143 logip:127.0.0.1 logport:11000 chatip:127.0.0.1 chatport:8002 setting:"file://data/features.xml=Regular, USA"

I checked the control prompts it brought up and all the server ports (Not sure if proper wording, I'm an idiot.. qq..) matched right, wasn't sure what the "code:1622 ver:143" meant I debated on changing the ver to be Mabi's version but I thought that might break it worse..

I'm sorry for bothering you so much. QQ I really do appreciate the help though.

**Comment by exectails** [comment]
>but I found the Start-all in the Aura folder, I think that works right?

Right, the guide was outdated, fixed it. Thanks.

>With the other issue being [...]

Your properties look correct, so if you use the shortcut to start the client, it *should* connect to your locally running server. What exactly happens?

>I'm an idiot.. qq..

Don't be so hard on yourself, every beginning is hard.

**Comment by Mewymew** [comment]
> Right, the guide was outdated, fixed it. Thanks

No problem and thank you again for helping me.

>Your properties look correct, so if you use the shortcut to start the client, it should connect to your locally running server. What exactly happens?

It opens like normal and I'm able to login to my Nexon account, the new// and new__ tell me invalid username or password, I login and all characters are on Alexina server, login to my main chara in Dunby and I see people, only thing odd about it is when I login the character window is open.

>Don't be so hard on yourself, every beginning is hard.

Thank you, I appreciate the encouragement.

**Comment by exectails** [comment]
Ohhh, I just realized you're using the *Mabinogi.exe*, that's the problem. Note how the guide says to create a shortcut to the *Client.exe*.

**Comment by Mewymew** [comment]
It works now! Thank you very much! <33 I'm really sorry for causing you so much trouble. Do you accept donations? It would prolly be 2 weeks plus before I could donate but I'd be happy to.

**Comment by exectails** [comment]
Good to hear^^ I do accept donations, you can find my Patreon page here: https://www.patreon.com/exec?ty=h
