### ISSUE TITLE
2171 years past 25

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#265]
So one of my friends logged on and saw this. I'm pretty sure this isn't a big deal, but I wanted to share this anyway.

https://i.gyazo.com/ca73eb26cbdf25c90e494a5d9cf6450c.png

**Comment by exectails** [comment]
This will be hard to debug, as we'd need the lastRebirth value to see what's going on. Without it I don't really see what might've happened here =/ If they haven't rebirthed yet, could you check their actual age on the creature database table?

**Comment by Pegwald** [comment]
Sure, how do I do that?

**Comment by exectails** [comment]
Oh, you're using Frontend, right? You'd have to download a database management tool, like [HeidiSQL](http://www.heidisql.com/). Download it, start it, create a new connection to 127.0.0.1 with the user and password from your database.conf, click open, select aura on the left, double click the creatures table, select the data tab and finally search for the character in question. Now just scroll to the age column.

**Comment by Pegwald** [comment]
Wow, that was easier than expected. According to this info, his age would be 33

**Comment by exectails** [comment]
And if he logs in right now it's displayed as 2171 years past 25? o.o If so, could you tell me the lastRebirth and the lastAging dates?

**Comment by Pegwald** [comment]
I will ask him to do that right away

**Comment by Pegwald** [comment]
He's still over 2k years old.

Last aging: 2016-05-10 03:29:46
Last Rebirth: 2015-11-29 21:03:08

**Comment by exectails** [comment]
I can't reproduce it =/

![ss 2016-05-12 at 06 37 40](https://cloud.githubusercontent.com/assets/5593920/15222626/e561283e-1870-11e6-8326-f254a3c2d2c8.png)
![ss 2016-05-12 at 06 36 53](https://cloud.githubusercontent.com/assets/5593920/15222628/e6fe8402-1870-11e6-8bf9-84df19ef2a72.png)

Since the data on the server appears to be fine, there's either a problem somewhere between the data being read from the db and it getting sent to his client, or with the client itself. Not sure which is more likely.

**Comment by Pegwald** [comment]
hmm, I told him to update his client...

**Comment by exectails** [comment]
I was just thinking that it might be the server, but nothing changed in the character info packet in a while. But if his client is really old... that might actually be the problem.

**Comment by Pegwald** [comment]
yes, it is confirmed that he forgot to patch his client so he is now 24 past 25 :)

**Comment by Pegwald** [comment]
sorry for all the hustle, but at least I know how to access and manage the database now ^^

**Comment by exectails** [comment]
Great^^
