### ISSUE TITLE
Now way to obtain Meditation

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#267]
Just like Herbalism in a previous issue (solved long ago btw), the skill 'Meditation' is implemented, but the method of obtaining it is not.
To get meditation one must have all the magic bolts (fire, ice and lightning) at rank F or higher and talk to Stewart about skills, but this does not work. I have all my bolts at rF and he doesn't really want to give me meditation.

**Comment by exectails** [comment]
Thanks for the report, good to have you back^^

**Comment by Pegwald** [comment]
Always good to be back ^^
Thanks
