### ISSUE TITLE
Herbalism quest is impossible

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#268]
Related to #92 and #115 - After doing 10 PTJs at Dilys, you get the quest. That's great, but now it seems impossible to actually pick a base herb without having novice rank of herbalism. Quest reward is the herbalism skill, so how can we pick base herbs without it?

I thought base herb was the only herb one could pick without the skill (at very low success rate), but after wasting well over 200 stamina, it seems impossible. Is there no chance at all for the moment?

**Comment by exectails** [comment]
Heh^^" Yea, gathering fails if you don't have the skill, that's wrong of course.
