### ISSUE TITLE
Kobold bandits' loincloth disapears upon counter

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#273]
If this isn't something added officially in NA, I'm pretty sure this is one of the most silliest bugs I've encountered so far. Try to counter (with any item) a Kobold bandit in Reghinalt and you will notice that something will be missing when it gets back up.

https://i.gyazo.com/adb94c24c6061bd4f15280d18c0016c9.png

**Comment by QewQew** [comment]
![image](https://cloud.githubusercontent.com/assets/11168098/15347847/0d57d3c6-1c7a-11e6-9580-b052c927e505.png)

**Comment by Pegwald** [comment]
After playing mabi for so many years, I feel embarrassed about the fact that I've never noticed this.

**Comment by exectails** [comment]
The Wiki mentioned this feature for Succubi once upon a time, but doesn't anymore. Maybe this was removed? If so, I wouldn't be surprised if they removed it for Kobolds as well. Though I strongly believe we should stick to the old behavior, or make it optional/feature checked.
