### ISSUE TITLE
Fishing skill not granted when equiping rod

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#277]
Title pretty much explains it. I have gotten the keyword from Ferghus too, but that doesn't really do much. I also tried to equip some bait too, but nothing really happens.

**Comment by exectails** [comment]
Weird. I'm sure we had this at some point...

**Comment by Cosrnos** [comment]
Not that it provides much context but I think this was present way back when the foshinogi experiment was underway because I had to code the skill to be given on character creation...
