### ISSUE TITLE
Daily effects

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#278]
Even though the prices in the store looks like they have been reduced by 5%, you actually pay the full amount of gold required. I figured this out when I brought just enough gold to purchase an item and still couldn't buy it. When i brought enough for the amount of the normal price, all the gold was subtracted. All the NPCs are scammers.

**Comment by exectails** [comment]
I'll backlog this, since I just realized we have near to no daily effects yet.

**Comment by exectails** [comment]
**Sunday**
- [ ] Increase in critical hit rate.
- [ ] Increase in lucky finish.
- [ ] Increase in lucky bonus.
- [ ] Increase in success rate for instrument playing.
- [ ] ~~Increase in success rate for magic music~~ (C4)
- [ ] ~~Increase in taming rate using magic music.~~ (C4)

**Monday**
- [ ] Increase in success rate for production skills.
- [ ] Increase in rank up bonus for life skills (110%).
- [ ] Increase in quality of output for productions.

**Tuesday**
- [x] Dungeon maps change even if the same item is dropped.
- [ ] Increase in dungeon item drop rate.
- [ ] Increase in rank-up bonus for Combat skills.

**Wednesday**
- [ ] Increase in item drop rate from animals and nature.
- [ ] Increase in rank-up bonus for complete mastery of a skill.
- [ ] Decrease in prices (5%) for items in NPC shops, including Remote Shop Coupons and money deposit for Exploration Quests.
- [ ] Decrease in Bank transaction fees. (10% --> 7.5%)

**Thursday**
- [ ] Enchant success rates are increased.
- [ ] Increase in rank-up bonus for Magic skills.
- [ ] Increase of proficiency gaining rate.

**Friday**
- [ ] Decrease in penalties if knocked unconscious.
- [ ] All potions become more potent. (Potion effect x 1.5 including toxicity).
- [ ] Increase in rewards for completing part-time jobs. (20% increase in EXP and Gold rewards)

**Saturday**
- [x] As you age and grow, you will obtain AP (takes effect after 12:00pm PDT).
- [ ] Food effects are increased. (2x weight, hunger; effects are long term)
- [ ] ~~You will be able to sketch monsters that move slightly.~~ (C2)
- [ ] ~~The L-Rod's effect will increase over time (this means that the L-Rod's accuracy has increased).~~ (C2)
- [ ] ~~Increase in success rates for Alchemy skills.~~ (C3)

**Comment by Pegwald** [comment]
Aren't some of these already implemented? There has been more potent potions on fridays, I can remember that. Increased success-rate on mondays, wasn't that implemented too?

**Comment by exectails** [comment]
I don't think so. I can't remember implementing them and I don't see them in the code.

**Comment by Pegwald** [comment]
The dungeon item drop-rate on tuesdays feels insane. Are you sure this is right? I got 5 silver gems in one alby int for 2, like 5 longswords too, and plenty of fomor scrolls o-o I have done this dungeon a lot before, but never even known that burgundy spiders drop long swords.

**Comment by exectails** [comment]
I don't know the official value, but I only increased the drop rate by 5%, so if it was 1% before, it would now be 6% on Tuesday. That seemed reasonable in my mind =| However, the drop rate of Long Swords on Burgundy Spiders is 0.04%. Simply adding **5%** on top (5.04%) does seem a bit much in that case, items can go from *very rare* to being common...

I guess we want a percentage increase instead, increasing drop rate by 50% from 0.04 to 0.06 or something like that.
