### ISSUE TITLE
Ciar Basic PQ incompletable

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#280]
There's a Party Quest that is currently impossible to complete. "PQ Defeat the Golem" can't be completed because when you get to the part of killing the metal skeletons, it doesn't count those so you're left at 0/6. This is very annoying because you can't get rid of the party quest either.

**Comment by Pegwald** [comment]
I have a Theory, but I haven't confirmed it in any way yet - Is it the right type of metal skeleton that we need to hunt? The metal skeletons in Ciar basic has armor, meanwhile in normal Ciar, they don't. Maybe that might be the case?

**Comment by exectails** [comment]
The monsters seem correct. Could the following issue be the problem? https://github.com/aura-project/aura/issues/230
The first objective is the Golem, so if you kill the Skeletons first, they won't count, and once you kill the Golem, there will be no more Skeletons to finish the second objective. You would then have to go in again to get those and finish the second and third objective.

**Comment by Pegwald** [comment]
That's what I did, I re-entered the same dungeon and killed the skeletons, but it didn't grant any progress at all.

**Comment by Pegwald** [comment]
I got the same bug in Ciar int. for 2. This time we killed the Golem first, then the skeletons. However, we still didn't get any progress at all for the skeletons.

**Comment by exectails** [comment]
Got it, there was a typo in the skeleton objective.
