### ISSUE TITLE
Missing titles

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#281]
I've noticed that some titles are not obtainable, like fire arrow, bear slayer at age of 10 etc.
Here's another good example - 
https://i.gyazo.com/ff2e2d183afe29cbb23cf93ad7b9319d.png

After completing all of the magic lessons in Tir, I still never got the "Elemental Apprentice" title.

**Comment by exectails** [comment]
You're right, titles are one of those little features nobody ever looked into.

**Comment by exectails** [comment]
Branch: [add-titles](https://github.com/aura-project/aura/commits/add-titles)
Just added:
- the Fishing Legend
- the Butterfingers

I totally forgot the titles aren't only added, but revealed before that as well, to show you they exist... this is gonna be fun .___.

**Comment by exectails** [comment]
Starting a list of presumed G1 titles, to have an overview of the ones that have been done. If feasible they should all be scripted, this gives the admins greater flexibility and we're forced to add a few more events, which gives scripters more to work with.

- [x] 19: the Fishing Legend
- [x] 20: the Butterfingers
- [x] 23: the Lucky
- [ ] ...

**Comment by exectails** [comment]
@xCryptic The effects of the "a friend of X" titles fall into your department, could you take care of those? To limit them to one per day you have to use a permanent character variable, to save when an item was added last. I wish I had known that effect before, missed so many free items =<

http://wiki.mabinogiworld.com/view/Titles#Gifts_Received_using_Beginner_Friend_Titles

**Comment by xCryptic** [comment]
So I would do it the same way I used char vars in my Halloween Event? Is there a certain way I should name them? Also, where should I put this in the scripts?

>I wish I had known about that effect when I still played, missed so many free items =<

Ikr, I never knew you could get these.

**Comment by exectails** [comment]
I would have to look up your script, but probably^^ Name them something unique and descriptive, that is unlikely to conflict with any other scripts vars and easy to identify. Though I'm not sure if it's "them", or "it", can you get *all* items each day, or only from one NPC?

**Comment by xCryptic** [comment]
>can you get all items each day, or only from one NPC?

Yeeah, I dunno. I can test it in a bit. Check gitter, I put the code I currently got right now.
