### ISSUE TITLE
No different ore veins in Barri Basic

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#282]
I was reading a little on the wiki about the different levels of Barri when I came over this note under "Barri Basic"

_"Notes: This dungeon (and higher levels of the Barri dungeon) has two different veins of ore to other instances of Barri. One of them is marked as ORE rather than Ore, which has a higher yield rate for Copper Ore and Silver Ore while Iron Ore is rather scarce. The other is marked as Mythril Ore, which always deposits Mythril Ore. Both of these always appear with two normal ore veins.​​​​​"_
(source: http://wiki.mabinogiworld.com/view/Barri_Dungeon#Basic )

So I did a quick run and I realized that there are no ore veins that either give rare amounts of iron, or give any mythril at all. The Issue here is that there are just normal ore veins in Barri Basic. Legit training of the Refining skill at higher ranks may be slow without the opportunity to obtain mythril, so perhaps consider this a case were you can get 2 birds with one stone ;)

**Comment by exectails** [comment]
We'll have to double check this with NA, since it doesn't seem like there's anything special about Barri Basic in terms of ore. Just like Barri Normal it uses the "CollectProp_Test" puzzle, which simply spawns 4 identical ore props in one segment/room, that drop Iron, Copper, Silver, and Gold Ore.

**Comment by Pegwald** [comment]
I'll check it out tomorrow ^^

**Comment by Pegwald** [comment]
Okay, so I did a Barri Basic in NA and it seems that the wiki was wrong this whole time about the "ORE" veins and the mythril veins. Maybe this has been confused with Barri Advanced were those ore veins appears. It seemed very unfortunate, but  what I did notice was that there were 4 veins of ore, both in rooms and corridors. Is this something that is worth considering? I should probably check out more versions of Barri to conclude where there are and aren't specified ores.

**Comment by exectails** [comment]
What do you mean by "there were 4 veins"? We should have 4 veins as w- ...
```csharp
for (int i = 1; i <= 3; ++i)
{
	var oreDeposit = new OreDeposit(22000, "Deposit" + i);
	propPlace.AddProp(oreDeposit, Placement.Ore);
}
```
Alright, who wrote that code?
![ss 2016-05-21 at 10 07 41](https://cloud.githubusercontent.com/assets/5593920/15447235/eaf0f4b0-1f3b-11e6-92c7-87549649c987.png)
Damn it =<
