### ISSUE TITLE
Switching equipment with loaded bolts

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#284]
Found a silly bug were you can charge a bolt and then switch to secondary item-set without losing the charges. You can charge 5 bolts with a wand and then switch to a sword, and also same way around.

**Comment by exectails** [comment]
You're supposed to lose the charges if you switch weapons? o.o

**Comment by Pegwald** [comment]
That's right ^^ There used to be mana evaporation too before - if you unequipped a wand, you would lose nearly all of your mana. This changed in later updates, however, it's completely removed from the game now.

**Comment by exectails** [comment]
Right, that I do remember.

**Comment by exectails** [comment]
I've fixed the issue and implemented mana burn. The canceling of bolt skills can be deactivated in the configuration, while the the mana burn *removal*, which came with G15S2, can be enabled via the features db. https://github.com/aura-project/aura/blob/master/system/db/features.txt#L367
