### ISSUE TITLE
Rank F enchant training

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#286]
I used the skill for my first time and I got a great success. Neat, I got the training exp for "achieving a very good result", but I didn't get any training for "Using the skill successfully". That's not right, is it?

**Comment by exectails** [comment]
Good question. One the wiki the requirements are called the following, possibly coming from an older localization version:
- Get a success.
- Get a great success.
- Get a failure.
- Get a horrible result.

Going by this naming scheme I assumed a success is not the same as a great success.

**Comment by Pegwald** [comment]
I see... Then it might just be the skill info that is wrong, or?

**Comment by exectails** [comment]
Either the training description is confusing or a great success/fail is a success/fail as well. We have to find out which one is correct.

**Comment by exectails** [comment]
Under the assumption that a great success is still a success, that they changed the description because it was ambiguous, and because other skills work similarly, I'm gonna change this.
