### ISSUE TITLE
Upgrade error (Fire elemental resonance)

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#287]
Stewart is unable to upgrade "Fire elemental resonance" twice on a fire wand. First time worked well, but I am unable to get a second upgrade of the same kind. I only get "(error)" displayed in the dialogue.

*Edit - once I re-logged it appears I have gotten two more of the same upgrade. However, it doesn't display that I have gotten a mana usage reduction.

**Comment by exectails** [comment]
There should've been a warning or error in the channel console. Anything?

**Comment by Pegwald** [comment]
I tried to upgrade a new firewand, but I got the same bug. Chaincasting still doesn't work. 
[Firewand upgrades.txt](https://github.com/aura-project/aura/files/276170/Firewand.upgrades.txt)

**Comment by exectails** [comment]
There's some problem with the WU meta data coming from the item... I'll have to look into that. It would help to see the meta data of your item before this upgrade fails, but that item would probably be a little harder to find in the database's item table. You'd have to look for the item id.

**Comment by Pegwald** [comment]
I've got a wand like that, but how do I exactly do this? ^^"
If it isn't too hard to explain, maybe there's a chance I can learn how to do it :)

**Comment by exectails** [comment]
A quick how-to can be found in MabiPale's thread on the forum: http://aura-project.org/forum/topic/220-mabipale-packet-logger-updated-2015-12-20-v290/

**Comment by xCryptic** [comment]
@exectails You just want the ItemNew packet right?

```
Op: 000059E0, Id: 00100000000844C9

001 [005000CC3B5332BF] Long   : 22518875305489087
002 [..............02] Byte   : 2
003 [................] Bin    : 0B 00 00 00 B4 2E 02 00 9D 92 B1 00 4F 5D 68 00
                                EC B7 0A 00 00 00 00 00 00 00 00 00 00 00 00 00
                                00 00 00 00 00 00 EB 00 02 00 00 00 00 00 00 00
004 [................] Bin    : 35 9E 1D 10 50 C3 00 00 88 13 00 00 00 00 00 00
                                76 3A 00 00 98 3A 00 00 E0 2E 00 00 0E 00 26 00
                                14 00 28 00 30 1F 65 61 00 00 00 00 00 00 00 00
                                04 00 BE 01 16 06 05 00 00 00 00 00 00 00 00 00
                                00 00 00 00 00 00 00 00 FF FF FF FF 00 00 00 00
                                00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                17 4F 01 00
005 [................] String : EHLV:4:5;MTWR:1:1;OWNER:s:Username;WU:s:00000000000c10;
006 [................] String : 
007 [..............02] Byte   : 2
008 [................] Bin    : 02 00 00 00 00 00 00 00 02 00 00 00 1B 00 01 00
                                00 00 00 00 0A 00 00 00 00 00 00 00 0A 00 00 00
                                00 00 00 00
009 [................] Bin    : 07 00 00 00 00 00 00 00 1B 00 00 00 9B 00 02 00
                                FA 75 01 00 0A 00 00 00 00 00 00 00 0A 00 00 00
                                00 00 00 00
010 [0000000000000000] Long   : 0
011 [........00000001] Int    : 1
012 [........0000000E] Int    : 14
013 [........00000044] Int    : 68
014 [..............00] Byte   : 0
015 [..............00] Byte   : 0
```
![](http://i.imgur.com/aPdQx8c.png)

**Comment by exectails** [comment]
@xCryptic Yes, perfect. Thanks.

**Comment by exectails** [comment]
Here we go, give it a try.

**Comment by Pegwald** [comment]
Everything is displayed now ^^
Too bad I am still just able to charge a single bolt :/
