### ISSUE TITLE
Cooking is useless

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#288]
We checked out cooking - the mini-game works well and all, but it's just unfortunate that all you can cook is food waste. We tried a lot, but it seems that you can not cook anything but food waste. Food waste isn't really useful now, is it?

**Comment by exectails** [comment]
And that's what you need unit tests for. *Wow.* Such a stupid bug. And cooking was working perfectly at one point, then I must've changed something simple without testing again and months later you have to file an issue.
