### ISSUE TITLE
Food effects stack

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#290]
It's unlimited for how many food effects you can have at once, so cooking now gives gives you a ridiculous amount of stats. This one was funny.

**Comment by exectails** [comment]
Maybe this should be configurable, a server where cooking is essential to compete could be funny^^

**Comment by exectails** [comment]
So, how exactly do they work? Going by what you said I presume you're not supposed to be able to eat the same thing twice and get the bonus twice. What if you eat something with +2 Str first, and then something with +5, does it stack? Does it override? Do you keep the +2?

**Comment by Pegwald** [comment]
I am not sure about this, but I think if you try to eat two dishes, the first dish buff and duration will be overwritten and the last dish you ate will be the one that counts. However, I so also think you can have two food buffs at once, one from food and one from beverage. I think that's the case. Not really sure about it really ^^ ''
I can ask one of my friends about this. He used to cook in EU and NA.

**Comment by exectails** [comment]
That would be helpful, thanks. Another question: Is it per food or per stat? As in, if you eat something with +Str, and then something with +Int, do you get both, or is the Str effect removed?

**Comment by Pegwald** [comment]
I would guess the strength would be removed. I think I tried this long ago, but you never know these days when there has been plenty of reworks, revamps and updates - everything that confuses me...

**Comment by Pegwald** [comment]
... Just as I thought, I reset the previous dish I ate by eating a new one. All the effects reset and I get a new one. I could reset the buffs from a T-bone steak with chocolate milk, but I will check if I can manage to drink an alcoholic beverage and still keep the 'food' effect.

**Comment by exectails** [comment]
Feel free to double post on here, otherwise I don't get a notification^^ Thanks for the research!

**Comment by Pegwald** [comment]
Oh, I thought you got notifications whenever I posted something. Sorry ^^
