### ISSUE TITLE
Fishing quest scrolls

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#292]
I have managed to catch items and fish, but not a single quest. I suppose this haven't been implemented.

**Comment by exectails** [comment]
Right, Fishing was added before we had support for quest scrolls. Those are currently commented in the fishing grounds db. We're gonna have to add support for them, and add the quests of course.

**Comment by exectails** [comment]
You should get collection quests from fishing now. Some quests that you can fish haven't been implemented yet, so I'll leave this open, so we don't forget to activate them.

**Comment by Pegwald** [comment]
I got a quest scroll now, but I didn't get any training for "catch a quest scroll". I got training for "catch an item" instead. - Rank B fishing.

**Comment by exectails** [comment]
What would I do without you?

**Comment by Pegwald** [comment]
The same thing I would do without you *blushes*
