### ISSUE TITLE
possible firebolt bug

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#295]
I am a bit conflicted when it comes to calculating different types of damages. I just can't seem to get this right.

_Critical hit is supposed to increase damage by 150% upon critical hit right? That's a 150% addition to the 100% pure damage._

Let's take magnum shot. That's basically a normal ranged attack with 500% scaling at R1. If a bolt deals 200 regular damage, the magnum would deal 1000 damage. Add the R1 crit and this will be a total of 2500. This worked well in practical.

Now firebolt (R1) is a different story. A single charge deals 170 damage. In theory 5 charges would be 500% damage, just like magnum shot, right? That's 850. However, when I cast 5 charges I get 1100-1200 damage. I also got a critical hit - 2900 damage.

I slowed down a bit and I tried doing this in pratice, elevating my way upwards with charges of firebolts.

1. 178 (452)
2. 335 (833)
3. 538 (1236)
4. 666 (1651)
5. 1187 (2968)

Where is that sky-rocketing spike from 4 to 5 charges coming from? Did I miss something? Am I just terrible at math? o.o

**Comment by exectails** [comment]
http://wiki.mabinogiworld.com/view/Firebolt
>For the first 4 charges, the damage is multiplied by the number of charges. At 5 charges, Firebolt damage will by multiplied by 6.5.

You have 650% with 5 charges.

**Comment by Pegwald** [comment]
... oh it makes sense then. I feel defeated.
