### ISSUE TITLE
incorrect monster aggro

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#298]
_I didn't bother looking this up at the wiki since I have a feeling it might screw me over like it always does. I will follow my heart on this._

Some monsters have different AIs than what I was used to in the official version. I will list some mobs here:

-**Gorgon**: Should multi-aggro, but only aggro one by one.
-**Wood Jackals**: Just like Gorgon, they should multi-aggro if they are within aggro range.
-**Town rats**: Should **not** auto-aggro. I am not very bothered by this, but I don't remember them being so aggressive in the official version.
-**Werewolves**: Are they supposed to multi-aggro? 
-**semi-aggro>aggro**: I've noticed that if you are fighting enemies that don't multi-aggro, but aggro one by one, they will attack instantly if they go from a semi-aggro state to an aggro state, like when you kill an aggroed monster, the next mob will run at you immediately. Isn't there suppose to be some sort of delay before they aggro or something?
-**semi-aggro**: I might be wrong about this one, because I can't remember it quite right, but when you inflict damage in an AoE at several enemies, one will always aggro you, but aren't all the others supposed to become semi-aggro instantly?

**Comment by exectails** [comment]
@Sairii, could you take a look at this? You've spend a lot more time with the AIs.

>Town rats: Should not auto-aggro

We only have one rat AI, which was probably written for the dungeon rats, which explains why they hate players. I guess we need a second one.

>Werewolves: Are they supposed to multi-aggro

No, I don't think so. Do they multi-aggro on Aura? o.o

>Isn't there suppose to be some sort of delay before they aggro or something?

Yea, there should be. Some tweaks in the AI have been postponed because the entire system is gonna get a rewrite soonish.

>aren't all the others supposed to become semi-aggro instantly?

Not necessarily, iirc that depends on the monster and the skill.

**Comment by Pegwald** [comment]
> Do they multi-aggro on Aura?

I thought they didn't but suddenly I had 3 coming at me at once.
Here: https://www.youtube.com/watch?v=mx35--RvThY

**Comment by exectails** [comment]
Yea, that can be attributed to the "not waiting" thing, they all 3 noticed that you're "free" at the same time and all started attacking, before one could "claim you".

**Comment by Pegwald** [comment]
Ah, I see.

**Comment by boilerplate5** [comment]
Werewolves multi-aggro in that they can choose to attack other players present but unless more than one is attacked the player can go one-on-one with them, one at a time. When you use windmill, no matter what, only one enemy is going to both notice and engage you. Windmill should never trigger a situation by itself where enemies all become aware of or target the player.

This may have changed slightly at some point. I stopped playing officials after the Iria patch, but the basics of melee combat have stuck with me.

**Comment by Sairii** [comment]
Oh totally didnt see this until now...
Yes, I think there are like 3 rat ais.
Gorgons should have multi aggro too
wood jackal is currently using the coyote ai, which is wrong. Only the normal jackal, timber wolfs and a few more use that AI.

So yeah... imma fix that later

**Comment by QewQew** [comment]
>Werewolf AI has no SetAggroLimit, so thats why they have multi aggro.

But by default, the limit is one. So by not having a SetAggroLimit, it shouldn't multi aggro..?

**Comment by Sairii** [comment]
apparently default is none?

**Comment by QewQew** [comment]
https://github.com/aura-project/aura/blob/master/src/ChannelServer/Scripting/Scripts/AiScript.cs#L125

**Comment by Sairii** [comment]
that is quite wierd
