### ISSUE TITLE
Field Bosses

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#299]
G1 field bosses.

http://wiki.mabinogiworld.com/view/Category:Field_Boss
http://wiki.mabinogiworld.com/view/Category:Field_Boss_Location

- [x] Giant Black Wolf
- [x] Giant White Wolf
- [x] Giant Bear
- [x] Black Warrior
- [x] Goblin Bandit
- [x] Black Raccoon
- [x] Giant Ogre
- [x] Black Wizard

**Comment by exectails** [comment]
While there's many ways we could implement those, I think the one that gives us the most freedom is a script approach. We write a base script, which the actual field boss scripts, one for each, inherits from, allowing them easy access to common methods among them.

This way users have full control over it, and can easily add new ones and edit old ones all in one place.

**Comment by xCryptic** [comment]
I just want to leave a note here so it's not forgotten: some NPCs will say something about a field boss before and during its spawn.

**Comment by exectails** [comment]
Thanks for the reminder, those will have to be hooked.
