### ISSUE TITLE
Skills

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#3]
**Combat**
- [x] Combat Mastery
- [x] Smash
- [x] Defense
- [x] Counterattack
- [x] Windmill
- [x] Stomp (Monsters)
- [x] Sharp Mind (old)
- [x] Heavy Stander
- [x] Natural Shield
- [x] Mana Deflector

**Ranged**
- [x] Ranged Attack
- [x] Magnum Shot
- [x] Support Shot
- [x] Arrow Revolver (G1)

**Life**
- [x] Rest
- [x] Gathering
- [x] Fishing
- [x] Blacksmithing
- [x] Cooking
- [x] Potion Making
- [x] Refining
- [x] Tailoring
- [x] Weaving
- [x] Milling
- [x] Handicraft
- [x] Campfire
- [x] First Aid

**Music**
- [x] Playing Instrument
- [x] Composing

**Magic**
- [x] Icebolt
- [x] Lightningbolt
- [x] Firebolt
- [x] Healing
- [x] Enchant
- [x] Meditation

**Hidden**
- [x] Resurrection

**Comment by UnknownVoid** [comment]
Don't Forget Item skills such as Phoenix Feathers and Dice, Then Action skills such as throwing Paper Air Planes (G1).

**Comment by QewQew** [comment]
>Dice, Then Action skills such as throwing Paper Air Planes (G1).

None of those are G1...

**Comment by xeroplz** [comment]
Hmm, are you literally going to code the G1 Arrow revolver? I'm fine with G1 or Present, but I just think it'd be easier in the long run to just code the current version over the old one so we don't have to update it again later.

**Comment by exectails** [comment]
@xeroplz There are literally two Arrow Revolver skills. The player one you're talking about didn't exist until later.

**Comment by DeleteIT** [comment]
I don't think there's any point in coding Mari's prototype version, since she's the only one who ever gets it.
Maybe that skill ID could go towards making some custom skill, or something (There's another ID for it, isn't there?)

**Comment by exectails** [comment]
Our goal is to emulate Mabinogi as closely as possible, and that's what we're going to do o.o If someone wants to give her the normal AR and use the skill for something else, that's their business.

**Comment by xeroplz** [comment]
I'm fine with Mari's prototype version anyway. I'd like to see it in action myself. If we gotta do both, that's fine with me though

**Comment by DeleteIT** [comment]
The prototype is literally just bolt AR. Charge an AR. 1 stack. Charge an AR. 2 stack. Repeat.

Which is why I said there's no real point to it, it's not very useful, and Mari is the only one who gets it.

**Comment by exectails** [comment]
>Which is why I said there's no real point to it, it's not very useful, and Mari is the only one who gets it.

No, it isn't, and I don't think anybody ever thought "I wish I had the Mari version of AR instead", but it's not for us to decide, if we want to emulate Mabi 1:1.01. It's an official skill, used by an official, playable NPC, so it has to be implemented.

>I'm assuming Arrow Revolver was the prototype?

Yea, I think so.

**Comment by exectails** [comment]
Looking at the AR data, it will actually be very easy to implement both in one handler, all their differences seem to come from skill variables.

**Comment by exectails** [comment]
lol, Mari's AR really is kinda pointless now, it has 0 load time in the new combat system, so you can just spam the hotkey, to immediately stack up 5 arrows xD

**Comment by Sairii** [comment]
wait wat?
It doesnt have the 3-4 seconds CD?

**Comment by exectails** [comment]
It has a cool down, but no load time. The cool down only prevents you from casting it again for 10s after each shot.
