### ISSUE TITLE
Nora repair dialogue is incorrect

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#301]
I tried 1-point repairing beginner clothes (cost 1g) and she said I didn't have enough gold. She did repair it (successfully), but still gave me the incorrect dialogue.

**Comment by exectails** [comment]
Indeed, seems like a gold fail [message](https://github.com/aura-project/aura/blob/master/system/scripts/npcs/tir/nora.cs#L94) was mixed in with the success messages for 1 point. Though this *could* be official. In which case we should probably fix it anyway. Do you remember, @xCryptic?

**Comment by Pegwald** [comment]
Now that you mention it, maybe it **is** official. I wonder if I read it on the wiki before in trivia or something that this should happen when you try repairing newbie wear. hmm...

**Comment by xCryptic** [comment]
Hmm... I did this awhile ago. Though I'd say that it was logged like this, but I can't remember what I was repairing... I'll try logging it later and see what happens.

**Comment by xCryptic** [comment]
Okay... this is really weird. I'm getting a lot of different messages. Some are still the same though.
```
					if (!result.HadGold)
					{
						RndMsg(
							"Do you have enough Gold?",
							"I'm sorry, but you need to pay more to repair that.",
							"Yes, it's my side job, but it certainly is a job.<br/>If you don't have enough money, I can't repair it."
						);
					}
					else if (result.Points == 1)
					{
						if (result.Fails == 0)
							RndMsg(
								"The repair is done.",
								"OK, it was a success.",
								"1 point, I think the clothes were well repaired."
							);
						else
							RndMsg(
								"Oops!",
								"Oh, sorry. I made a mistake.",
								"It says, \"My hands slipped\".<br/>What does that mean?"
							);
					}
```
I have no idea what the problem is. Did I log the wrong NPC or did the messages change? I can't even find the log to Nora either.. I guess something went wrong on my end.
