### ISSUE TITLE
can't obtain "The hungry"

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#304]
I can't obtain the title "The hungry". I managed to get a 0 durability newbie wear (beginner long pants), 50% hunger, but when I use the "clothing shop" keyword at Glenis, she only gives me the direction to Simon's clothing shop without giving me the title (and repairing the wear). I also tried without any gold in my inventory. Nothing really works.
I made this issue since I noticed the title was implemented, but not obtainable.

**Comment by exectails** [comment]
Well, I did make a mistake in Glenis, as you should get knowledge about the title when you talk about the Clothing Shop, but I put it in the Private Story keyword. That's only part of it though, you actually get the title when you talk to *Simon*, about Private Story.

>Talk to Simon about Private Stories while wearing ONLY a Beginner Long Pants (or skirt, or the equivalent basic Elf or Giant Newbie Wear) that has 0 Durability (this includes items in the Style tab, even when it's locked), and with Hunger at 50%. Upon receiving the title, the newbie wear will be fully repaired.
