### ISSUE TITLE
Splash Damage

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#307]
We're currently missing splash damage from normal attacks and high rank Smash. This has to be added, together with the SplashRadius and SplashDamage upgrades.

This might require some changes in how CombatMastery and Smash are handled, as there will potentially be more than one target, but we can simply create a list of targets with the main target as the first, to loop through them.

**Comment by boilerplate5** [comment]
I'm sure you know, but when Splash Damage comes up, Magnum Shot at rank 5 also starts doing the same.

**Comment by exectails** [comment]
https://github.com/aura-project/aura/tree/add-splash

**Comment by exectails** [comment]
Implemented, tested, seemingly working. Keep an eye on it^^

Less to do, @xKamuna.
