### ISSUE TITLE
Alby Basic Pass

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#308]
I have never gotten this pass on Aura, so I went to the wiki to check out what mobs actually drops this. I also headed over to the "races" document in db to check if this was correct and I found out that there are currently just two mobs who drops this pass:

-Blue wolf (Alby basic) 0.7 drop chance
-White spider (ID:30001 and 30014) 0.3 drop chance

So right now only the white spider can drop it in order to get to alby basic.
According to wiki, this pass should also be obtainable from giant spider, black spider and red spider, but these do not show up in db. You're also supposed to get the pass in end chests in alby.
I have only managed to get int passes for 1, 2 and 4 :/

**Comment by exectails** [comment]
You can definitely get the Alby Basic Pass from Alby Normal in Aura, and the chance is twice as high as the Int Passes, though combined it's more likely for you to get an Int Pass than a Basic Pass.
https://github.com/aura-project/aura/blob/master/system/scripts/dungeons/tircho_alby_dungeon.cs#L160

You're right about the pass only dropping from White Spider and Blue Wolf, but the question is whether or not the Wiki is right about more monsters dropping them. The Wiki is not even consistent here, as the pass is not listed as a drop for the red and black spider on their own page.

Our drop data is based on official information. According to that information there are four monsters that drop the Basic Pass:
- WhiteSpider
- Hardmode_WhiteSpider
- BlueWolf
- Hardmode_BlueWolf

I've never been a big fan of Alby, so I don't have any personal experience, but I'd wager that the Wiki is wrong in this case. I've gone back to the very beginning of that page's history, and at that point those spiders were already mentioned, which makes me think that nobody ever tested this, they kept the data, wherever that might've come from, and only updated the page.

**Comment by Pegwald** [comment]
Wow... I did a single normal run and I got the pass. Case dismissed?

**Comment by exectails** [comment]
I guess so^^ We'll reopen this issue if anyone has new information at some point.
