### ISSUE TITLE
Equip repairing and modifying in Bangor

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#311]
_I'm pretty sure this haven't been forgotten, but I couldn't find any issue of it... so here I go._

The NPCs in Tir and Dunbarton already have all their modify and repair options, but in Bangor there's still lacking some. Despite Edern is the best blacksmith, he's just really useless ^^ ''

**Comment by xCryptic** [comment]
Yeah, I haven't gotten to Bangor yet. I gotta make some changes to Tir and Dunbarton, and then I'll get to Bangor.

If you want to help, log repair & upgrade messages for me :)

**Comment by Pegwald** [comment]
I really want to help, but I can't do anything else than reporting bugs... qwq

**Comment by boilerplate5** [comment]
Do you still need their messages?

In the case of those particular dialogues, do they need to be logged through tools or can they simply be screen capped and written down?

**Comment by xCryptic** [comment]
@boilerplate5 I do still need them. It'd be _a lot_ easier to log it using [Morrighan](http://aura-project.org/forum/topic/40-morrighan-client-proxy-updated-2015-12-13-v156/) and [MabiPale](http://aura-project.org/forum/topic/220-mabipale-packet-logger-updated-2015-12-20-v290/).

Of course, with this 100% repair event going on, it's impossible to get the fail messages. So it'll be awhile until it can be considered complete.

**Comment by boilerplate5** [comment]
@xCryptic I can't find info on that event. When's it end?

**Comment by exectails** [comment]
August 30th!? I guess we really should add them with "(missing dialog") texts for now, @xCryptic.

**Comment by boilerplate5** [comment]
Yep. http://puu.sh/pE5G0/7e6e4bf0d5.jpg

**Comment by xCryptic** [comment]
>August 30th!? I guess we really should add them with "(missing dialog") texts for now

Yeah, I was talking about that on Gitter the day that event started. It might take some time before I get to these though. Right now, I'm trying to get all the Greetings I've missed along with the other fixes I stated in another issue.

>I'm also willing to do a quick writing up if need be, I believe there's an NPC template floating around somewhere and I've got a lot of time.

What do you mean by a quick write up?

**Comment by boilerplate5** [comment]
@xCryptic
I'm a bit hyper this morning and hastily suggested I'd just write up some filler text and do other menial things to help out. Trying to do as much as I can with my limited abilities.

**Comment by xCryptic** [comment]
Ah, feel free to tackle it if you want. I'll review what you got when you're ready. I still have to update my [NPC tutorial thread](http://aura-project.org/forum/topic/299-tutorial-how-to-code-an-npc/), but it has helpful info :)

**Comment by exectails** [comment]
If we don't use filler we can also just do what I've been doing with actual non-obtainable dialog so far.
https://github.com/aura-project/aura/blob/228a1aa27167e0e545591842e40d157b49e95cca/system/scripts/quests/beginner_uladh/202043_talk_with_stewart.cs#L34
