### ISSUE TITLE
Fished items durability

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#313]
_Most equipment fished up will have 0 durability, but can be repaired.
This does not necessarily apply to event items obtained through fishing.
This does not apply to equipment that are irreparable, such as a Gargoyle Sword._

source: http://wiki.mabinogiworld.com/view/Fishing

I was so happy I finally got something else than fish and quest scrolls for once, but I wasn't so excited anymore when I realized my new Gargoyle Sword had 0 durability.

**Comment by exectails** [comment]
Minor mistake on my part. A check for that did exist, but it wasn't correct. Sorry about that, when you finally caught something of interest^^

**Comment by Pegwald** [comment]
dw, I just fixed it in the database so I didn't have to feel so salty about it ^^
