### ISSUE TITLE
Dungeon cutscenes

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#316]
I want to mention this because right now there is a problem with how the dungeon/boss cutscenes are dealt with.
On one side we have the fact that if you have a party leader and x-amount of members, all members will only see the party leader in the cutscene, which leads us directly to the next issue - If the party leader disconnects, the other members are unable to skip or proceed after the cutscene.

Every member should be able to cancel a cutscene and go straight to action (unless party leader is doing a mainstream quest).
A cutscene should also end automatically instead of fading to black and never end, leaving all members in a party unable to do anything if the leader should DC.

**Comment by exectails** [comment]
Thanks for the issue, but there already is one for this problem: #72 

Though the DC problem should definitely be kept in mind.
