### ISSUE TITLE
Death-bug

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#319]
I don't know how I can explain this, so I just made a video for you to watch it.
It started happening recently that if a mob finishes you off with a "ghost punch", you will stay unconscious and unable to revive. I don't know what causes the ghost punch or why you can't revive without having to relog, but I found an error in the channel log. I will upload it here too:

[2016-06-22 0100 [Error] - Exception in LycanthropeAi.txt](https://github.com/aura-project/aura/files/327981/2016-06-22.0100.Error.-.Exception.in.LycanthropeAi.txt)

https://youtu.be/hcZO6lAWUx0

**Comment by exectails** [comment]
Does that happen every time you fight Lycanthropes?

**Comment by exectails** [comment]
Nvm, I think I got it. Stupid mistake.

**Comment by exectails** [comment]
Should be fixed now. It should be reproducible, and should happen every time you die while being in a party, by the claws of a monster that one of your party members didn't attack yet. I've closed this for now, should you encounter it again somehow we'll reopen.

Thanks for the report! There's bugs that are really hard to test for.
