### ISSUE TITLE
Hilt polishing error

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#320]
Similar error like #287 , I get an "(error)" when I try to upgrade my gathering knife at Deian. It doesn't display that I have done any upgrade, but when I relog I can see that I have used 1 upgrade on my gathering knife. The upgrade effect is not displayed, so I suppose it's not working either. It's hard to see if it's 0.25 sec faster ^^ ''

**Comment by exectails** [comment]
Stupid mistake =< Thanks for the report~
