### ISSUE TITLE
Armor Doesn't Gain Proficiency

### ISSUE THREAD

**Issue by boilerplate5** [aura-project/aura#321]
Having played long enough with some different armors and some tailored items I notice they only lose Durability but cannot gain proficiency for any reason. They should gain proficiency for just being worn and by taking damage.

There is a _chance_ according to the wikia that armor gains proficiency on taking hits, but I'm certain this isn't happening in Aura.

**Comment by exectails** [comment]
You're right, this does appear to be missing. I thought I added it... but I guess that was only the dura loss every 5 minutes. Thanks for the report.
