### ISSUE TITLE
Elf Ranged Attack versus Defense Skill

### ISSUE THREAD

**Issue by boilerplate5** [aura-project/aura#322]
According to the wiki, **Elf Ranged Attack** should not do full damage an enemy if they use **Defense**, but will still fire two arrows with only one hitting and triggering the enemy defense, the other firing uselessly.

Currently in Aura, if an enemy is defending and an Elf fires at them with Ranged Attack, one arrow will hit their defense and the other will hit them as normal. This causes a 'stun' on the Elf player as if they struck the Defense with melee or something else - basically, it's the window of opportunity the opponent should have to hit back.

Personally having experienced it, I think it should be up to a config of some sort to toggle this bug. Accurately, an Elf should not be able to do this by the official standard, but on the other hand, it's neat and gives them an advantage some may find well deserved.

**Comment by exectails** [comment]
I wish we could deactivate the other races, so we don't have to worry about stuff like Elf specific Ranged handling yet =P

**Comment by exectails** [comment]
Thanks for the report, it should be working like on officials now.

Regarding your suggestion of adding an option for it I'd like to ask you to create a separate issue, which I can tag as "suggestion", or a thread on the forum, for others to comment and "vote" on and discuss the potential repercussions. I'm all for customization, but I've never played an Elf, and I don't know if this is a sensible option to add.
