### ISSUE TITLE
Animations and Poses

### ISSUE THREAD

**Issue by boilerplate5** [aura-project/aura#323]
Having started up the game again to look into some things, I noticed there are a lot of different animations for stuff now. An obvious one is that rest has a lot of different poses for characters at the earlier ranks but switches over to more unified ones the closer to R6.

But if you get hit with a shield equipped, your character does more buckling and crumpling under assault. Holding a weapon like the stick definitely has a different set of animations, as a 1h blunt weapon just being carried. There are a lot of little things like this that need to be researched in my opinion.

**Comment by exectails** [comment]
If anyone feels like logging those differences, go ahead^^

**Comment by boilerplate5** [comment]
Actually I'm full of crap on the blunt weapon part, I quickly checked, but I know that Rest has a lot of different animations, most of which aren't triggering for me. It's not really a big deal either in my opinion because everyone eventually has the same animation but I've logged the female char poses and the "getting hit with a shield" stuff. 

The rest stuff is kind of superfluous in the end because everyone uses the same animation after hitting Rank 9 but I was bored. The special animations, like when holding puppets or being in swimsuits, should automatically trigger in Aura, like with using Rest while equipped with a Pillow.

[Rest (Arms under Thighs).txt](https://github.com/aura-project/aura/files/331800/Rest.Arms.under.Thighs.txt)
[Rest (Japanese style).txt](https://github.com/aura-project/aura/files/331802/Rest.Japanese.style.txt)
[Rest (Legs out).txt](https://github.com/aura-project/aura/files/331801/Rest.Legs.out.txt)
[Getting Hit (New Shield Anims).txt](https://github.com/aura-project/aura/files/331804/Getting.Hit.New.Shield.Anims.txt)

**Comment by exectails** [comment]
Wait, what exactly are you referring to with Rest? The different styles, below R9 should automatically come from the clothes you're wearing.

**Comment by boilerplate5** [comment]
Oh, it's based on clothes? My bad.

**Comment by exectails** [comment]
Alright, this seems to be solved then.
