### ISSUE TITLE
Coupon Customizations

### ISSUE THREAD

**Issue by boilerplate5** [aura-project/aura#324]
I noticed on the board there were was a question about the special hair, eye, and faces for characters available in the dressing room. Is it necessary to log the purchasing of an aesthetic to make the dressing room and its associated vices available for Aura? Although with how they're in the client it'd probably be easier to make them available in regular char creation anyway, since these 'permanent' options require coupons and will vanish upon rebirth in the grand scheme of things.

Just say the word though and I'll have a log here in a jiffy.

**Comment by xCryptic** [comment]
I'm pretty sure it'll need to be logged. If those coupons have a "Use" function, an item script can be made to change the hair/face that way (for now).

>will vanish upon rebirth in the grand scheme of things

Just a note, this is only if you change that option to something else.

**Comment by boilerplate5** [comment]
The coupons are used as part of the transaction in the dressing room, but not quite like a material for crafting.

Should I get a log of using the dressing room to change appearance?

**Comment by xCryptic** [comment]
Actually, I think I got one of those from an event, but I'm not gonna use it on my main since I like the hair he already has. I'll see if it's bank tradeable and use it on an alt.

>Should I get a log of using the dressing room to change appearance?

Uhh, I'm sure that would still be useful, but @exectails is the one who'll be looking at the logs, so I can't really answer for him xD

**Comment by exectails** [comment]
We will need logs of the Dressing Room if we want to implement it, but I don't plan to tackle that feature until (much?) later. You can already log it of course, we appreciate research for future features as well, and maybe someone else wants to implement it sooner. Feel free to log it and post it on the Research forum.
