### ISSUE TITLE
Script functions

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#325]
We decided early on that we wanted the scripts to be simple, even though they were C#. One aspect of this was that we made all methods appear like simple functions, `Msg`, `GiveItem`, `TrainSkill`, etc, without an object to call them on, or parameters like the creature that the method affects. While I still believe this makes scripts more readable, they have become more involved, they need more calls to methods, and we now have a disconnect between the simplicity and normal C#.

Take this method I'm currently writing for Nao for example:

``` csharp
private async Task Birthday()
{
    // Unofficial
    Msg(L("Happy Birthday, <username/>! "));
    Msg(L("I have a little something for you on this special day,<br/>please accept it."));

    var potentialGifts = new int[] { 12000, 12001, 12002, 12003, 12004, 12005, 12006, 12007, 12008, 12009, 12010, 12011, 12012, 12013, 12014, 12015, 12016, 12017, 12018, 12019, 12020, 12021, 12022, 12023 };
    var rndGift = potentialGifts.Random();

    GiveItem(rndGift);
    Player.Vars.Perm["NaoLastPresentDate"] = DateTime.Now.Date;

    if (IsEnabled("NaoDressUp") && !HasKeyword("present_to_nao"))
        GiveKeyword("present_to_nao");

    await Conversation();

    Close(Hide.None, "Until we meet again, then.<br/>I wish you the best of luck in Erinn.<br/>I'll see you around.");
}
```

We have the Msgs, very clean, then some raw C#, then a GiveItem call, that we have to assume means giving an item to the player, then a direct property access on the player, because there's no functions for variable access, and then we go back to clean functions and implicit calls to the player.

This is just one example I'm looking at right now, but there's more in our code and more will be added in the future. That's because we do have direct access to everything, and adding a duplicate function for _everything_ in NpcScript is not only annoying but bloats up the class unnecessarily.

We also have to think about the NPC, what if we want to do the same things we do with players for them? Do we add functions like NpcGiveItem and NpcPermVar? Do we use raw C#?

Further, we only get clean calls in NpcScript like this, but what about GeneralScript, ItemScript, etc? There we use raw C# when it comes to working with creature objects, because not every player gets their own instance of those. In one script you do `GiveKeyword("...")`, in the next you have to do `creature.Keywords.GiveKeyword("...")`.

What I'm proposing is moving most of those simplified functions that affect the creature, like `GiveKeyword("...")` to `Creature`. Every method that affects an object goes into the object, but on the first level, so you don't have to go down the properties.

``` csharp
SetLocation(...) // stays the same
Msg(...) // stays the same
GiveKeyword(...) -> Player.GiveKeyword(...)
TrainSkill(...) -> Player.TrainSkill(...)
```

This is still simple, easy to remember, and much more descriptive. I believe some _script_ functions can stay the same, like Msg, because they don't affect anything and are only used in that script, but for the others it might make sense to change our conventions.

One might now think "but then Creature gets bloated!", which isn't incorrect, but we're basically just moving bloat code from one class to another, but that will help clean up basically all scripts a little.

**Comment by xCryptic** [comment]
This sounds like a good idea. It'll keep things more organized and be a little more specific when only looking at the scripts.

**Comment by xCryptic** [comment]
gasp ![](https://cdn.discordapp.com/emojis/230157937752932364.png)

**Comment by exectails** [comment]
Though now that I'm copying those methods around I have to wonder if it would be so terrible if we had to do `Player.Skills.Something()`, `Player.Inventory.Something()`, etc. Many of the methods really just forward the call down one layer to the respective classes.

**Comment by exectails** [comment]
If you compare it it's really not all that terrible, even in a block.
```csharp
Player.Inventory.AddItem(new Item(...));
Player.Inventory.AddItem(new Item(...));
Player.Inventory.AddItem(new Item(...));

Player.AddItem(new Item(...));
Player.AddItem(new Item(...));
Player.AddItem(new Item(...));
```

**Comment by xCryptic** [comment]
Hmm.. it's whatever I guess. Nothing groundbreaking, it's just more specific. I don't mind either way ![](https://emotes.tastycat.org/emotes/misc/shrug.png)
