### ISSUE TITLE
Can't obtain "The fire-arrow"

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#327]
_Perform a critical finish on an enemy with an arrow while nearby a Campfire. Only works with a Bow equipped._

I tried this, but it doesn't appear to give me anything.

**Comment by exectails** [comment]
It's working just fine for me. Are you close enough to the Campfire? Did you see the fire effect on the arrow? Were you using a *bow* (not crossbow)? Or maybe you already have the title and didn't notice it?

**Comment by Pegwald** [comment]
I did use a short bow near a campfire and the arrow was lit. I could only lit it while using magnum shot, but that's how it's supposed to work or?

**Comment by exectails** [comment]
Meh, damn Short Bow, doesn't have a `/bow/` tag >_>
