### ISSUE TITLE
Wound penalty

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#337]
After dying and reviving at the closest statue of goddess, I noticed that I suddenly didn't have a health bar. It was entirely black, filled up with wounds (100%). Isn't the maximum amount of wounds  supposed to be 95% when you revive?

**Comment by exectails** [comment]
I don't know, is it? o.o

```csharp
case ReviveOptions.InCamp:
case ReviveOptions.StatueOfGoddess:
	// 25% life recovery and 10% additional injuries
	this.Injuries += this.LifeInjured * 0.10f;
	this.Life = this.LifeMax * 0.25f;
	break;
```

Right now we don't do that, and I couldn't find anything about it on the Wiki. Is that your personal experience?

**Comment by Pegwald** [comment]
Indeed, I was already 30% wounded, survived a 300+ dmg stomp, then died to another instant stomp. When I revived I had no health what-so-ever. xD

**Comment by exectails** [comment]
What I meant was, is the 95% thing your own experience on officials?^^ Because I couldn't find any info on it just now, after a quick search on the Wiki.

**Comment by Pegwald** [comment]
Yeah, it's pretty much what I have experienced myself. I really don't have any other sources of information

**Comment by xCryptic** [comment]
I've never seen wound at 100% either myself. You normally always have a little HP left, 5% would be a safe guess.

**Comment by exectails** [comment]
>I've never seen wound at 100% either myself

Wait, does this mean it's *generally* capped at 95%?

**Comment by xCryptic** [comment]
I would assume so. Have you ever seen wound at 100% when you played?

**Comment by exectails** [comment]
I don't remember ever being wounded that badly =<

**Comment by xCryptic** [comment]
3pro5me.

I haven't recently, but I still don't remember 100%. I mean, if you have a newbie character, it's easy to test.

**Comment by exectails** [comment]
Tested. You can get more than 95%, but when you revive at statue you'll always have 25% HP. That's because of "25% life recovery and 10% additional injuries", you will always get those 25%.
