### ISSUE TITLE
Pickaxe still usable at 0 Dura

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#338]
I'm not sure if this works on other tools too at the moment, but I'm pretty sure about the pickaxe is not supposed to be working at 0 durability.

**Comment by exectails** [comment]
While you're most likely right about this, have you tested it, or do you have a reference? (Just to be sure.)

**Comment by Pegwald** [comment]
To be really honest, I have been abusing this for a little while now - just until Edern could repair my pickaxe again ^^ ''

https://cdn.meme.am/instances/58923423.jpg
