### ISSUE TITLE
Splash damage bug

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#339]
_I did Rabbie normal today to check out the splash damage and stuff. Turns out I managed to find a bug here :)_

- It's possible to open a dungeon door before all the enemies are defeated. this happens if you strike an enemy twice with splash damage. It's like it dies twice and registers two individual deaths from two different mobs even though it is the same one. Sounds confusing, but I have some footage I can render and upload to show you what I really mean.

**Comment by Pegwald** [comment]
- Here's another splash damage bug. It pretty much knocks down B if A is being killed or knocked back. https://www.youtube.com/watch?v=h6GluudWL7k

**Comment by exectails** [comment]
I understand the first issue, and I can see the problem.

About the other issue, KB doesn't depend on A, B simply gets destabilized normally, with every hit, and eventually, just like A, it will get knocked back. Is this not how it's supposed to be?

**Comment by Pegwald** [comment]
I think we mixed our A nd B ^^''
Let's say the one being targeted is A now. B is the one taking the splash. Normally I could perform another two hits if A survived the first four ones, but it did not. B, however did survive, but still got knocked back. That's where I'm trying to get with this. Isn't it supposed to NOT be knocked back even if A does?

**Comment by exectails** [comment]
We didn't mix anything, that's exactly how I understood it^^ The question still is: *is* B supposed to get knocked back? *Does* its stability even go down?

**Comment by exectails** [comment]
I've confirmed that on Aura B won't get knocked back just because A was knocked back, which means that what happened in your video must've been a loss of stability.

https://youtu.be/5elHqytY14Q

What about the question of whether they lose stability from splash at all? Do you have any experience with that? I would expect them to, but it's been way to long for me remember.

**Comment by Pegwald** [comment]
I am pretty sure they are supposed to lose stability from splash, so right now I think this is functioning like it should.
