### ISSUE TITLE
is a friend of Deian description text is wrong

### ISSUE THREAD

**Issue by wezurii** [aura-project/aura#344]
Says, 'you and Trefor' when you get the friend of deian title in the desc box.

![mabinogi_2016_07_04_001](https://cloud.githubusercontent.com/assets/13336302/16566739/38cf74f6-41e5-11e6-9acd-42d1c0e6229d.jpg)

**Comment by xCryptic** [comment]
I'm pretty sure this is client sided. I'm surprised it was never fixed.

**Comment by wezurii** [comment]
lmao. thanks nexon

**Comment by exectails** [comment]
Yes, this is indeed client-sided, nothing we can do about it, unfortunately. Thanks for the report though.
