### ISSUE TITLE
Ranged attack movement disabled for crossbows

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#35]
https://youtu.be/jexILuVYTS0

I'm back digging up some ranged attack bugs and issues :)

**Comment by exectails** [comment]
Well, that's definitely a server side lock. You're supposed to be able to run with crossbows?

**Comment by Pegwald** [comment]
I thought so too, but I really don't know for sure. All I know is that it's still not working for me. I tried relaunching Aura frontend, but is there something else I need to do?

**Comment by exectails** [comment]
I've tried it after fixing it, it should work after you update and recompile. I *think* Frontend should handle that for you, but that tool was coded by @Xcelled, I don't know much about it.

**Comment by Xcelled** [comment]
Frontend should auto update. However, I don't know what the repo being deleted and then reposted would do. You can always try deleting the Aura folder where frontend stores the source. That would force a total refresh.

**Comment by Pegwald** [comment]
That did the trick. Thank you so much guys ^^
