### ISSUE TITLE
Dual login with same account

### ISSUE THREAD

**Issue by sdbezerra** [aura-project/aura#350]
I tried to logon on aura server with the same account in different computers, and the result:

![aura_dual_account](https://cloud.githubusercontent.com/assets/6790026/16647194/684e6e50-4404-11e6-99f2-fef6e3d00370.png)

**Comment by exectails** [comment]
Wow, we never added an already logged in check...? How did we forget this? Thanks for the report.

**Comment by exectails** [comment]
Weird. In the past there was a dialog when you were already logged in, wasn't there? It said something like "You're already logged in, wanna request logout?". What happens on NA now is that you get to the secondary password screen, but it acts like it's the first time, and tells you to enter a new secondary password. If you do, it shows a general error, saying that the server might be in maintenance. Somebody fucked with the double login code when they added the secondary password I guess =<
