### ISSUE TITLE
Counter Attack (Trefor)

### ISSUE THREAD

**Issue by RageNTonic** [aura-project/aura#351]
When getting the Counter attack from Trefor it doesn't seem to give you the skill after the explanation (this being when i used the skills keyword) though maybe its just me.

**Comment by exectails** [comment]
Huh, I could've sworn we had that o.o

**Comment by exectails** [comment]
Oh, and thanks for the report =)

**Comment by RageNTonic** [comment]
no problem if your looking for help anywhere else i have basic knowledge of C# , i would love to see G1 and onward finished

also things i found aside from that
-final hit wont end
-randomly when fighting my character would lock up mostly in dungeons, maybe it was because i was fighting with a maid, though i couldnt tell you exactly what causes it unfortunately
-when maid finishes boss they receive the quest item (this happened with the malcom's ring quest in particular) 
-krystal claims to be a restuant owner when asking about skills (lol)
-when colecting cobwebs sometimes they wouldnt despawn but say they did not exist
-when summoning bag dolls and talking to maids character crashes (though i imagine this is because they arnt in the game yet)
-banner imp has pitch black skin (probly textureless)
-succubus wont love me halp

**Comment by exectails** [comment]
Final Hit should end just fine, unless you're using the devCAT title.

While pets aren't technically part of G1, we should probably fix that they get quest items^^"

@xCryptic 
>-krystal claims to be a restuant owner when asking about skills (lol)

**Comment by exectails** [comment]
What exactly do you mean by
>my character would lock up
? You can't move? You can't do anything anymore? Are there any errors in the channel server console?

**Comment by RageNTonic** [comment]
other things around me could still function but you couldnt do anything like move, use your inventory, or interact with anything really. though i was still able to log out and log back in to fix the problem, so to me it seemed to be very player based, though i may be wrong

**Comment by RageNTonic** [comment]
ill try to recreate the problem and get back with more info when i can

**Comment by xCryptic** [comment]
>krystal claims to be a restuant owner when asking about skills (lol)

Oh. This will randomly happen with any keyword she doesn't know anything about. I'll fix that when I get around to dunby npcs (almost got the first batch ready).

I guess I should have checked all the phrases and default messages to make sure I have the right amount... (more tir fixes again, yay)
