### ISSUE TITLE
Pets acting as other players

### ISSUE THREAD

**Issue by RageNTonic** [aura-project/aura#354]
as weird as the title sound i comes down to pets having their own claim to items. so lets say they finish an enemy and they drop gold ya cant pick it up until the some time passes, like another player killed it. this is also ties into something i brought up earlier where pets can claim key items and making the quest unable to be finished.

**Comment by exectails** [comment]
I'll put this on the back burner, so I don't forget about it, but since we don't "*officially*" support pets yet, I don't want to mark it as a bug.

**Comment by exectails** [comment]
Actually... let's reference this on #18 and close it, as that's our Pet backlog issue.
