### ISSUE TITLE
Hunt Giant Spider

### ISSUE THREAD

**Issue by RageNTonic** [aura-project/aura#357]
completion of this quest yields swordsman shoes, useless to anyone playing a female character as they are gender locked.

**Comment by exectails** [comment]
I agree that it seems unfair, but that's what you're supposed to get.

http://wiki.mabinogiworld.com/index.php?title=Beginner_Quests_(Human_Uladh)&oldid=152349#Hunt_1_Giant_Spider

One of the nice things about Aura is that we can customize it to our liking though, you can easily change the reward for your server in the quest scripts =)

https://github.com/aura-project/aura/blob/master/system/scripts/quests/beginner_uladh/hunting/1000055_hunting_giant_spider.cs#L25
