### ISSUE TITLE
Oriental Town

### ISSUE THREAD

**Issue by YaibaToKen** [aura-project/aura#370]
Would like to point out that the current Oriental Town script warp point is invalid as shown in the screenshot as I clicked on the stone entrance:
![mabinogi_2016_07_27_001](https://cloud.githubusercontent.com/assets/9133736/17185686/e4acbd32-5429-11e6-9ce8-939d8c74e3fc.jpg)

**Comment by exectails** [comment]
Weird. Though this message doesn't mean that the warp point is invalid, but that the server can't find the prop you clicked on.

**Comment by YaibaToKen** [comment]
Anything I can do to help test if it's something I'm doing wrong? (Btw already cleared cache earlier, due to a problem with my own script and retried, only to get the same message)

**Comment by exectails** [comment]
Huh... well, at least it's working now.
