### ISSUE TITLE
Error on disconect

### ISSUE THREAD

**Issue by YaibaToKen** [aura-project/aura#371]
Sometimes, when I attempt to disconect from the server, the channel server throws this error :/

![image](https://cloud.githubusercontent.com/assets/9133736/17258657/d61fb25a-55bf-11e6-8be7-a24c85ca5c58.png)

**Comment by exectails** [comment]
You have an ErinnTime in a scripting variable somewhere, and since it's not marked as Serializable, the server can't handle it. I can't think of Aura using any ErinnTimes in scripts, do you have custom scripts? We can fix that though.

**Comment by YaibaToKen** [comment]
Cryptic's Halloween script apparently uses it.. Though I'm sort of working on replacing his script xD

**Comment by exectails** [comment]
Well, it's fixed now, ErinnTime should definitely be usable as scripting variable.
