### ISSUE TITLE
Friend failed to enter world

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#38]
A friend of mine is trying to enter the server I hosted, but can't enter the world. Logging in is ok, but once he clicks the "start" button he gets a message telling he failed to enter the world. Any idea of what could be wrong here?

**Comment by exectails** [comment]
You have to set the channel's IP to your public IP, since that's the IP that is sent to the clients, to tell them how to reach the channel server.

**Comment by Pegwald** [comment]
Ah, after deleting the Aura folder to reseet everything, I forgot to change that in the config. I already added the external ip to the target in the shortcut properties on the client.exe, but at least that explains it. Thx exec :)
