### ISSUE TITLE
Failed to run update

### ISSUE THREAD

**Issue by samuelhamilton** [aura-project/aura#393]
Couldn't find an issue similar to this. Just started trying to get this project to work today, getting an error in the login server "RunUpdate: Failed to run 'update_2015-09-16_1.sql': Duplicate column name 'status' "

My Msgr and Web servers are working fine, Channel Server closes because of an error "Table 'aura.guilds' doesn't exist", which I assume would be fixed if the updates ran properly.

**Comment by QewQew** [comment]
They all seem to run just fine for me.
Try dropping your schema and running it again (only run main.sql).

**Comment by samuelhamilton** [comment]
Alright, re-running the database worked, thanks.
