### ISSUE TITLE
Possibly a PTJ issue - Malcom

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#408]
I am able to complete Malcolm's delivery PTJ before 12:00 pm (which is report time according to wiki). All the down to before 10:00 am, am I able to report my quest if I get Malcolm's delivery quest. Is that normal?

**Comment by exectails** [comment]
According to @valdeza, some PTJ quests have different report times, which results in not all PTJs of one NPC ending at the same time. Malcolm is one of those with various report times.

**Comment by exectails** [comment]
I've just checked a few of Malcolm's PTJs, and they do indeed have varying report times, so I'll close this. Thanks for the report though, could just as well have been a bug =)

**Comment by Pegwald** [comment]
Thought there might be an excuse for this since I could never really remember this type of ptj ^^ ''
