### ISSUE TITLE
Can't obtain more PTJ from Malcolm

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#409]
_It's probably a bug this time :P_

I've had quite a few PTJs over at Malcolm, but I've gotten to a point were he just never wants to give me any more PTJs. He just tells me that he doesn't have any more work for me today - and I should come back tomorrow.

I suppose I this has something to do with going from basic jobs and over to intermidiate ones...

**Comment by exectails** [comment]
I was thinking "this sounds familiar...", and I was right^^ Thanks for the report^^
https://github.com/aura-project/aura/issues/341

I've fixed it for good this time.
