### ISSUE TITLE
Bugged PTJ - Manus

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#410]
a friend of mine told me she was unable to get a PTJ from Manus, telling her to come back tomorrow. She only did the PTJ once before, but I still feel this might be related to #409 . I have not checked this out myself yet.

**Comment by exectails** [comment]
Have you updated your server yet?

**Comment by Pegwald** [comment]
I did, the fix for Malcoms ptj worked, but this was discovered after the fix. I will check out the bug very soon. I'll give you an update on what happens.

**Comment by Pegwald** [comment]
I just went to Manus to do his PTJ. "Come back tomorrow."
That's all he told me. I haven't done any of his PTJ at all, so this is fishy.

**Comment by exectails** [comment]
Weird, I can get a job from him just fine. You're sure the PTJ hasn't been done by others yet? He only has 10 jobs per day after all. Or maybe you did another healer's PTJ already on that day? I'll keep my server running for a few minutes and try again on the next Erinn day, maybe there is a reset problem somehow.

**Comment by boilerplate5** [comment]
I believe there is a reset problem. Whenever I start the server up and try to do a PTJ they tell me it's already been done for the day.

**Comment by exectails** [comment]
I could do his job just fine two days in a row. Just to be 100% sure, you guys did update and recompile in the past 2 days, after this fix?
https://github.com/aura-project/aura/commit/4c785e7bb791b6d648df989cdea0999daa443824

**Comment by Pegwald** [comment]
I'm pretty sure we did, but I' can do it once more - just to be 110% sure ^^

**Comment by Pegwald** [comment]
Nothing changed. He still tells me to come back tomorrow

**Comment by boilerplate5** [comment]
I always recompile after updating. With larger updates I tend to just delete the cache too out of a "clean install" habit.

**Comment by exectails** [comment]
Something isn't right here... I have no issues whatsoever. Just did his job once on the second day, and could do it again on the third day, on two different chars.

Could you try to delete your cache folder and then start the server again?

*If* that doesn't work, could you test something? Could you go to the script, "system\scripts\quests\ptj\healer_manus.cs", and on line 50 change "private" to "public"? Like this:
```
public void OnErinnMidnightTick(ErinnTime time)
```

**Comment by Pegwald** [comment]
I can try that... Btw, Kristell won't give me any PTJ either, even though I've never done hers. "Today's work has been completed."

**Comment by exectails** [comment]
It's probably the same problem for all of them.

**Comment by Pegwald** [comment]
That did the trick, but it's weird because I recently deleted the entire cache just two days ago - before the other Malcolm ptj fix you added. I suppose I should do this more often whenever I update ^^''

**Comment by Pegwald** [comment]
- Hold on a bit!
I believe I found a new bug regarding manus's PTJ! ^^''

I collected 10 wool, but the quest didn't notice that since it was added in a wool pouch. Once I pulled out a stack it was alright, but when I reported the PTJ, I still had the 10 wool in my pouch.

**Comment by exectails** [comment]
That's *obviously* your fault, because wool pouches are G4 content =P /jk
You're right, the objective doesn't check for pouch items, gonna fix that.

So, deleting the cache solved it? You didn't do the "public" change?

**Comment by Pegwald** [comment]
Yeah, I only deleted the cache.

**Comment by Pegwald** [comment]
---NO HANG ON A BIT!!
I can't do anymore PTJ at Manus anymore TnT''

Should I try the other fix you suggested?

**Comment by exectails** [comment]
... so it worked once after restart, but not on the next (Erinn) day? Yea, test the other .__. (What is going on here o,o"")

**Comment by Pegwald** [comment]
The other npcs wouldn't give me any ptj either, so do I apply the same fix on them as well?

**Comment by exectails** [comment]
If that does the trick I'll update them all, but I don't understand why everything's working for me @_@

**Comment by Pegwald** [comment]
> I applied the change, restarted everything and nothing changed.

QnQ

**Comment by exectails** [comment]
Alright, we're gonna have to start debugging this, I'm out of ideas =/ Sorry about that, but I can't reproduce it at all.

Please go into the script I mentioned above, to line 168. It's empty and comes right before the CanDoPtj check.

```
168   
169   // Check if not done today and if there are jobs remaining
170   if (!npc.CanDoPtj(JobType, remaining))
```

On that empty line, paste the following, restart the server, and try to get a job. Then tell me what appeared in the channel console when you weren't able to get a job.

```
var record = npc.Player.Quests.GetPtjTrackRecord(JobType);
Log.Info("remaining: " + remaining);
Log.Info("type: " + JobType);
Log.Info("record type: " + record.Type);
Log.Info("record change: " + record.LastChange);
```

**Comment by Pegwald** [comment]
I waited a few days and I'm able to do the PTJ once more o-o''

This is very confusing, but I think after I applied the fix and restarted, I tried immediately to do the PTJ again - which didn't work. Now that I retried later it seems that it should be working so far. I'm going to run a few days doing some PTJ and see what happens. I'll let you know later what's going on

**Comment by Pegwald** [comment]
I've been running around in Dunbarton to do most of the available PTJ, but I can't seem to run into the issue anymore. I've done Manus, Nerys, Simon, Aeria, Eavan and Stewarts PTJs 4 times over without running into a single error.

**Comment by Pegwald** [comment]
Ok, 5th attempt and I suddenly ran into the error with Manus. I will add those lines to the script you mentioned earlier and see what I can pick up. What do I do next?

**Comment by exectails** [comment]
You should've added the lines before running around, then you would already be able to tell me what I wanted to know^^

> Then tell me what appeared in the channel console when you weren't able to get a job.

**Comment by Pegwald** [comment]
"2016-09-10 17:44 [Info] - remaining: 10
2016-09-10 17:44 [Info] - type: HealersHouse
2016-09-10 17:44 [Info] - record type: HealersHouse
2016-09-10 17:44 [Info] - record change: 9/10/2016 5:44:25 PM"

That's what I got now from Manus

**Comment by exectails** [comment]
Going by the time this was after you had just finished a PTJ for him?

**Comment by Pegwald** [comment]
No, this was just after I got the error - like right after I added those lines. Should I delete the cache again and do a couple of PTJ normally until I encounter the bug again?

**Comment by exectails** [comment]
Let me recap, you added those lines, restarted the server, logged in, talked to him, and you got the above in the console?

**Comment by Pegwald** [comment]
Yes, that's correct :)

**Comment by exectails** [comment]
Do you have the conf option "ptj_infinite_memory" set to yes?

**Comment by Pegwald** [comment]
yes o-o

**Comment by exectails** [comment]
Well, that's the error. Give me a minute to understand this code I wrote years ago and I'll fix it =<

**Comment by exectails** [comment]
Alright, you can give it a try.

**Comment by Pegwald** [comment]
So far it's looking good. I didn't delete the cache and manus has changed his attitude. I can finally work for him again :)

**Comment by exectails** [comment]
Sounds promising, thanks for helping me fix it.

**Comment by Pegwald** [comment]
thanks for fixing it ^^
