### ISSUE TITLE
Multiple Characters + Bank Tab "Dupe"

### ISSUE THREAD

**Issue by ldzbrown** [aura-project/aura#417]
I hope I'm doing this right.

There's an issue with the way characters can access other character bank tabs.

If you store items into the bank on character A, then log onto Character B and withdraw the items from A's bank tab. Upon logging out and back in again onto character B, the items from character A will reappear for withdrawing again.

It sounds like a saving issue or something but, I could be wrong.

**Comment by QewQew** [comment]
The issue stems from the fact that SaveCharacterItems does not delete items belonging to other creatures, only the one that is being saved, thus the items from other bank tabs persist in the database.

**Comment by exectails** [comment]
Thanks for the report. Yes, this is indeed a saving issue... and it's surprisingly hard to hot-fix. We have to properly load and save all bank items on login/logout. (As we should've done from the beginning <_>)

I've temporarily disabled the ability to access other character's tabs and will look into fixing the problem later.
