### ISSUE TITLE
Same conditions don't stack

### ISSUE THREAD

**Issue by QewQew** [aura-project/aura#421]
Say you had two sources that give you Hurry condition (e.g. title and >speed command), the effects won't stack. Instead, the last one used would take effect.

**Comment by exectails** [comment]
You're right, but then the question is if it *should* stack. Does the Hurry condition stack on officials? Do we even have multiple official ways to get the Hurry condition? Please say no, because if it does we might have a problem, the condition system is not designed for that xD"

**Comment by QewQew** [comment]
I'm not sure how many ways there are to get the hurry condition, but I know that there is a main title that gives +1% Speed (Outlaw Hunter), and you can tack on one of the many option titles that do, too.

**Comment by boilerplate5** [comment]
"The Busy" title also gives +1% speed. Then there's also the Falias treasure "Wave Sweeper".

**Comment by QewQew** [comment]
Well, after obtaining two titles that give a speed bonus on official, it seems titles do not stack, so others wouldn't stack with it, too.

**Comment by exectails** [comment]
Praise Morrighan, hallelujah!
