### ISSUE TITLE
G1 Typos (and a couple issues)

### ISSUE THREAD

**Issue by boilerplate5** [aura-project/aura#422]
G1 is rock solid from start to finish, no bugs, crashes, glitches, etc. Just some typos and other things listed here that are probably going to be dealt with at some point in the future irregardless of the mention.

1.	Typo in one of Tarlach’s dialogues after using the Paradise keyword. Believe the word was ‘Barrios’ instead of ‘Barriers.’
2.	Typo in Goro’s dialogue “Just what I’d **though**”
3.	Typo in Goro’s dialogue “Been a while since I **cam** across”
4.	Typo in Tarlach’s dialogue “I **can’** be sure”
5.	Typo in Tarlach’s dialogue “Tarlach **listen’s idently**”
6.	Typo in Duncan’s dialogue “**Gmm**…  you’re right”
7.	Typo in Tarlach’s dialogue “Sided with the **Formors**”
8.	Typo in Tarlach’s dialogue “Just what I’d **tought**”
9.	Typo in Tarlach’s dialogue “after **losign** some item”
10.	Kristell should have some dialogue when using “Morrighan’s Revenge” keyword at her.
11.	Typo in Kristell’s dialogue “**May Aeira** knows something about this”
12.	Typo in Aeira’s dialogue “It says that she once ‘the book of revenge”
13.	Typo in Aeira’s dialogue “It’s turning to **tbe** a lot harder”
14.	Typo in Lassar’s dialogue “not too long ago while **excavatin** the site”
15.	Typo in Duncan’s dialogue “please let **my** see it”
16.	Typo in Duncan’s dialogue “a lot more serious than I’d **though**”
17.	Typo in Duncan’s dialogue “commanded by an evil **gold**”
18.	Typo in Duncan’s dialogue “the **personal** who borrowed it”
19.	Typos in Bryce’s dialogue “when this **happenes**” and “either **on** of those things”

20.	The Dark Lord is, according to the wiki, immune to Magic & Melee, meaning only Mari / A bow user can hurt him.

21.	Typo in Tarlach’s dialogue “No **sigh** of Mari and Ruiairi”
22.	Typo in Tarlach’s dialogue “hypocrisy from the **Godess**”
23.	Tarlach should have some dialogue when using the “Goddess’ Request” keyword at him.
24.	Typos in Duncan’s dialogue, “just as I **though**” and “have the **slighted** clue”
25.	Typo in Duncan’s dialogue “needed as **on** ingredient”
26.	Typo in Duncan’s dialogue “one of the **Tree** Missing Warriors”
27.	Tarlach should have some dialogue when using the “How to Reach Tir Na Nog” keyword at him.
28.	Typos in Duncan’s dialogue “wrapped tightly in a **blanked**” , “inside the **blanked**”, “Mari becomes **and** adult”, “what the **leter** said”, “she’ll **attack** her memories to this item”

29.	In the final dungeon, there was only 1 hellhound on floor 1 when, according to the wiki, there are 3.

**Comment by exectails** [comment]
Right... I did notice those non-typo issues, but in the current data we get from the client, this is how it is. I assume the first Dark Lord had Heavy Stander and Mana Deflector in the original, but not after the G12 update, since he didn't have them in any video I saw. Same for the Hellhound(s). We need feature checks in the data files to fix this.

**Comment by exectails** [comment]
>Tarlach listen’s idently

This was actually an official typo, I thought maybe I just don't know the word xD" I see it's been fixed later.

>Kristell should have some dialogue when using “Morrighan’s Revenge” keyword at her.

All Uladh NPCs have something to say about every one of those keywords, problem is we don't know what =/

**Comment by boilerplate5** [comment]
Welp, that's unfortunate =/

**Comment by exectails** [comment]
Hm... I just gave Dark Lord HS and MD, if he really did have those on "Level 3", where he would be invulnerable to the attacks, I can understand why they were removed. It's impossible to fight him without ranged. Does anyone remember if that's how it was supposed to be?

**Comment by YaibaToKen** [comment]
Afaik, when i first did it, you used the lil girl when soloing because of that. Going by memory, the reliance on a party was due to her lack of health leading to the need for someone to tank and take on the aggro from the mobs.

**Comment by exectails** [comment]
Yea, that's pretty much what the Wiki said as well. I just wonder if he actually had HS, or if he was immune some other way. HS makes it even harder I think, because you can't stun him with normal attacks.

**Comment by exectails** [comment]
I couldn't find a video where he actually pinged, so I'll assume it's more of a natural invulnerability. Having a monster with R1 HS and MD so early in G1 would be a little hard anyway imo, even for classic Mabi.

**Comment by YaibaToKen** [comment]
Leave in the option for anyone with slight masochistic tendencies... err I mean looking for a challenge?
