### ISSUE TITLE
Wing of a Goddess bugs

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#424]
I got two wings of a goddess from fighting some Gorgons, so I tried using them to take me and my other party member to Tir. Here's what happened:

- Both wings were consumed for one use.
- I was transported to Tir alone.

**Comment by exectails** [comment]
Oh, I forgot to warp party members. What perplexes me however is that you're saying both wings were consumed o.o

**Comment by exectails** [comment]
Ahhh, nvm, found the bug. I didn't know there were wings that could stack, the skill handler simply removed the whole stack instead of decrementing it. Thanks for the report~

**Comment by exectails** [comment]
About the party warp, does it warp *everybody* in the same region? Or is there a range in which it works?

**Comment by Pegwald** [comment]
hmm, good question. I have no idea, actually

**Comment by exectails** [comment]
I'll make it the whole region for now.

**Comment by exectails** [comment]
Although... \*spam* being able to warp your whole party while it's scattered across all of Rano seems excessive. Maybe better use visual range?

**Comment by Pegwald** [comment]
Yeah, that sounds like a better idea ^^
