### ISSUE TITLE
Broken Cutscene in Alby Dungeon

### ISSUE THREAD

**Issue by xeroplz** [aura-project/aura#43]
When with friends, I did Alby dungeon in a party and once we opened the door, the cutscene played, but did not advance; the screen stayed black. I then had to force log, as pressing Esc to end the cutscene didn't work. At the moment I don't have any logs of the issue, but I know you wanted me to open an issue anyway.

I also don't know if this is an issue with any other dungeons or cutscenes.

**Comment by exectails** [comment]
So it stayed black after the cutscene? Could be an error during the finish callback, where the client notifies the server it's done with the cutscene. I did change something in that code while working on parties.

Does anyone have a log of this bug? I would expect an error/exception in the log when it happened. Remember that all logs are archived in `[Aura folder]/logs/archive`, if you experienced this in the past and feel like doing some digging.

**Comment by exectails** [comment]
Does anybody who has experienced this have more information? Does it only happen in parties, does it happen only with cutscenes, did you notice any errors?

**Comment by Xcelled** [comment]
Tried several runs solo and in parties. CNR.

**Comment by exectails** [comment]
Did this happen again to anyone?

**Comment by xeroplz** [comment]
I can't reproduce it again- it hasn't happened fo me again since then, and I haven't had many people on my server for a while to test it with a party again. It definitely doesn't happen solo, so i guess it has to be tested with parties.

**Comment by exectails** [comment]
Earlier I found a bug where you wouldn't be able to finish a cutscene if the creature's cutscene was nulled during watching somehow. That might've been what happened here...

>xeroplz 16:30
aura-project/aura@ba8b209
do you think this might have been what happened in that bug report i opened ages ago

>exectails 16:32
hm... interesting theory
I don't know why there would've been a cutscene inside a cutscene though
or
maybe the cutscene was set null... somehow...
yea, that's very possible

**Comment by exectails** [comment]
I'll close this for now, as it apparently hasn't happened again, and might've been related to a bug that has been fixed since. Should anyone encounter it again, we can reopen this issue.

**Comment by exectails** [comment]
Reopening it, since someone did experience it again.

**Comment by exectails** [comment]
Nvm, it's a new issue.
