### ISSUE TITLE
Max and Min damage on ranged attacks

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#439]
_I'm just curious about this since some modifiers seems to be improving ranged attack meanwhile some don't._

Upgrading ranged weapons with Min/Max damage seems to be working normally, but enchants on the other hand doesn't seem to make any improvement. I've tried equipping enchanted gear* that increases min and max damage significantly, but shows no improvement whatsoever on ranged abilities. Why are those damage enchants melee only?

_*=Fox, Fox Hunter's, Victorious Enchants_

**Comment by exectails** [comment]
Basically because I didn't know they affected ranged damage^^ Do they?

**Comment by Pegwald** [comment]
Well, I thought it would since upgrading max damage on a crossbow increases max damage, so why would a max damage enchant do it? ^^ ''

**Comment by Pegwald** [comment]
It's worth mentioning some enchants like "Fancy" are enchants for bows and crossbows that increase max damage by 8 (if ranged attack is over rank B).

**Comment by exectails** [comment]
You're right, it would make little sense to make it depend on Ranged if it didn't benefit it. There's also no other ranged attack bonus that I'm aware of. I'll change it. Thanks.
