### ISSUE TITLE
Mimic aggroes while being dead

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#442]
How to reproduce:
windmill mimics, run to their bodys and alt+click them. I 1-shotted the mimics so this might have something to do with it?

So yeah... they "!!" you while being dead on the floor...

**Comment by exectails** [comment]
We might be missing a dead check in the touch mimic handler, so Aggro is called even though it shouldn't be.

**Comment by exectails** [comment]
I actually can't reproduce it, but the TouchMimic handler still has several flaws. I'll fix those, and that will also fix the problem.
