### ISSUE TITLE
Minor Issue enchanted items on floor wrong color

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#443]
Last time I checked, an enchanted item dropped in a dungeon etc has a blue label/name when you press Alt.

On aura its white.

Ye, thats all...

**Comment by exectails** [comment]
It would be news to me that we have any kind of control over an item name's color =<

**Comment by Sairii** [comment]
ok throwing on the vpn ;D

**Comment by exectails** [comment]
Fixed in 8589ba64e035d3679050e142f6a38c4f4fa80783.
