### ISSUE TITLE
G1 - Goro's Ring

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#445]
At this part when you use the keyword "Priest's token", you get the "Goro's ring" quest, but no dungeon pass for Ciar. The keyword disappears and you can't really talk to Goro again to get the pass. I tried running a normal Ciar, but I didn't get any ring there either. 

Here's what the wiki tells about this part: _The "Find Goro's Ring" quest and "Goro's Ciar Fomor Pass" will be received by owl, once the player leaves Alby Dungeon._

http://wiki.mabinogiworld.com/view/Generation_1:_Advent_of_the_Goddess_(Pre-Genesis)#Goro.27s_Ring

**Comment by exectails** [comment]
Thanks for the report, but it's actually working as intended. The Pre-Genesis G1 page you're referencing describes a newer version of G1 than the one we have implemented, with changes that made G1 through G3 easier after the G12 update.

As you can see in older G1 pages, you're supposed to get his ring from Ciar *Basic*, and you have to find a pass to get there yourself.

http://wiki.mabinogiworld.com/index.php?title=Generation_1:_Advent_of_the_Goddess&oldid=61442#Goro.27s_Ring

>The Ciar Basic Pass must be obtained from monsters or a reward room chest from Ciar Dungeon.

**Comment by exectails** [comment]
Maybe we should make a wiki for Aura based on the World wiki ôo

**Comment by majorcyto** [comment]
Well since quite a bit of things are different from the current gen, it might be a good idea. But who even has the time to document  all the differences anyways. xD and eventually (oneeee dayyy) it will be the same as retail anyways i guess.

**Comment by exectails** [comment]
Well, since Aura is completely modular with its features, it will never truly be on any one level. Even if Aura supports everything up to G20, some users can and certainly will use the classic G1. What would be ideal, is a Wiki that can adjust to feature settings, so the pages on the Wiki reflect the choices the user made.

Actually... that Wiki could be part of our web server o.o!

**Comment by majorcyto** [comment]
Yay another use for the web server, you were trying to find something practical for it aside from the obvious choices like a guild message board, so that would be a good one. :P

And true, i forget sometimes that you have been adding these things with a switch lol.

**Comment by exectails** [comment]
I like this idea lot, we just have to come with a good system. I think it would be nice if the wiki stored the pages as files, so everybody can easily edit them and make pull requests, without requiring special tools or database dumps. It would also allow for reading all pages from our repository, or anywhere else.

We would also have to decide on a markup language. Wikitext? Markdown? HTML would always be valid as well, but a simpler one will make for more pleasant editing.

**Comment by exectails** [comment]
I've created a wiki prototype on the Swebs branch (#430). It uses Markdown files that are parsed automatically, so they can easily be edited and viewed with any standard editor. And it's nice how GitHub renders the pages as well^^

https://github.com/aura-project/aura/tree/add-swebs/system/web/wiki

I thought about generating the menu automatically from the files, but we might not want certain files to appear in the main menu, so it's better to do it manually.

I have yet to add the "features feature", but my idea here is to use CSS to filter the relevant information. For example, on the Moon Gate page you would want to differentiate between old and new gate systems. That might look like this:
```
<div data-feature="!MoonTunnel">Moon Gates are open at night, they warp to one location, ...</div>
<div data-feature="MoonTunnel">Moon Gates are always open, you can warp to any previously visited gate, ...</div>
```

A search function might also be interesting for the future.
