### ISSUE TITLE
Suggest Moving MathDungeon in Features.txt from G2 to G1

### ISSUE THREAD

**Issue by Kiduni** [aura-project/aura#448]
After testing mainstream quest I found that Math Dungeon's Sealed stone is not breakable without commenting out the lock in the sealedstones.cs. This prevents from finishing the required G1 "Clear Math Dungeon" quest.  When moving { name: "MathDungeon", enabled: true }, up to G1 in features.txt stone becomes breakable.

**Comment by exectails** [comment]
Weird, we thought Math was G2, but I didn't think about it being required for G1. So it actually *can't* be G2 =| Thanks for the report.

**Comment by exectails** [comment]
Fixed in 16c2bbf89339096fea401593f7e5767c50d14234.
