### ISSUE TITLE
How to make a break a GM character.

### ISSUE THREAD

**Issue by spo702** [aura-project/aura#451]
So apparently logging out with when you character has a Scythe that Reaps Darkness on their back will completely break them, as in makes it appear as though their entire inventory was deleted with exception to whatever is currently equipped, and then makes the character completely immobile too, Also makes it impossible for you to drop the scythe. Managed to save the character by using the gm >die command, summoning a pet, plopping the scythe on the pet, and then rebirthing. but for starters that made the pet break, where every time I summoned it, it was in the knocked out state with zs over its head, yet not actually knocked out.  However Rebirthing with the scythe still in your inventory just makes you get stuck a few feet away from Nao completly unable to move to talk to her, and since your in the event your not allowed to logout, and apparently GMs cant use commands in the Rebirth event. so I can't use that inventory clear command or any of the others.

**Comment by Sairii** [comment]
The Scythe has no maxUpgrades in the db but I doubt that it has something to do with it.
Cannot really look at it atm caus im at work.

Not entirely sure what happens there....
Anyways... you can go into your DB and delete the Item manually from your character / pet.
You have to be on charselect screen or entirely logged out for that.

**Comment by spo702** [comment]
I have no idea how to edit a single characters inventory from the DB, I'm not even sure which DB your talking about

**Comment by Sairii** [comment]
Your SQL Database.
Open your SQL Database with MySQL Workbench or something.
Connect to your Database, Open the Schema 'Aura', open the table items and then search for the one causing problems and delete it.

**Comment by QewQew** [comment]
http://mabinogi.x10.mx/itemdb/?action=view&item=41237

According to this, it can't be upgraded.

**Comment by Sairii** [comment]
still wierd.... every other (that I tested) no upgrade weapon works fine without maxUpgrades...
This one doesnt?? I dont understand it.

maxUpgrades: 0 <- doesnt work, everything glitches
maxUpgrades: 1-5 <- does work, I DONT GET IT

@exectails please enlighten me

**Comment by spo702** [comment]
As someone with no experience with SQL or SQL Workbench, I managed to connect to the Aura DB and found the Tables. I can see them but have no idea what to do from there.

**Comment by Sairii** [comment]
1. Right click the 'creatures' table and select 'select rows' (only if it is a specific character)
2. Look for the character you want to delete an Item from and remember the creatureId
3. Right click the 'items' table and select 'select rows'
4. Now either look for your creatureId and delete the specific item OR sort by ItemId and delete all you find (thus deleting them from every creature that has the item)

Also as mentioned above the item does work without glitching if you do a little edit in the items.txt

**Comment by spo702** [comment]
OH It did fix it, I just forgot to restart the servers after editing the item. Woops, but thanks for the explanation on how to change specific parts of the DB

**Comment by Sairii** [comment]
Well yes... restart the server or '>reloaddata'

**Comment by exectails** [comment]
@Sairii It doesn't cause any problems if you set maxUpgrades in the item data to anything >0...?

**Comment by exectails** [comment]
Well, this problem happens when an item has a different item info structure than others. Like spirit weapons or guild robes. They have additional values, which when we don't send them confuses the client. This is to be expected.

Unfortunately we can't fix this without a log of the item. I'll try to find one on NA, see if I can get a log.

**Comment by DennouNeko** [comment]
Hm... Can't remember well, but there's a chance I have one. Gonna check it once I get home if you won't find it, @exectails.

**Comment by exectails** [comment]
Thanks, @DennouNeko. Actually found one in housing on Alexina. For some reason that scythe has an additional int after the quest id... no idea why =< But at least it's working now.
