### ISSUE TITLE
Cannot learn Campfire Skill from Quest

### ISSUE THREAD

**Issue by BentonNCo** [aura-project/aura#452]
I got the Quest to learn campfire from Piaras, and after talking with him I had to talk with Deian, but when I talk to him it only says> (Missing Dialog: Another Campfire Explanation).

And now I am stuck in that Quest, without being able to complete it or give up.

**Comment by hketp** [comment]
The skill book is in your bag.

**Comment by exectails** [comment]
I have improved the missing dialog a little, to clarify that you have to use the skill to finish the quest. You got the book to learn the skill and some firewood when you first talked to Deian, you're then supposed to make your first Campfire to clear the second quest objective.
