### ISSUE TITLE
Sound Issue

### ISSUE THREAD

**Issue by spo702** [aura-project/aura#453]
Is there a particular reason why 99% of the time when I lower the client (alt-tabing to the wiki or something) the sound breaks when I bring it back up? The only thing I've found that fixes this without relaunching the client is alt-tabing repeatedly until I get that rare instance where the sound starts up again.

**Comment by Sairii** [comment]
1. I have never encountered this myself
2. Pretty sure this is a client thing.

**Comment by spo702** [comment]
It doesn't happen with the official server though.

**Comment by exectails** [comment]
There are certain client glitches that seem to happen more often with Aura than officials, but so far we haven't seen one that happens *exclusively* here. For example, if you don't wait a moment between arriving at the character selection and clicking start, the client tends to crash with Aura, but *usually* not on officials. That doesn't mean it's not happening at all though.

No packets are exchanged on toggling the client window, so there's really nothing (missing) in Aura that could be causing this. It is indeed a client problem, though we don't know why it happens more frequently on Aura.

Personally I haven't experienced it yet either, but I always run in window mode, that might be why.

**Comment by Sairii** [comment]
Actually one problem disappeared for me.
The crash on to fast logging in and joining the world.
Haven't had that since I came back.

**Comment by exectails** [comment]
It hasn't happened to me either recently, but I'm so used to waiting a moment after all this time that I probably wouldn't run into it accidentally anymore anyway^^
