### ISSUE TITLE
Visual chat can upload, but can not show in game

### ISSUE THREAD

**Issue by sht547** [aura-project/aura#454]
Visual chat can upload, but can not show in game

**Comment by exectails** [comment]
Have you enabled the feature in both the client and Aura?

https://github.com/aura-project/aura/wiki/Web-server#visual-chat
https://github.com/aura-project/aura/blob/master/system/web/upload_visualchat.cs#L9

**Comment by sht547** [comment]
I can see the Visual chat UI in the client , and it can upload the png files in the EMU , but  can not show the picture in game

**Comment by sht547** [comment]
My features.xml
    <Feature _Name="815bf781" Default="G10S2" Enable="" Disable="" />
    <Feature _Name="8a124e66" Default="G0S0" Enable="" Disable="" />
    <Feature _Name="4fe181fa" Default="G10S2EX" Enable="" Disable="" />
    <Feature _Name="aaa4fd9b" Default="" Enable="G10S2EX@China, G0S0@Europe, G10S2EX@Japan,

**Comment by sht547** [comment]
My 	features.txt

	// Season 2
	{ name: "G10S2", enabled: true, children: [
		{ name: "VisualChat", enabled: true },
	]},

**Comment by sht547** [comment]
And my client version is 235

**Comment by exectails** [comment]
gfVisualChat is 8a124e66, to enable it, use this:
```
<Feature _Name="8a124e66" _RealName="gfVisualChat" Default="G0S0" Enable="" Disable="" />
```

**Comment by sht547** [comment]
yes I enable it   , But it not work

**Comment by sht547** [comment]
<Feature _Name="815bf781" Default="G10S2" Enable="" Disable="" />
    <Feature _Name="8a124e66" Default="G0S0" Enable="" Disable="" />
    <Feature _Name="4fe181fa" Default="G10S2EX" Enable="" Disable="" />
    <Feature _Name="aaa4fd9b" Default="" Enable="G10S2EX@China, G0S0@Europe, G10S2EX@Japan,

**Comment by sht547** [comment]
<Feature _Name="8a124e66" Default="G0S0" Enable="" Disable="" />

**Comment by exectails** [comment]
How did you enable VisualChat in Aura?

**Comment by sht547** [comment]
I can see the VisualChat iso in the game,  I can Drawing and upload , but I can not see the VisualChat  chat bubble

**Comment by exectails** [comment]
Please answer my question^^

**Comment by sht547** [comment]
// Season 2
{ name: "G10S2", enabled: true, children: [
    { name: "VisualChat", enabled: true },
]},  
is it not enable?

**Comment by exectails** [comment]
>Also make sure the feature in Aura is not inside a parent feature that's disabled.
https://github.com/aura-project/aura/wiki/Feature-Settings

**Comment by sht547** [comment]
// Season 2
{ name: "G10S2", enabled: true, children: [
{ name: "VisualChat", enabled: true },
]},
Is this enabled?

**Comment by exectails** [comment]
Only if G10 is enabled. Look at the end of the file to see how to enable features outside of their normal generation structures.

**Comment by sht547** [comment]
Thanks

**Comment by exectails** [comment]
Closing under the assumption that the issue was resolved.
