### ISSUE TITLE
Soft Lock Logout

### ISSUE THREAD

**Issue by RashataanVuul** [aura-project/aura#470]
So when I host a server, when I log in and log out, I logout fine but when my friend joins and he logs into his character and try to log out, his character infinitely does the "saving character" or whatever and he gets stuck. This errors occurs:

`[Unimplemented] - PacketHandlerManager: Handler for 'AC1F', '?'.
[Info] - Connection lost from '46.49.117.52:37366'.
[Error] - Unable to send packet to '46.49.117.52:37366'. (Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.)`

**Comment by QewQew** [comment]
Aaand what exactly was the problem? Would help others out who might have this problem in the future.

**Comment by exectails** [comment]
AC1F was the unknown disconnect packet before the last update, so I assume he had updated Aura, but not his client.
