### ISSUE TITLE
Trapped in void after the cutscene in RP Quest - Rabbie Dungeon

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#471]
Only the party leader was able to move, but the two remaining party members are trapped in this black void, unable to move.

https://gyazo.com/110d41eeff208eab67007630dfcf2fab

This is still in the dungeon lobby, btw.

**Comment by exectails** [comment]
Could you elaborate on what happened? You three were on the altar, the party leader dropped the item, you saw the cutscene, and afterwards two of you were outside the normal map? Did you change any scripts, maybe activating the RP characters?

**Comment by exectails** [comment]
Oh, now I see what you mean... just tested it. Wth o,o

**Comment by exectails** [comment]
Thanks for the report, I was able to fix it. It was caused by a recent change in how the cutscenes work, which was necessary for the RP feature.
