### ISSUE TITLE
PTJ Difficulties

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#473]
I have been doing a lot of Walter's PTJs to unlock intermediate and advanced level difficulty PTJs, but it seems after 46 completed jobs (2 failed) I am still on basic level - BUT! when it comes to delivery quests I have gotten the intermediate ones several times over and over.

In my logic I should be at intermediate level now, but the braid quests still tells me to make 2 braids instead of 3 (which is int level). What level am I really at? o-o

https://gyazo.com/0af6d556e0337c505a2ed711af5f4f59

info source: http://wiki.mabinogiworld.com/view/Walter#Part-time_Jobs

**Comment by exectails** [comment]
From the World Wiki:
>- Basic - Complete 0 ~ 50 times successfully.
- Intermediate Complete 50.1 ~ 100 times successfully with a minimum of 70% success rate.
- Advanced Complete ≥ 100.1 times successfully with a minimum of 92% success rate.

So you're just short of reaching Int. You mentioned you got Int delivery quests already, but some of them overlap and exist on Basic as well. Are you sure you got ones only available on Int?

**Comment by Pegwald** [comment]
pretty sure I've had every delivery PTJ on int level

**Comment by Pegwald** [comment]
That might also be a reason for why those crafting quests feel so rare. I've gotten 3 jobs were I have to make braids ^^''

**Comment by exectails** [comment]
Just to make sure, we're talking about the following Int level quests?

>Receive Candlestick from Nerys
Deliver Candlestick to Stewart

and

>Pick up Lump of Cheese from Glenis
Deliver to Aeira

The other Aeira and the Manus delivery quests are available on all difficulties.

**Comment by Pegwald** [comment]
Yep, I've mostly been delivering cheese and candlesticks. I get those two a lot

**Comment by exectails** [comment]
Ah, you're right. I see the problem, the levels are incorrect, they were declared Basic.

**Comment by exectails** [comment]
You should only get those two on Int and Adv now, thanks for the report.
