### ISSUE TITLE
Fished items can be picked up by other players

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#476]
Whenever your inventory is full and you start dropping all of those fished items, other players are able to pick them up without restriction.

**Comment by Pegwald** [comment]
Unless that player I just picked up those items from dropped those items themselves...

**Comment by exectails** [comment]
The code looks good, unless I'm missing something, the item should be protected. I'll test it.

**Comment by exectails** [comment]
I think I see what's going on here, the loot protection is *20 seconds*. So unless the fisher quickly picks them up, it's to be expected that they become loot-able. Now the question is whether that's official. Do "overflow items" on officials get a longer loot protection?

**Comment by exectails** [comment]
Actually... is 20 seconds even correct in general...? Seems kinda low.

**Comment by Pegwald** [comment]
Yeah, the loot protection on fishing is supposed to be infinite until the item despawns. Btw, I can confirm the fisher just dropped the stuff just before I came by and picked up the stuff xD

**Comment by exectails** [comment]
Alright, I'll change that then. Thanks for the report.
