### ISSUE TITLE
Status not updating in friends list/ private chat

### ISSUE THREAD

**Issue by Fuhhue** [aura-project/aura#48]
If you change your friends list status it does not show the new status to a friend, it will still show them the old status. If you need me to explain more just comment asking and i will try to provide more detail

**Comment by exectails** [comment]
>If you need me to explain more just comment asking and i will try to provide more detail

That would be good, I'm not sure what you mean. We're talking about the Busy/Online/Offline/etc. thing in the options, right? I've just tried it, seems to be working for me.

**Comment by Fuhhue** [comment]
No i mean like the mood status

**Comment by exectails** [comment]
Ah. OH! Of course, I'm only sending and update when the status changes, but not if the nickname changes. I'll look into that tomorrow (in a few hours).

**Comment by exectails** [comment]
Hm, are you sure it's supposed to live update the nickname? I don't see anything like that my logs. It seems to only update when you change your status.

**Comment by Fuhhue** [comment]
http://puu.sh/kuZtH/9cf8040998.mp4
http://i.imgur.com/pIfzAUl.png

**Comment by exectails** [comment]
Well, I can't find this update in my logs, but it does make sense, and apparently it does happen on official, so I added it.
