### ISSUE TITLE
Guild Home Page Unavailable

### ISSUE THREAD

**Issue by ArieJoJo** [aura-project/aura#484]
I've made a guild to test it's functionality. Everything seems fine, but I can't expand the guild because the guild page doesn't load. It is probably redirecting to Nexon's guild page similar to the cash shop.

**Comment by QewQew** [comment]
Please read: https://github.com/aura-project/aura/wiki/Web-server#guild-management

**Comment by exectails** [comment]
I'm gonna close this, since it was answered. Should you have trouble modifying your client accordingly, there have been threads on the forum about enabling hotkey saving which might help you: http://aura-project.org/forum/topic/103-how-do-i-save-everyones-hotkay-bars-on-my-server/
