### ISSUE TITLE
Pet was an incorrect color after creation

### ISSUE THREAD

**Issue by eotetb** [aura-project/aura#486]
I used a Yellow Jindo card from the revamped points shop, and the pet was black instead of the yellow color its supposed to be after it was created. I never had an issue with pet colors before that update.

http://image.prntscr.com/image/836853362ac540eebe58f04a85ee1196.png

**Comment by exectails** [comment]
Were there any errors in the login server log file?

**Comment by exectails** [comment]
Just tested it, and I didn't have any issues. Bought the card, created the Jindo:
![ss 2016-11-26 at 10 17 14](https://cloud.githubusercontent.com/assets/5593920/20639356/8552a872-b3c1-11e6-9112-4bead1833497.jpg)

Did modify Aura by any chance? The colors for the pets are specified in the pets db:
```
{ raceId: 200001, name: "Yellow Jindo", timeLimit: 116, [...], color1: 0x00B08048, color3: 0x00A0A0A0 },
```

**Comment by eotetb** [comment]
I have not modified the race in any way. I'll try making a few more and see what happens. It seemed really odd to me. I didn't see any warnings, errors, or exceptions in the console or in my logs.

**Comment by eotetb** [comment]
I was able to recreate the bug. If you select a pet that is color select-able before choosing the Jindo (or any other pet), it will use the same color(s) as the color select-able pet. 
![](http://image.prntscr.com/image/2dd0e1cff5a6438490e00e0038cc8ac3.png)

Its a bug, but its kind of cool to be able to change the color of pets that aren't normally color select-able. I just happened upon it because I was just looking through all the pets before I made mine.

**Comment by exectails** [comment]
Thanks for figuring it out, fascinating bug. While I wasn't able to reproduce it, I have a good idea how it might happen, thanks to the client sending nonsense data, and I've tried to fix it. It would be good if you could try to reproduce it again after updating, to confirm that it's fixed.

**Comment by eotetb** [comment]
Just confirming that the issue is indeed fixed.

**Comment by exectails** [comment]
Thanks. Maybe we should look into how to make all pets color select-able^^ Won't work without client modifications, but it would certainly be interesting.
