### ISSUE TITLE
Freezing on party leader switch

### ISSUE THREAD

**Issue by Raraldor** [aura-project/aura#488]
So me and two other people were doing party quests in Rabbie basic, when I noticed I had a nearly completed red skeleton party quest, I asked them to switch the leader to me and attempted to switch the quest. Once I tried to switch the quest, the quest did not switch and I was frozen in place, unable to interact with anything.

This happened twice, once I didn't even get to attempt to switch the quest before my character was locked, and again when I could walk around perfectly fine, but once I tried to switch the quest I got locked up.

**Comment by exectails** [comment]
Thanks for the report. If this was on your own server, could you check if there were any warnings or errors in the channel log file?
