### ISSUE TITLE
Leader's boss cutscene plays even when party members are outside the dungeon

### ISSUE THREAD

**Issue by eotetb** [aura-project/aura#489]
If you are inside a party and the leader opens the bossroom door, the cutscene will play. The problem is that it ends up playing for party members that are either outside the dungeon or currently inside a different dungeon from the party leader. I'm fairly sure this is not supposed to happen.

**Comment by Sairii** [comment]
welp, never thought about that.
yeah it only checks for party members not if they are in the dungeon.
Pretty sure thats wrong.
Also now i know that i could basically make a cinema in mabinogi. Or a broadcast video? xD /gg

**Comment by exectails** [comment]
Thanks for the report, I guess the cutscene system needs another tweak =| Blindly adding all party members to the viewer list isn't a good idea, who would've thought^^

Does anybody know if you see the cutscenes if you're in the same *dungeon*, but on different *floors*?

**Comment by xeroplz** [comment]
no, you don't see the cutscene if you're not on the same floor.

**Comment by exectails** [comment]
Goody, easy fix then. Thanks.
