### ISSUE TITLE
"You failed to enter the world"

### ISSUE THREAD

**Issue by Zeftseed** [aura-project/aura#49]
http://puu.sh/kHcD4/abbbc6318e.jpg

I setup the server and configs correctly, yet it tells me this when connection from internal or external.

**Comment by DeleteIT** [comment]
What does your channel.conf say at channel_host?
Does your Aura host have a firewall? If so, have you allowed the channel server through it, or opened the port in the above config file?

**Comment by Zeftseed** [comment]
So channel_host has my external ip.
I have also configured the right ports to be allowed through the firewall, Im still having the same issue

**Comment by DeleteIT** [comment]
What IP are you initially connecting to, the machine's internal or the network's external IP?

**Comment by Zeftseed** [comment]
Im connecting to local, but my friend also tries to connect and its the same issue

**Comment by DeleteIT** [comment]
So, can you try putting the internal address of the server in that conf file, and then just try connecting yourself?

**Comment by Zeftseed** [comment]
ok, i put the internal address in the conf file to say 192.x.x.x and it seems to be working, :D but will people be able to connect from outside my network?

**Comment by DeleteIT** [comment]
No, they won't.

For that, you'll need to open up your router's config page, and put in port forwarding for that port, to the machine hosting Aura.

**Comment by Zeftseed** [comment]
I forwarded the ports on the machine running aura and also in the router config. I typed my external ip in the channel_host but it seems to not be working again.

**Comment by exectails** [comment]
If it's not working from neither inside nor outside, you probably forgot something, but if your friend is able to connect from the literal outside, but you aren't, from inside the network, it's possible that your router doesn't allow you to connect to your own public IP, we've had this problem a few times in the past.

**Comment by Zeftseed** [comment]
There is no way around it?

**Comment by exectails** [comment]
If that is in fact the problem, there's not much we can do. Unfortunately I never heard back from people who had this problem. I'd suggest checking your router, maybe the manual, maybe Google, to make sure you can't do anything about it. Another option might be something like Hamachi.

You could hard code a solution into the login server, so it gives *you* an internal IP, while the public IP is sent to others. That would be relatively simple, albeit being a hack.

**Comment by Sairii** [comment]
uhm... sorry for the noob question but did you try connecting to localhost?
usually even with public ip in the config you can still connect with 127.0.0.1.
*confused*

**Comment by Zeftseed** [comment]
The server that is hosting Aura is on another computer

**Comment by Zeftseed** [comment]
How can you hardcode it into the server? I have no coding experience.

**Comment by DeleteIT** [comment]
It depends whether your router is capable of reflection.

**Comment by exectails** [comment]
>How can you hardcode it into the server? I have no coding experience.

Replace [this line](https://github.com/aura-project/aura/blob/master/src/LoginServer/Network/Send.cs#L406), with the following.

```
if (client.Account.Name == "your account name")
	packet.PutString("the ip sent for your account");
else
	packet.PutString(info.Host);
```

Fill in your information in the marked places and compile the servers again. Example:

```
if (client.Account.Name == "zeftseed")
	packet.PutString("127.0.0.1");
else
	packet.PutString(info.Host);
```

This will make the login server send the IP if the account with that name is used, otherwise it will use the IP from the conf file.

**Comment by DeleteIT** [comment]
I was going to add "I'd tell you about how to hardcode your IP, but Exec will have come and finished explaining it by the time I even locate the relevant part of the source."

**Comment by Zeftseed** [comment]
Thank you all, it worked :D

**Comment by DeleteIT** [comment]
@exectails  Maybe we should add a config option for local IP addition?
For example, if the value is there, the server returns the local IP for all connecting addresses that have a matching first three segments?

Perhaps with an alternate/additional OR for "If there's anything in the local connection only accounts field", in case the router's reflection redirects with the router's internal IP?

**Comment by exectails** [comment]
Yes, maybe we should. So far I always hoped for someone to dig deeper, to maybe find a better solution for this, and I was never sure how to implement it. No matter how you do it, it always feels like a hack =/

**Comment by V45Hx1** [comment]
by the way exec an actual tutorial on how to use hamachi would be nice i tried to set it up 3 or 4 different ways and it didnt work when i tried it

**Comment by DeleteIT** [comment]
@V45Hx1 Hamachi is just using the Hamachi IP of whatever device is hosting the server, it needs Hamachi installed.
Personally, I'd recommend just opening ports on your router instead, since Logmein is rather monetarily focused.

@exectails I don't think there's really a cleaner solution, you're always at the mercy of the router's capabilities.

**Comment by exectails** [comment]
@DeleteIT I mentioned Hamachi as a potential means to overcome this problem, not as an alternative to opening ports. But if @V45Hx1 tested it, and it didn't work for him, maybe that's no solution.

**Comment by DeleteIT** [comment]
I suspect that he may have used the normal IP address, instead of the Hamachi one, which means that the externally connecting clients are still in the exact same boat.

**Comment by V45Hx1** [comment]
no i didnt i used the hamachi one i am well experienced with how hamachi works i ran a lan only mass effect 3 private server off of it i know my software trust me

**Comment by DeleteIT** [comment]
You used the Hamachi `25.x.x.x` IP in the *channel.conf*, and not just in the client's command line?

I find it hard to believe that Aura would act differently with a particular kind of VPN system.

**Comment by V45Hx1** [comment]
yes i did and it didnt work

**Comment by DeleteIT** [comment]
Did it work for *any* clients?

**Comment by V45Hx1** [comment]
no

**Comment by DeleteIT** [comment]
So, we can basically summarise this chat with:
"Actually, I don't remember anything about this, other than there were issues, which *definitely* weren't due to ***my*** configuration, because I'm the master of Hamachi.".

Great.
I'll absolutely be able to use that information to resolve your issue.

Thanks for your time.

**Comment by Sairii** [comment]
Maybe try another programm like Tunngle.
Hamachi is just bad.

Ofc the best thing would be to setup your server/pc correctly and dont use any other stuff.

**Comment by V45Hx1** [comment]
actually i solved the problem i was having and i didnt need hamachi in the end anyway and yes tunngle works way better for things like this but hamachi is free and tunngle latency is notoriously bad
