### ISSUE TITLE
r8 Windmill training - boss requirement 

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#491]
Someone is having trouble ranking their windmill when it comes to defeating a boss level enemy. I believe the deal was whenever he kills a boss level enemy, he doesn't recieve training. He did manage to get training when he defeated 5+ at once, I believe.

**Comment by eotetb** [comment]
I can confirm having issues with that particular rank of windmill for getting training for boss kills.

**Comment by exectails** [comment]
Thanks for the report and the fix (#492), that's how I like my issues^^
