### ISSUE TITLE
Missing Shop items

### ISSUE THREAD

**Issue by Achrome1** [aura-project/aura#494]
Did some looking around and saw a book was missing from Stewart's (Lines 425-428) and Aeria's( Lines 298-318) shop inventory within their respective scripts.

For Stewart.cs
```
Add("Spellbook", 1007); // Healing: The Basics of Magic
Add("Spellbook", 1008); // Icebolt Spell: Origin and Training
Add("Spellbook", 1009); // A Guidebook on Firebolt
Add("Spellbook", 1010); // Basics of Lightning Magic: the Lightning Bolt
Add("Spellbook", 1085); // The First Steps of Meditation
```
And For Aeria.cs

```
Add("Skill Book", 1007); // Healing: The Basics of Magic
Add("Skill Book", 1029, 1, 9900); // A Campfire Memory
Add("Skill Book", 1114); // The History of Music in Erinn (3)
Add("Skill Book", 1111); // The Path of Composing
Add("Skill Book", 1013, 1, 80000); // Music Theory
Add("Skill Book", 1115, 1, 6190) ; // For Effective Meditation
```

Feel free to look into this proposition when you please.

Edit by exec: Fixed block code.

**Comment by exectails** [comment]
Thanks for the contribution, I wonder how we missed those =O

**Comment by Achrome1** [comment]
I'm honestly not sure ._.
On another server I was in, one of the co-owners told me that It should have been there and that she had it at rank D, so, maybe it was accidentally thrown out. XD
