### ISSUE TITLE
Guild recruit bug

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#496]
There's a bug were peoples guild invitations are set to pending for some reason. People who wants to join the guild gets a 404 error and will be put to pending. They appear as member on the guild list, but they don't get the guild name, chat or whatever.

**Comment by Pegwald** [comment]
Never mind, I just heard the guild accepting was working fine now o-o''

**Comment by exectails** [comment]
Was that maybe a few days ago? I remember fixing something on the guild page.
