### ISSUE TITLE
Prod mastery advancement typo

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#497]
Some player noticed that the cost displayed to rank Production mastery to r9 would cost 10 AP, but someone else tested this and found out the right cost is subtracted subtracted anyway, which is 5 AP. It's just a typo, we figured. The correct cost is 5 AP, not 10.

**Comment by exectails** [comment]
Thanks for the report, but where is that typo supposed to be? It says 5 AP when I try to rank it to 9. Though we couldn't really do anything about it either way, since that's client-sided.

**Comment by Pegwald** [comment]
huh, that's odd. I just saw someone over at my forums mentioning it. I assumed it was a bug so I just reported it before I got to check it myself... Sorry ^^''

**Comment by exectails** [comment]
I'll close this for now, since I assume that even if there is a bug, it would be client-sided. If there actually is an issue after all, please post here.
