### ISSUE TITLE
Missing Red wing of the Goddess info

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#498]
I feel like there is lacking some info on those red fixed feathers you receive in G1. Normally they will show a blue text about where the feather will take you, but right now I'm having a hard time sorting out which feather takes you where.

_(yeah, I'm a hoarder and save all of my feathers in my "Me" tab. What are you going to do about it?)_

**Comment by exectails** [comment]
Thanks for the report. This fix won't correct existing wings, unfortunately, but new ones won't be without target location info anymore. It would be possible to fix the existing wings in the database if it's a big issue though.
