### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#5]
References for G1 quests:
* Beginner: http://wiki.mabinogiworld.com/index.php?title=Beginner_Quests_(Human_Uladh)&oldid=14665
* Hunting: http://wiki.mabinogiworld.com/index.php?title=Hunting_Quests&oldid=61558
* Party: http://wiki.mabinogiworld.com/index.php?title=Party_Quests&oldid=60385

**Beginner**
- [x] Nao's Letter of Introduction
- [x] Rescue Resident
- [x] Save my Sheep
- [x] Malcolm's Ring
- [x] Duncan's Praise
- [x] Playing Instruments
- [x] Let's gather Green Gem
- [x] Let's Learn the Resting Skill
- [x] Campfire
- [x] Caution against Fire
- [x] Gathering Berries
- [x] Sheep shearing
- [x] Gather Cobweb
- [x] Repairing an Item
- [x] Do you know Production Mastery skill?
- [x] Logging Camp at Dugald Aisle
- [x] Talk with Stewart
- [x] Gather Eggs
- [x] Harvest Potato
- [x] Talk with Eavan
- [x] Visiting Bangor
- [x] Mine Lumps of Iron Ore
- [x] **School quests**
- [x] Go to School
- [x] Magic Mastery Lesson
- [x] Basic Combat 1 Mission
- [x] Basic Combat 2 Mission
- [x] Basic Combat 3 Mission
- [x] Basic Sorcery 3 Mission
- [x] **Age and level quests**
- [x] Duncan's call
- [x] Reach Level 20
- [x] Reach Level 30
- [x] Reach Level 40
- [x] Adulthood Ceremony
- [x] **Hunting quests**
- [x] Hunt 5 White Spiders
- [x] Hunt 5 Gray Foxes
- [x] Hunt 5 Gray Wolves
- [x] Hunt 5 Black Wolves
- [x] Hunt 5 White Wolves
- [x] Hunt 5 Brown Dire Wolves
- [x] Hunt 5 Black Dire Wolves
- [x] Hunt 5 White Dire Wolves
- [x] Hunt 1 Brown Bear
- [x] Hunt 1 Whisp
- [x] Hunt 5 Kobold Bandits
- [x] Hunt 5 Skeleton Wolves
- [x] Hunt 5 Skeletons
- [x] Hunt 1 Brown Grizzly Cub
- [x] Hunt 1 Red Grizzly Cub
- [x] Hunt 1 Red Bear
- [x] Hunt 1 Brown Grizzly Bear
- [x] Hunt 1 Black Grizzly Bear
- [x] Hunt 1 Troll
- [x] Hunt 1 Ogre
- [x] **Boss quests**
- [x] Hunt 1 Giant Spider
- [x] Hunt 1 Small Golem
- [x] Hunt 1 Hellhound
- [x] Hunt 1 Black Succubus
- [x] Hunt 1 Golem
- [x] Hunt 1 Ogre Warrior

**Hunting/Party quests**
- [x] Hunting quests
- [x] Party quests

**Comment by Pegwald** [comment]
Are those action quests (Tracy's Escape and Hurling Rocks) considered to be G1 material? They are pretty useful, but I don't think they came out before like in G13-14 or something.

**Comment by QewQew** [comment]
They definitely weren't as early as G1, but they *definitely* weren't as late as G13.

**Comment by exectails** [comment]
Hunting quests done.
