### ISSUE TITLE
Wolf AI

### ISSUE THREAD

**Issue by RashataanVuul** [aura-project/aura#50]
I wouldn't really say it's a bug I guess but Wolves seems to only have a passive aggro like foxes when close to them. From what I know from the offical, wolves eventually start attacking you after walking around you a bit.

**Comment by QewQew** [comment]
Gray wolves do not aggro unless you are in combat mode.
White wolves do aggro.

**Comment by exectails** [comment]
Actually, Gray and White Wolves use the same AI officially, so there should be no difference between them. And my experience is that Wolves will not attack players, unless you go into battle mode or attack them.

**Comment by DeleteIT** [comment]
Well, on this subject, is the progression from ! to !!! on entering combat mode still *immediate*?

On official, I recall there being a "Wow, really? Oh man, look at the time; it's Go'clock! D:<." delay.

**Comment by QewQew** [comment]
not immediate. on next check

**Comment by DeleteIT** [comment]
All I recall is that it is *significantly* faster than official.

**Comment by exectails** [comment]
Yea, on Aura it's pretty much instead, we don't have support for delayed aggro yet.

**Comment by QewQew** [comment]
oh. i was talking about official. oops.

**Comment by exectails** [comment]
I've just rested a bit in South Tir on NA with two wolves in alert mode. After 5 minutes the Gray and White Wolf were still circling me, but they didn't aggro, as expected. So I'll close this issue.

**Comment by Sairii** [comment]
<var_decl>
			<var name="visualfield_radius" default="650" />
			<var name="audio_range" default="400" />
		</var_decl>
		<sensor visualfield_radius="%visualfield_radius" visualfield_angle="120" audio_range="%audio_range" />
		<character target_type="one" support_type="one">
			<race stringid="*/pc/*" type="doubt" />
			<race stringid="*/cow/*" type="doubt" />
			<race stringid="*/dog/*" type="hate" />
			<race stringid="*/sheep/*" type="hate" />
			<option>
				<hate_nearby_battlemode duration="3000" />
			</option>
		</character>

They only hate on combat stance after 3000.

**Comment by exectails** [comment]
I can't imagine any mob attacking while *in* doubt, *something* would have to push them into aggro.

**Comment by Sairii** [comment]
http://i.imgur.com/2cJmYWI.png

It is possible but the chance is fairly low. I had videos about it. Kobold bandits being in doubt for up to 30 seconds and hitting me in doubt.

**Comment by DeleteIT** [comment]
I'll add that I have countered mobs and they've thrown up the !!! as they've been thrown back.
