### ISSUE TITLE
missing Support shot effect

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#500]
I just noticed that the blue cloud effect on support shot never appears. I'm not even sure if support shot puts enemies into a weakened state at all when I come to think of it...

_Issue No. 500! \o/_

**Comment by exectails** [comment]
> I'm not even sure if support shot puts enemies into a weakened state at all

It doesn't, because that's a G12 feature^^ It should be part of the `SupportShotRenewal` feature.

https://github.com/aura-project/aura/blob/master/src/ChannelServer/Skills/Combat/SupportShot.cs#L233
http://wiki.mabinogiworld.com/index.php?title=Support_Shot&oldid=116197
