### ISSUE TITLE
Trading in dungeon

### ISSUE THREAD

**Issue by killer000** [aura-project/aura#508]
Sometimes causes a person to be stuck until they get killed or relog out of client, while stuck they can't do anything expect type messages on the chat no skills can be used, no items no can be used.

I'm assuming because trading isn't fully gone when you quit from a trade during a dungeon

**Comment by exectails** [comment]
Could you elaborate on how exactly this is happening? How it can be reproduced?

**Comment by killer000** [comment]
Seems like you go to any dungeon and start trading with anyone it happens infrequently

**Comment by exectails** [comment]
It sounds like an error happened, but I assume it didn't happen on your own server, so we don't have a log of that. Without a clear idea of what happened, or a reliable way to reproduce it, it will be tricky to debug and fix this.

**Comment by killer000** [comment]
It isn't trading in dungeons it's the trade system Peg will open up a another Issue with the more accurate information
