### ISSUE TITLE
Ranged attack

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#51]
While playing around with golems I noticed that you cannot attack a golem that spawned ontop of you or you ran into.

The Aim either shows 0 or 100% but no matter what I couldn't hit and no debug message in the chat.

Ofc RANGED ATTACK

**Comment by exectails** [comment]
Any error/debug messages in the channel logs?

**Comment by Sairii** [comment]
Nothing really. I just had one unimplemented from the msg server?
I highly doubt that had anything to do with it.

**Comment by exectails** [comment]
Interesting... since the aim chance function was reverse engineered from the client, I wonder if this happens on officials as well... The reason is pretty simple, it's this check:
```
if (distance > bowRange || distance <= 0)
	return 0;
```
The distance is 0, because you're standing on top of the enemy. But I didn't write that function, so I don't know if that's official. Do you remember, @Tachiorz ?

**Comment by QewQew** [comment]
It should be official. If you're standing exactly on the same coordinate as another player/mob, ranged attack will always miss on official.

Also, attacks that cause knockback will knockback to the same coordinate, so they show the animation, but stay in place.

**Comment by exectails** [comment]
I'm not so sure, the client doesn't *always* show 0, sometimes it shows 99/100. Since our function is supposed to mimic what the client does/displays, you would expect it to not always return 0.

**Comment by Sairii** [comment]
Well back then zero shot was a thing...
Standing right in front or even in the mob and just shooting away.
And I never really had that issue. Ofc spawning a mob inside me might be something totally different.
But I think this even happend while trying to zero shot em.

*starts aura*

**Comment by exectails** [comment]
>Well it really only happens if you spawn it on you.

As I said above, we have a `distance == 0` check, which means whenever two creatures are standing on the same exact position, the aim chance function will return 0%.

**Comment by exectails** [comment]
Tachi took another look at the function in the client. While they have the same distance 0 check, their distance calculation is slightly different from ours, in that it uses 3 axis, it's 3D. Aura doesn't have a concept of a third dimension. My theory is that the client can "glitch", and put the enemy on a slightly different position, which causes *some* kind of distance in 3D, but not in 2D. That's also why it sometimes shows 0 and sometimes max.

There's really no way for us to fix this, and it's very possible that the official server has the same problem, even though that's hard to proof. I'll close this issue, as it should rarely occur during normal game-play, and might very well be official behavior.
