### ISSUE TITLE
"Moon Gates leading to" bug

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#511]
They only appear and never close if you trust the ingame broadcast that is.

Basically:
1. Moongate to Tir appears....... hovering over the clock says current moongate: Tir, next moongate: cant read that shit
2. Moongate to Tir closes, broadcast telling me that it appeared and next moongate at clock: TIR

http://i.imgur.com/M8ZHSTp.jpg

**Comment by exectails** [comment]
I'm pretty sure I fixed this like 1-3 weeks ago.

**Comment by Sairii** [comment]
just checked my file is 11 days old and does have the newest ceo fix.

**Comment by exectails** [comment]
https://github.com/aura-project/aura/commit/aa8db20729e71f53b09f0f508f895a9352bf3534

**Comment by Sairii** [comment]
I do have that aswell.

**Comment by exectails** [comment]
Looks like I fixed it partially, but not completely. *Now* it should hopefully work probably though. Thanks for the report.
