### ISSUE TITLE
Magic loading bug

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#514]
Recently I've been getting this bug were whenever I want to cast magic - getting stuck in a loading loop and receiving a message saying "<SERVER>: Error: skill wasn't fully casted yet."
It is possible to cancel the loading and move freely afterwards. There's also no additional mana cost when you're stuck in this state.

Need a look at my log, exec?

**Comment by Pegwald** [comment]
I checked it, but it doesn't give anything other than "SkillReady - Skill 'firebolt' wasn't fully casted yet"

**Comment by QewQew** [comment]
Are you using anything that would reduce casting time? Equips, etc?

**Comment by Pegwald** [comment]
I've got nothing out of the ordinary - not even a wand or anything.

**Comment by exectails** [comment]
You get that message if the server expected casting to end at a later time than it did, it's basically a security check to ensure that people don't modify their clients for shorter casting times. Are you using any client mods that might be causing this somehow?

Also, does this happen every time, or is it kinda random?

**Comment by Pegwald** [comment]
My client is totally clean. No mods, nada, niet, nothing.
It's very random. Sometimes it can happen up to 4 times in a row. It's like casting magic has a success rate now xD
I'm not sure if anyone else has this issue, because it happened pretty recently to me o-o''

**Comment by exectails** [comment]
I've never heard of it before, but it wouldn't be the first time a bug isn't reported.

**Comment by Pegwald** [comment]
I have a strong feeling this is just client sided. I noticed I could update the client qwq''
I'll check out if it's gone

**Comment by Pegwald** [comment]
well... I updated and noticed this https://gyazo.com/a6363a4ed8cde5f430ad2fe254231692
Also when trying to log out I'm stuck in "Saving character, Logging out" ^^''

**Comment by Pegwald** [comment]
On the other hand, I can't seem to recreate this bug, meaning we could temporarily close this issue ^^

**Comment by exectails** [comment]
> I'm stuck in

That would indicate that either the client or the server aren't up-to-date. NA is currently in maintenance though, so it's possible you're out-of-sync with Aura now, if you downloaded the next patch, which Aura potentially isn't compatible with yet.

**Comment by Pegwald** [comment]
Right. I'll just have to wait for an Aura update then ^^

**Comment by exectails** [comment]
I assume this is still a problem?

**Comment by Pegwald** [comment]
Looks like it's fixed, I can't recreate it anymore. I'll still keep an eye for it just in case ;)

**Comment by exectails** [comment]
Alright, closing for now.
