### ISSUE TITLE
Firebolt doesn't unstabalize 

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#516]
I noticed if you use firebolt to knock down an enemy, that target will get up immediately with full stability. Along with the free movement after casting it, you can run up to the firebolted target and start melee attacking it once it hits the ground. We're talking about a full free combo after firebolting it o-o''

It also feels like the firebolted target might teleport sometimes, but I can't confirm this yet.

**Comment by Sairii** [comment]
Yes, not sure if part of #171
but there is alot of wierdness tied to stun time / knockdown time.

**Comment by exectails** [comment]
Indeed, I don't see any stability setting in the Firebolt handler.

**Comment by Pegwald** [comment]
Some player also noticed this with magnum shot. It's the same deal - You can do a full combo after using magnum shot on an enemy
