### ISSUE TITLE
Critical hit Novice training (elf)

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#523]
This is possibly just a missing feature for elf (idk), but I noticed when you've got knowledge about critical hit, you either need to get critically hit or deal a critical hit with counter attack. In this case, there was no training received for taking a critical hit from a mimic.

I've got a video of it if that's needed ^^

**Comment by Sairii** [comment]
Noticed that aswell.
Not sure if its only elf tho. Anyways you need to land a critical hit with counter for it to work.
