### ISSUE TITLE
Mislinked Moon Gates

### ISSUE THREAD

**Issue by YaibaToKen** [aura-project/aura#542]
so.. I can't seem to get a screenshot at the moment (Mabinogi doesn't want this to be seen apparently xD) but the moon gates seem to be linked to themselves instead of opening the map. That is, they connect only to themselves and nothing else :/ Anything i can provide to help? Aside from the screenies, which I will try and get asap.

**Comment by Sairii** [comment]
So basically you are using the new Moongate system? Or old system? You do not have a map for the old system after all.

**Comment by YaibaToKen** [comment]
Do you mean the time restriction? I have the moon gates open all day. Aside from that I honestly don't know... Should I check the features config?

**Comment by Sairii** [comment]
basically old moongates = all moongates lead to one that is currently open
new moongates = always open and you can choose where you wanna go

**Comment by eotetb** [comment]
It should be noted that there are two different moongate features:
`MoonTunnel` which lets you choose a location like with iria's mana tunnels and
`Tunnel24Free` which causes gates to stay open even during the daytime.

**Comment by YaibaToKen** [comment]
Both are active, I'm rebuilding and resetting the cache to see if it helps. All help so far is appreciated :)
