### ISSUE TITLE
Aura & Mono

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#547]
**For future reference:**

Was running aura on a raspbian server:
Had Mono 3.2.8 and xBuild 12.
Compiled with Monodevelop caus xBuild was being mean.

Anyways, everything appeared to be working fine until I upgraded an Item.
Basically broke my upgrades.

What I did to get it working again:

I updated my repo list:
http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives
and installed Mono 4.6.2 xBuild 14.
Upgrade bug was gone.

**Comment by exectails** [comment]
Thanks, this would be better suited as a guide on the wiki or the forum though^^
