### ISSUE TITLE
creature.AcquireItem(item) doesn't insert into existing stacks

### ISSUE THREAD

**Issue by YaibaToKen** [aura-project/aura#549]
So, just like the title says, the method doesn't insert into existing item stacks in a character's inventory when, I believe, it should :( if there's an alternative method I can use that does this then feel free to let me know and close this issue. Otherwise I think it should be implemented as the code run when the player picks up an item already does this.

**Comment by exectails** [comment]
I will close this, as it's related to #345, and the question what exactly the methods should do by default.
