### ISSUE TITLE
Unable to rebirth through character window

### ISSUE THREAD

**Issue by YaibaToKen** [aura-project/aura#550]
While on the character selection menu, I'm able to rebirth, but if I log in and try to rebirth through the character's stats windows, it says I must wait 7 days between rebirths. I trust this is not a client issue. If it is, just close this.

**Comment by exectails** [comment]
This is indeed a client "issue". When you're logged in the client knows when you rebirthed last and checks that time when you click rebirth, based on its knowledge that you can rebirth once a week on officials. On the login screen it doesn't have that information and lets you pass.
