### ISSUE TITLE
Finish tags prevent dungeon room doors from opening

### ISSUE THREAD

**Issue by eotetb** [aura-project/aura#551]
If monsters receive finish tags while in a party, dungeon room doors will not open until the monsters are finished (or disappear, but I have not tested that yet). Dungeon room doors should open when the monsters are all defeated, players can choose to ignore finish tags and continue the dungeon in official.

**Comment by exectails** [comment]
Alright, the problem is that the death events aren't raised until the creature is completely dead, but simply moving those events could have unexpected effects on other areas, like skill training. I think we need a second event, with death occurring first, and being finished second, because that's what's happening.

**Comment by exectails** [comment]
I find it interesting this is considered an issue, when it actually ensures that your party members don't accidentally forget a monster and as a result the key as well^^ Anyway, thanks for the report!

**Comment by Pegwald** [comment]
I just have to make sure; The key will always drop even before the mob is finished (or not), doesn't it? The other loot will drop on the finish, I believe.

I think that's how I remember it, but my memory is getting more and more rusty.

**Comment by eotetb** [comment]
That is definitely correct, dungeon keys, treasure chest keys, and boss room keys will drop from the mob after they are defeated, they don't have to be finished.

**Comment by exectails** [comment]
Wait, what...? I definitely remember going back to rooms because someone forgot to finish some monster, why would we do that if it wasn't for the keys? Maybe that's "new"?

**Comment by eotetb** [comment]
I can't say I remember how it was in early generations, but in official currently that is how it works. I know I often left keys in a room without picking it up, but it did drop from the monster, we just missed it.
