### ISSUE TITLE
Can't enter Sliab Cuilin from Dugald Aisle

### ISSUE THREAD

**Issue by YaibaToKen** [aura-project/aura#552]
So I just demolished the seal stone only to find out I can enter Sliab Cuilin from here xD

[Unimplemented] - TouchProp: No prop behavior for '00A00010000C00D2'.

Question is, is something I didn't enable in the feature list? Or is it something else?

**Comment by killer000** [comment]
Yeah the area Sliab Cuilin isn't done yet, I believe I think that happened in G9 gone a bit too far ahead of yourself there :)

**Comment by YaibaToKen** [comment]
To be honest I wasn't sure on the map progress xD figured I might as well ask

**Comment by exectails** [comment]
What you've encountered here is that the portal doesn't have any behavior added to it yet. Basically we have to tell each of those portals what they should do, which usually means a warp. You can see which regions are done already here: https://github.com/aura-project/aura/tree/master/system/scripts/regions

The warps and spawns of regions that aren't in there likely haven't been added yet.
