### ISSUE TITLE
Can't compose

### ISSUE THREAD

**Issue by YaibaToKen** [aura-project/aura#553]
Is the Music Composition not fully implemented yet? Is it a bug? Is it because of the new Music Update?
Either way, whenever I try to compose, I write something to the chords, give it a name and click to finish and the skill doesn't get triggered, nor does the scroll get written.

**Comment by killer000** [comment]
You should probably remove this issue and come comment on this one  #545

**Comment by YaibaToKen** [comment]
ups, you're right, sorry about that, didn't even remember
