### ISSUE TITLE
New finish rule + dungeons

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#554]
I randomly noticed that the party finish rule has been implemented and with it a bug (or two).

Say you're in a party of two in a dungeon. You open a chest and defeat everything inside. What's this? You're still unable to leave the room after clearing it? Oh, that might be because there are some enemies haven't been finished off yet.

So doors won't open and spawns won't spawn before every "finishable" enemy has been finished off.

I wonder what happens if you don't finish a mob in one of the rooms and you let it expire... Expire as in "poof" - gone.

**Comment by eotetb** [comment]
Uhhh, #551

I suppose this post is a little more detailed, but its essentially the same issue. That said, I'm really curious what happens when monsters poof. It would be really bad if it trapped you inside the room.

**Comment by Pegwald** [comment]
Oh, sorry I didn't notice it ^^''

**Comment by killer000** [comment]
@eotetb  I don't believe they go poof, but only once did someone have a problem seeing the monster they had to finish since it was invisible to them.

**Comment by exectails** [comment]
Closing this because we already have an issue about it. You're right though, @killer000, they wouldn't disappear, because they aren't completely dead yet.
