### ISSUE TITLE
Tailoring skill not being triggered after minigame

### ISSUE THREAD

**Issue by YaibaToKen** [aura-project/aura#555]
So, is the tailoring skill not supposed to always trigger after the minigame for finishing an item, no matter how crappy the outcome of said minigame? I was doing Simon's ptj and failed the first minigame. The item was not completed but consumed the materials.

I then attempted it a second time, had a better result from the minigame and it completed the item.

I believe the reason we are only given enough finishing materials for the requested items is because, no matter the result of the minigame, the item will always be finished, though quality will vary.

Both times this was outputted to the Channel Server console:
[Warning] - ApplyUpgradeEffects: Unknown/unhandled stat 'LessenManaUsage'.

**Comment by eotetb** [comment]
Its normal for an item to not be fully complete after using the tailoring skill and consume materials for an attempt. Did it do nothing at all after failing or was there some sort of change?

**Comment by YaibaToKen** [comment]
Basically I didn't finish the minigame on time. On officials this will simply produce an inferior item. What happened on Aura though was that the item was not finished, the materials where consumed and the animation that usually plays with the skill showing up in a bubble above the player's head didn't happen.

**Comment by exectails** [comment]
I think I know what the problem is, I might've misinterpreted a value in the skill's packet. Basically Aura silently fails the skill if not enough stitches were sent.
