### ISSUE TITLE
moon tunnel to Ceo

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#556]
I noticed if you have Moon tunnel enabled in your features, there's no Ceo Island moon gate you can travel to (which should have been added in the first place). I tried warping to Ceo with my GM in order to save it (by touching it) from there, but once I try to return to the island from another moongate it will not show up at all.

The moon gate should already exist in your list of available moongates you can travel to, but it doesn't.

**Comment by YaibaToKen** [comment]
I currently have the moon tunnel feature active as well as the moon gates always open and I seem to have no such issue.

**Comment by exectails** [comment]
You get the Ceo Moon Tunnel automatically if the G2 feature is enabled.

**Comment by eotetb** [comment]
Do you have the generation 2 feature enabled? The ceo island moon gate is working fine for me with moon tunnels enabled and g2 enabled.

**Comment by Pegwald** [comment]
Ah, I didn't know that x-x''
I only enabled the dungeons from the g2 settings instead of the whole thing. Thanks!

**Comment by exectails** [comment]
I'll add a new feature just for the Ceo Moon Tunnel, so this becomes more obvious.
