### ISSUE TITLE
Math Adv. Dungeon - Bard Skeletons Don't Transform

### ISSUE THREAD

**Issue by boilerplate5** [aura-project/aura#558]
There was no log at the time but when I went through Math Adv, the pass for a fully party of 8, the Bard Skeletons did not transform after the Hellhounds were defeated, upon which they should turn into Metal Bard Skeletons, be knocked out, and the dungeon be completed.

**Comment by exectails** [comment]
They do transform, but only if they are killed before the Hellhounds. Though I don't remember where I got that from anymore...

https://github.com/aura-project/aura/blob/master/system/scripts/dungeons/dunbarton_math_high_dungeon.cs#L18

What's the official behavior?

**Comment by boilerplate5** [comment]
http://wiki.mabinogiworld.com/view/Skeleton#Bard_Skeleton

Bard Skeletons in their initial form are invincible. When the Hellhound Skeletons die they should become Metal Bard Skeletons (I believe there's a cutscene for this too where it becomes enraged about it) then when the Metal Bard Skeletons are KO'd, the door will open to the treasure room.

**Comment by exectails** [comment]
As you can see in the file I linked we do have the transformation and the cutscene, but I guess I misunderstood the check for it. It's supposed to happen when the last hound dies, and not if the last monster dies and it was a hound.

(Side note: I'm starting to hate the wiki, not even the anchors are working properly half the time anymore >_> Someone should make a proper database some time.)
