### ISSUE TITLE
Ranged Attack arrow trail upon miss

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#559]
https://www.youtube.com/watch?v=HJM1ExDyABw

The Arrow simply flies towards the sky upon miss.
It usually flies to the vicinity of the monster you are trying to hit.

**Comment by exectails** [comment]
Huh. I guess it makes sense, if the arrow misses we only send the attacker combat action, and the client wouldn't really know where the arrow is supposed to go. We need a log of a missing arrow to analyze how officials do that.

**Comment by exectails** [comment]
```text
Target Action
--------------------
Creature: 0010F000000033DF
Type: None
Stun: 0
Skill Id: CombatMastery
```

**Comment by exectails** [comment]
It seems like this is only a thing for elves, as there's no effects for humans using Ranged. The log of the target action above works though, the effect now goes to the enemy, even on a miss.
