### ISSUE TITLE
Splitting exp% via skill tab in the config file

### ISSUE THREAD

**Issue by Zaxanity** [aura-project/aura#566]
For example:
// Exp rate for combat skill training (%)
combat_skill_exp_rate: 500%
// Exp rate for magic skill training (%)
magic_skill_exp_rate:
// Exp rate for music skill training (%)
music_skill_exp_rate:

etc.

Instead of all the skills having to be affected by the same change.

// Exp rate for skill training (%)
skill_exp_rate : 100

Like it is currently.

**Comment by exectails** [comment]
This is a good suggestions that I don't see any problem with. Implementation: add conf options and in the training check the skill type.

**Comment by exectails** [comment]
Added in 3106be1.
