### ISSUE TITLE
Production Skills and Bags

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#57]
Production skills do not use items that are in a bag.

You can place a production bag into the procudtion window and click start.
Everything works fine till that moment.
Then after a while you get the notice "Insufficient Materials".

**Comment by exectails** [comment]
What is a "production bag" =<

**Comment by QewQew** [comment]
Item sacs is probably what he means. Wool bags. Leather bags.

**Comment by exectails** [comment]
But those didn't exist in G1 qq Well, if you can actually put those into the slots on officials, I'll have to come up with a way to handle it... The tags are completely different, so we'd need to keep a reference to the item data of the sac item, to compare both tags.

**Comment by Sairii** [comment]
yup yup wool bags etc
