### ISSUE TITLE
Implementing Elemental Enchant-All Slots

### ISSUE THREAD

**Issue by eotetb** [aura-project/aura#575]
The hidden skill Elemental Enchant-All Slots (skill id 50011) needs to be implemented in order to use massive elementals (which enchant all equipped gear with the given element).

**Comment by exectails** [comment]
I that doesn't work yet maybe we shouldn't enable the quests just yet =|

**Comment by eotetb** [comment]
Closing this, since it looks like you implemented this a few days ago.

**Comment by exectails** [comment]
Oh, right. Thanks.
