### ISSUE TITLE
Items being added to wrong bags

### ISSUE THREAD

**Issue by YaibaToKen** [aura-project/aura#576]
As the title says, whenever the player picks up an item, it can be placed in any bag, even if it's not allowed in that bag. For example, potions getting stored in an equipment only bag. I' m not sure if this is related to #366 or not but just wanted to let you know.

**Comment by eotetb** [comment]
Bags can also end up going inside of other bags too when bagception is disabled because of this.

**Comment by YaibaToKen** [comment]
Actually, despite having bagception enabled I can't place bags inside bags xD

**Comment by exectails** [comment]
Thanks for the report, but it is related to #366. Basically item association to specific bags is not a thing yet, that's what both those issues come down to, and the reason I'm gonna close this one. We should probably look into that some time though, even if we don't technically need it for our current generation.

**Comment by YaibaToKen** [comment]
I'll help with whatever I can since it honestly bothers me quite a bit

**Comment by exectails** [comment]
>it honestly bothers me quite a bit

That items can go into any bag? This is G1 though, that's how it's supposed to be =P

**Comment by YaibaToKen** [comment]
I'm a neat freak xD
