### ISSUE TITLE
Unfinished mobs do not despawn

### ISSUE THREAD

**Issue by eotetb** [aura-project/aura#582]
Mobs with finish tags should despawn after a set amount of time passes, rather than never disappearing.

**Comment by exectails** [comment]
Didn't know that, makes sense I guess^^ Do you happen to know how long that time is?

**Comment by eotetb** [comment]
Unfortunately, I do not.

**Comment by Zaxanity** [comment]
Looks like its exactly 60 seconds. I just timed it a few times on the main server.
