### ISSUE TITLE
Missing book in Nele's secret shop

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#583]
http://wiki.mabinogiworld.com/view/Wind_Instruments:_Melodies_of_the_Soul

Enough said. All the other books are there, it seems.

**Comment by eotetb** [comment]
Oops, look I missed a book. That particular book is actually supposed to be in his regular shop tab however.

**Comment by eotetb** [comment]
Sent a PR to fix this in #584

**Comment by exectails** [comment]
Thanks!
