### ISSUE TITLE
Potion making bug(s)

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#61]
It seems that when you craft a potion with the potion making skill, your selected basic herb will not be subtracted as loss from your VIP inventory if the crafting would fail. So far this has only happened with the basic herb.

https://youtu.be/_qBMZtCgOcY

**Comment by Pegwald** [comment]
It looks like that even if the basic herb is located in another inventory or not, it still doesn't subtract from failure. Bloody herbs still does.

I have yet to see if the basic herb will be subtracted at success.

**Comment by Pegwald** [comment]
New bug - There is no mana consumption when I make SP 100 potion. I assume that this is the same case with all the other mana consuming potion crafts.

https://youtu.be/HVGPhDqRRVg

**Comment by QewQew** [comment]
New bug? New issue.

**Comment by Pegwald** [comment]
I'm sorry about the comment spam, but I also noticed there are no base potion x 10 available for purchase.

**Comment by Pegwald** [comment]
I was afraid that making a new issue for the same category would be sort of unnecessary, but if that is what is most preferred I will of course respect that and start doing it from now ^^ ''

**Comment by QewQew** [comment]
>I also noticed there are no base potion x 10 available for purchase.

Which NPCs have you checked?

**Comment by Pegwald** [comment]
I checked Manus, but not any other yet

**Comment by xCryptic** [comment]
@Pegwald just spawn them in for now `>spawn 51037 10`

**Comment by QewQew** [comment]
>item

And it's not like we didn't know you could do that.
The issue is that the NPC is selling the wrong amount of items.

**Comment by exectails** [comment]
>I was afraid that making a new issue for the same category would be sort of unnecessary

No, we strongly prefer one issue per *issue*. As you can see here, mixing topics ends in "spam" fast, and you can't close a "multi-issue" before all issues are solved, which is counter intuitive. Let's keep this issue to the first one you mentioned, herbs not being removed. Please create new issues for additional bugs.

The reason for materials somethings not getting removed is that on fail, a random amount of materials are removed. Or at least so I'm told. Right now it's a random amount between 0 and the actual amount. Is there a minimum that always gets removed? Like at least 1, or at least half?

**Comment by Pegwald** [comment]
The way it used to function is that if you queue the crafting, all items added will be consumed. If you don't queue the production, there is a chance you will successfully craft all at once, however, if you fail - there will be a random amount subtracted from the items you added.

Say if you add 10 basic herbs, 10 bloody ones and 10 basic potions, you might end up not loosing more than one ore two of for example bloody herb, but you might also loose up to nearly all of your basic herbs or potions. It's completely random how much you lose upon failing an "unqueued" craft.
In a queued craft you always subtract all items added by 1, even if you succeed or not.

**Comment by exectails** [comment]
Huh, interesting. I'll implement it like that then. I'll also make the minimum 1 I guess, it doesn't make too much sense to not lose *any* materials.
