### ISSUE TITLE
Immobilising bolt-firing book

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#62]
Equipping a crossbow while holding a book will make your character move funny. I am not yet sure if this affects other items too such as swords, potion kits and other things held in the right hand slot.

https://youtu.be/3TKLa1Fw4eY

**Comment by QewQew** [comment]
The bug is not the funny movement -- that happens with any equipment set that's not legal.
The bug here is that you can equip a crossbow and a book simultaneously.

**Comment by Pegwald** [comment]
I am aware that the funny movement is not the bug in this case, but that was just intended as a joke since the video already makes a more accurate info about this issue. Sorry about the misleading info.

However, I expected the book to automatically be unequipped and put into the inventory as well, but such did not happen. That is indeed why I am posting this issue here in the first place :)

**Comment by exectails** [comment]
The equipping and unequipping thing is a little complicated in Mabi, I've fixed it again for now, but it's quite possible there are equip combinations that aren't handled properly yet.

**Comment by Pegwald** [comment]
Great job, it works :>
