### ISSUE TITLE
Key Colors?

### ISSUE THREAD

**Issue by Xcelled** [aura-project/aura#68]
To the best of my knowledge, dungeon keys are *never* purple.

![](http://puu.sh/laXE5/fd7b411e15.jpg)

Though this is really interesting! A conf option to allow the full rgb spectrum of colors to *always* be used for keys would be awesome.

**Comment by Xcelled** [comment]
Chest keys are also blue, not the proper silver.

**Comment by exectails** [comment]
I think it makes sense to limit it to certain colors, otherwise you could get keys that look more or less identical, or really weird colors. It is pretty easy to customize though, if one wanted to. If you remove the default colors you would actually a get a random in range of 0xFFFFFFFF, which is the fall back.

https://github.com/aura-project/aura/blob/44ad61767e625beb9737cc34e11a98c71bfc1566/src/ChannelServer/World/Dungeons/Generation/DungeonFloorSection.cs#L68

Was this supposed to be a bug report or a suggestion? I really don't see it as a problem if we have slightly different colors from officials.

**Comment by Xcelled** [comment]
Yes but customizing via code editing is less friendly than a conf option.

It was a combination bug report/suggestion. It's a bit unsettling to suddenly see different colors, from a user's perspective.

**Comment by exectails** [comment]
>It's a bit unsettling

Yet the first one to even bring it up in *any* way is you =P We could use official colors, but I won't be the one to run dozens of dungeons to collect colors =< It's also really not a *bug*, so I'm not sure what to do with this issue.

>Yes but customizing via code editing is less friendly than a conf option.

Naturally, but I told you it doesn't make too much sense to make it completely random. And there's literally no reason to make it configurable, aside from it maybe being a little funny. I won't be the one to implement it.

**Comment by exectails** [comment]
About the treasure keys... they don't have color maps, I assume we got the wrong item if they aren't silver, I'll look into that.

**Comment by Xcelled** [comment]
Minor issue I just noticed: If we run out of door keys, it's possible (but unlikely) to get the same color twice, as there's no check on the rng return.

**Comment by exectails** [comment]
>it's possible (but unlikely) to get the same color twice, as there's no check on the rng return.

You don't say.

>I think it makes sense to limit it to certain colors, otherwise you could get keys that look more or less identical, or really weird colors.

I haven't tried if the locks flash, the keys probably would.

**Comment by exectails** [comment]
Normal treasure chest keys are silver and the ones after the boss are gold?

**Comment by QewQew** [comment]
Treasure chests are silver, but the boss ones can be any color.

**Comment by exectails** [comment]
Alright.

**Comment by exectails** [comment]
I'm thinking about closing this issue, as I don't consider it to be one. I actually like the colors we're using right now better than the official ones, and I can't imagine that someone would like to run dozens of dungeons to collect official colors anyway. Though we might want to add some more, to ensure that we don't run out of colors.

**Comment by exectails** [comment]
Should this ever become an actual issue, please report it again. Also, if anyone actually wants to, please feel free to collect official lock colors. It would be good to have them, and I actually wonder how many they have in their rotation.
