### ISSUE TITLE
Dungeon scroller missing

### ISSUE THREAD

**Issue by Xcelled** [aura-project/aura#70]
When you enter a dungeon or click a statue of the goddess, you get a scrolling message across the top of your screen telling you who's in the dungeon, and which floor they're on. This is missing from the statues, and the creation.

**Comment by xeroplz** [comment]
OH yeah I remember talking about this in gitter and then forgetting to actually open an issue.
:+1:

**Comment by Xcelled** [comment]
I wrote the code to make the initial-entrance scroller, but we have a problem. Since a creature's location isn't set until their client acknowledges a warp, the scroller is generated before they're actually in the dungeon, so it's inaccurate. (It reports 0 people, for example)

Generating the scroller on-demand when the client arrives in the dungeon won't work either, as it won't contain the characters who are still warping.

What I have so far is here: http://puu.sh/lbeMN/6e7bd4a6c9.patch

**Comment by exectails** [comment]
I've added a Region event "PlayerEnters" that is already used for the memorization and the "dungeon created by another player" notice, that might be a good place for it.

**Comment by Xcelled** [comment]
Does it let you access players who are in the process of warping into the dungeon? If not, the crawler will still be incorrect.

**Comment by exectails** [comment]
The event is raised after the player was added to the region.

**Comment by exectails** [comment]
When exactly does this message appear? Only when you go in or switch dungeon regions? Or is it broadcasted to everybody in the dungeon whenever someone enters it as well?

**Comment by Xcelled** [comment]
It only shows up when *you* enter a dungeon, however, it includes everyone "in" the dungeon, regardless of if they've finished warping in or not. If you're in a party with Bob, it's wholly possible to get the scroller "Players in dungeon: You, Bob" and Bob doesn't actually load in until your scroller is done.

**Comment by exectails** [comment]
I admit, that would be tricky to do with the way warping currently works... we should make sure that's how it actually works.

**Comment by exectails** [comment]
This is the best we can do for the moment. Getting a list of all creatures, before they're done warping, would require hacks, which wouldn't be ideal imo. Should we ever change the warp logic again, we can improve this.
