### ISSUE TITLE
Defense training

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#74]
One of my friends told me that it was impossible to train defense, something relating to my magic bolt issue I just posted. In his case, though, he wouldn't receive any training exp for being hit by a mob. His rank is E and he's unable to train this skill any further. How odd... mine is rank D somehow.

**Comment by exectails** [comment]
Part of this fix was part a refactoring that was long overdue. Defense now works, but the refactoring could potentially cause other problems, so keep the issues coming if you notice anything, especially in regards to skill training^^
