### ISSUE TITLE
Tuesday

### ISSUE THREAD

**Issue by Xcelled** [aura-project/aura#78]
Looking at the code, Tuesday does not seem to affect dungeon instance generation.

**Comment by exectails** [comment]
Too bad @DeleteIT isn't here, he researched and removed that. I always forget his explanations about it =<

https://github.com/Whimsytech/aura/pull/3/files#diff-7408e9a93c047dfe91692dca8bd2bb05L124

Originally I made the manager create a new dungeon every time on Tuesdays. But apparently that's not what happens, iirc what should happen according to him is that the floor layout is static on normal days, but random on Tuesdays. That would easy to do, but I never got confirmation.

**Comment by DeleteIT** [comment]
Tuesday: Dungeon should have random layout. 
Every other day: Dungeon should reuse previous layout. (I don't know if it changes on a daily basis or not)

***NO INSTANCING AT ANY POINT***.
Except for passes, which are always random layouts anyway.

**Comment by exectails** [comment]
So I did remember that correctly. It's still weird, isn't it? How most people seem to assume Tuesday = instance? Maybe that should be an option.
