### ISSUE TITLE
Basic NPCs

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#8]
NPCs are considered "done" when they're more than a pure dummy, meaning handling a variety of keywords and ideally having their shops or other special functions working (e.g. Alissa's Windmill).

- [x] **Tir Chonaill**
- [x] **Sidhe Sneatcha**
- [x] Bear
- [x] Tarlach
- [x] **Dugald Aisle**
- [x] **Dunbarton**
- [x] **Gairech**
- [x] Seumas
- [x] **Bangor**
- [x] **Tir Na Nog**
- [x] Dougal
- [x] **Others**
- [x] Nao
- [x] Tin

**Comment by Pegwald** [comment]
Wouldn't an NPC be considered "done" when they all have it all - accessable shop, PTJ, classes and training, PTJ and item upgrades? I mean, there are still NPCs in Tir who doesn't have that yet, unless they are not supposed to YET <w<''

**Comment by QewQew** [comment]
By that definition, it'll be forever until any NPC is considered "done". That's why it's just simplified to more than just dummy responses.

**Comment by Pegwald** [comment]
Yeah, it probably takes a while to make them fully "done"... there are plenty of NPCs. :/
I just had trouble understanding "done" - if this meant "complete" or just "temporarily done", when thinking about the fact there are still some missing features and content.

**Comment by exectails** [comment]
Some things, especially PTJs take a while. You could also count quests into the requirements for an NPC to be done, all the keywords they can handle, and so on. Like I wrote above "done" means more than a dummy (no dialog), ideally with shop, but not necessarily "*done*" done. That would just take too long, and we don't need *everything* for our G1 milestone.
