### ISSUE TITLE
Seal breaker title rewards not granted

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#80]
I've noticed that when the seal stone to Ciar is broken, the breaker doesn't get rC first aid. The seal breaker of Rabbie doesn't get WM rE, and I doubt this goes for the other seal stones as well. Not a very serious issue, but since Aura is supposed to be nearly as accurate as the official Mabi, doesn't this have to be applied?

**Comment by exectails** [comment]
>doesn't this have to be applied?

Absolutely.

>Not a very serious issue

Absolutely not, but an issue nonetheless, and issues must be reported and fixed^^

I assume I didn't really look into the effects of seal breaking, and just implemented the basics, since all that ever happens in the script is enabling the title.
