### ISSUE TITLE
Dual Wielding Animation

### ISSUE THREAD

**Issue by Aura-Cryptic** [aura-project/aura#81]
This issue was brought up back in September, where the dual wielding's last animation is incorrect. Refer back to the thread I made here - http://aura-project.org/forum/index.php/topic/989-dual-weilding-animation/

**Comment by exectails** [comment]
So... the problem is only with first hit kills? In that case the solution is clear, because we don't handle first hit kills yet^^ If FirstHit is never set the animation can never be correct.

**Comment by Aura-Cryptic** [comment]
It happens with both. Just compare the hits to live :P

**Comment by exectails** [comment]
I *think* it's correct now.
