### ISSUE TITLE
Dungeon Instance bug

### ISSUE THREAD

**Issue by Xcelled** [aura-project/aura#81]
Bug video: https://youtu.be/wkJskScv9Mc

When a dungeon is created, party A is set as the "creators" of the dungeon. Dungeon creators *do not change* once the dungeon has been constructed.

Party "A" is then warped in to the dungeon. This currently works, but it works for the wrong reason. Instead of the *party* being warped in, this list of *creators* is. At this point, creators is the same as Party A, so there's no visible effect.

When party B comes along and tries to enter the dungeon, the mistake in the warping code becomes obvious. Once again, instead of warping the *party*, the *creators* are warped. However, creators is really the members of Party **A**, not Party **B**, so party B is left on the altar while A is warped back into the dungeon. You can clearly see this in the bug video.

In summary:
 - Altar check code is fine
 - Dungeon constructor/creation is fine, aside from a slightly confusing member name.
 - Warping into a dungeon is *incorrect* because *the wrong set of creatures are warped*.

**Comment by Xcelled** [comment]
As I currently lack commit access...

http://puu.sh/lbaAu/b8b0d71acd.patch

**Comment by QewQew** [comment]
Pull request. :+1:

**Comment by Xcelled** [comment]
Would require forking and then moving my commits to the fork, which I'm too lazy to do... ;)
