### ISSUE TITLE
Insane knockback bug

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#85]
Meanwhile in Tir, near the moongate by Ferghus, I was testing the knockdown skill requirements for the magic bolt spells when I found myself in an itchy situation. I was down to like 10 hp and decided to run away to try to escape my inevitable death of a white wolf that was running at me with smash. Ahead of me was the entrance to Dugald Aisle, which would be my great escape... or that's what I was expecting.

This is very hard for me to explain since I did catch it on tape this time, but I will give it a shot. I am not joking with you when I am about to tell this.
Upon reaching the entrance, I clicked it and thought I was safe. However, the wolf managed to catch up to me and landed its smash while my screen was fading to black. When it faded back in, I could not recognize the place around me. It wasn't before I opened my map I figured what had happened.

https://youtu.be/CJjCzWsVFGM
This is the only footage I got of this incident.

Do we take this seriously or? I am just speechless.

**Comment by QewQew** [comment]
Looks like the Smash set your character's position after the map movement, overriding the transition.

**Comment by Pegwald** [comment]
Upon clicking an entrance, isn't it supposed to making your character non-targetable? I thought all agro dropped by doing this.

**Comment by QewQew** [comment]
In officlal, it probably would.
Of course, you'd have to code it first, and this was probably overlooked.

**Comment by Pegwald** [comment]
Totally understandable.Who would ever predict this happening? ^^ ''

**Comment by exectails** [comment]
Mhm, a quick fix could be checking for the Warping property from the AI, to drop aggro and exclude the target.
