### ISSUE TITLE
"herbalismless" herb picking

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#92]
It's possible to pick any herb without Herbalism. I already know it's possible to pick basic, red and yellow without it, but I've recently managed to pick Mandrakes and poison herbs... also antidote herbs. Does production mastery has anything to do with it? I know it gives you x% in production and gathering, but I thought this was unlocked for gathering skills (such as herbalism) once you knew the gathering skill? I'm not sure about this, but however, the case is that I can pick adv. herbs without herbalism.

**Comment by exectails** [comment]
So what you're saying is that officially you can't pick those herbs without Herbalism? The way this is currently implemented in Aura is that we use the chance specified in the collection db by default, and the chance increases based on you Herbalism rank.

For example, Poison Herbs have a base chance of 15%, with it being increased to 50% on rB and ... 90% on r3... Okay, I see how these chances can appear too high for an "advanced" herb. What's weird is, that Poison Herb has the same base chance as Base Herbs in dungeons, unlike Bloody, Mana, and Sunlight, that have less than 10% base chance. Base Herbs in fields and Gold Herbs have a base chance of 0%, which makes them unpickable without the bonuses from Herbalism.

Does anybody know if you can pick Poison Herbs without Herbalism on official?

**Comment by Xcelled** [comment]
http://wiki.mabinogiworld.com/view/Herbalism

This seems to gel with my experiences in game. There's two bonuses, but any herb can be picked at any rank, it's just the higher herbs have a success rate so low it might as well be zero.

**Comment by xeroplz** [comment]
You can indeed pick herbs without the skill, it's just a horribly low success rate.

**Comment by exectails** [comment]
>I've never successfully picked anything over a sunlight herb without herbalism

Yea, that matches the chances *generally*. Sunlight has 5% without Herbalism, Mana has 3, Gold has 0, so you *can't* pick it without the skill. However, White, Poison, etc, the really "high level" ones, have comparably high base success rates, without anything in the client data indicating that they are a special case.

I've just noticed, White Herb has *50%* base chance... that seems really wrong. Someone go run Peaca for me, on a character without Herbalism^^

**Comment by exectails** [comment]
While we still haven't gotten any real world tests done, someone pointed out to me that according to the Wiki you're supposed to be able to pick White Herbs from rE onward.

http://wiki.mabinogiworld.com/view/Herbalism#Rank_E
>Hint: You can now gather White Herbs, but it will still be difficult.

I wonder if maybe the base success chance doesn't apply to Herbalism, even if it's seemingly used in the db. In that case you would not be able to pick White Herbs below rE, and afterwards the success chance would be 25%. But you wouldn't be able to collect even Base Herbs without Herbalism then =/ I assume the entire formula we're using is wrong.

**Comment by Pegwald** [comment]
I'm not sure about this, but I thought it was impossible to gather base herbs without herbalism. Impossible until you gain knowledge/novice rank or something. That's at least what I thought. Again, I'm not sure about this.

**Comment by Xcelled** [comment]
It's entirely possible to gather base herbs without herbalism, you just
can't identify patches nor can you locate base herbs in the field by sight.
Moving your mouse over an invisible patch still gives you the hand cursor.

**Comment by exectails** [comment]
@Pegwald Yes, it is possible, which is the problem with the theory that base chance is not a thing^^

Oh, btw, some were wondering if the Wasp herbs are the same as the patches in Peaca, going by the client db, they're not. According to the db, those actually have a *100%* base chance.

**Comment by exectails** [comment]
I've finally done some research. It seems like the base chance in the database doesn't actually affect the success chance of Herbalism. The Wiki is wrong as well, with their 25/50 rule. I've spawned the herb patch props, enabled the devCAT title, and simply logged all values for every rank and herb. If I didn't get a success chance, I used 0. Here's the official success chance table:

/|base|bloody|sunlight|mana|white|golden|mandrake|antidote|poison
----|------|--------|----------|------|-------|--------|--------|-------|--------
N|15|8|5|3|0|0|0|0|0
F|50|20|15|10|0|0|0|0|0
E|55|25|20|15|10|0|0|0|0
D|60|30|30|20|15|7|0|0|0
C|65|50|35|25|20|9|0|0|0
B|70|60|50|30|25|13|0|0|0
A|75|65|55|35|30|15|10|0|0
9|80|70|57|50|35|17|12|25|10
8|85|75|60|53|40|19|16|30|14
7|90|80|62|56|45|21|18|35|17
6|95|85|64|60|50|23|23|40|20
5|97|90|66|70|55|25|25|50|30
4|98|93|68|72|60|27|27|55|39
3|99|96|75|74|65|50|32|60|50
2|99|99|80|76|70|50|45|65|55
1|99|99|83|80|75|50|50|70|60

This table makes sense, it's what the client displays, and some values even *kinda* match what the Wiki said. The only thing that's a little weird to me is that the "starting points" of Antidote and Poison are different than on the Wiki. They're saying C and B, when in reality both don't seem to start until 9. But I'll add it like this for now regardless. Who knows where they got their information from.

**Comment by Pegwald** [comment]
Yep, this looks way more accurate than what I've been used to in NA ^^. GJ
