### ISSUE TITLE
Missing Portals

### ISSUE THREAD

**Issue by Xcelled** [aura-project/aura#95]
I know none of these are G1, but it makes for a very disrupting experience to try to walk around the world and have to look up every other region id.

Regions I've identified that have portals that don't work:

* Cuilin
* Abb
* Cobh
* Sen Mag
* Taill
* Corrib
* Tara
* Blago

Surprisingly, this comprises most of Uladh. I have not checked into Iria or Belvast recently, but those most likely have issues as well.

**Comment by exectails** [comment]
"Issue"? "Bug"? We don't need those regions in G1, so I didn't add them yet o,o Feel free to do so^^

![](http://puu.sh/ejQET/f4e2b1d4a2.png)
