### ISSUE TITLE
Sheep are in a hurry

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#96]
compared to the official mabi, these sheep don't stand around for too long before they run off. You are supposed to be able to get at least 2 wool before it moves, but here I am only able to get 1. 

https://www.youtube.com/watch?v=pIgCIr3A678

**Comment by Sairii** [comment]
i dont think we have the official sheep ai yet

**Comment by exectails** [comment]
We are using a kind of dummy AI atm, but I will classify this as a bug, as it makes gathering wool rather challenging.

**Comment by Sairii** [comment]
*cough*
https://github.com/Sairii/aura-AI/blob/master/scripts/ai/sheep.cs

*hides*

**Comment by QewQew** [comment]
You're always welcome to make a pull request.
