### ISSUE TITLE
Sheep don't have a max shearing limit

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#97]
When I am able to actually keep up with 1 sheep, it looks like it can offer me quite an amount of wool. Not just 5, but I was able to gather 30 wool before I felt bad for it and switched sheep. In official mabi the limit is 5 before the sheep has to "regenerate" its wool.

**Comment by Pegwald** [comment]
Yay, nerfed sheep :D
I am not able to get the 5 wool without failing at the last one - "there's just no wool left", but once I try once more, I get the last piece. I believe this is because the sheep is missing 1 mana. Not a big deal, really. It's just 1 mana.

**Comment by Pegwald** [comment]
-Scratch that. I can't re-create this scenario. Looks like this was a one-time issue once after the change/server beboot :l

**Comment by QewQew** [comment]
I'm not sure what game you were playing, but sheeps hold ***way*** more than just ***5*** Wool (in official).

I'm shearing sheep right now and I've gotten a ton more than 5 successes (I wasn't keeping exact count, but 30 is about right). [Even the wiki states 30.](http://wiki.mabinogiworld.com/view/Sheep_Shearing)

**Comment by exectails** [comment]
Thanks, @QewQew , I wasn't sure, and when I tested in on NA, I definitely didn't get >10, so I thought he's probably right. I guess the sheep I tested was just empty =|
