### ISSUE TITLE
Picking up Item Pouches

### ISSUE THREAD

**Issue by Pikachews** [aura-project/aura#97]
Picking up an empty item pouch (e.g. Cobweb Pouch) will remove the item completely.
The [Pickup()](https://github.com/aura-project/aura/blob/master/src/ChannelServer/World/Inventory/CreatureInventory.cs#L491) method does not handle item pouches uniquely, and if it is empty, it will fall straight through the method and result in a successful pickup, although nothing was added to the inventory.

**Comment by exectails** [comment]
Huh. Same probably happens with gold pouches?

**Comment by Pikachews** [comment]
Yep.

**Comment by haywoodspartan** [comment]
Guys it is too late Someone got the jump on the JP server files and is now
running a legit private server.

http://mabire.net

On Fri, Jan 16, 2015 at 7:02 PM, Pikachews <notifications@github.com> wrote:

> Picking up an empty item pouch (e.g. Cobweb Pouch) will remove the item
> completely.
> The Pickup()
> <https://github.com/aura-project/aura/blob/master/src/ChannelServer/World/Inventory/CreatureInventory.cs#L491>
> method does not handle item pouches uniquely, and if it is empty, it will
> fall straight through the method and result in a successful pickup,
> although nothing was added to the inventory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aura-project/aura/issues/97>.
>



-- 
Christopher Spivey
(Database Administrator)

**Comment by exectails** [comment]
Thanks for the notification, @haywoodspartan, but that doesn't really matter to us. It's not our goal to set up a simple private server.

**Comment by haywoodspartan** [comment]
True just a heads up since Nexon does not take this very lightly since we
are messing around with there stuff.

On Mon, Jan 19, 2015 at 2:08 PM, exec <notifications@github.com> wrote:

> Thanks for the notification, @haywoodspartan
> <https://github.com/haywoodspartan>, but that doesn't really matter to
> us. It's not our goal to set up a simple private server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aura-project/aura/issues/97#issuecomment-70544455>.
>



-- 
Christopher Spivey
(Database Administrator)

**Comment by haywoodspartan** [comment]
And did you guys fix the movement control in this latest update


On Mon, Jan 19, 2015 at 2:09 PM, Christopher Spivey <cjspivey96@gmail.com>
wrote:

> True just a heads up since Nexon does not take this very lightly since we
> are messing around with there stuff.
>
> On Mon, Jan 19, 2015 at 2:08 PM, exec <notifications@github.com> wrote:
>
>> Thanks for the notification, @haywoodspartan
>> <https://github.com/haywoodspartan>, but that doesn't really matter to
>> us. It's not our goal to set up a simple private server.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/aura-project/aura/issues/97#issuecomment-70544455>.
>>
>
>
>
> --
> Christopher Spivey
> (Database Administrator)
>



-- 
Christopher Spivey
(Database Administrator)

**Comment by exectails** [comment]
Not sure what you mean, Aura is perfectly legal and has nothing to do with MabiRe, and I don't know what bug you're referring to, you aren't able to move?

Please stop by our chat at https://gitter.im/aura-project/aura or on our forum, this conversation doesn't belong in the comments of a closed issue.

**Comment by haywoodspartan** [comment]
Yeah logging in to soultream and actually talking to npc.nao it won't even
let me WASD around and won't let me mouse click all i get are some
unimplemented errors


On Mon, Jan 19, 2015 at 2:13 PM, exec <notifications@github.com> wrote:

> Not sure what you mean, Aura is perfectly legal and has nothing to do with
> MabiRe, and I don't know what bug you're referring to, you aren't able to
> move?
>
> Please stop by our chat at https://gitter.im/aura-project/aura or on our
> forum, this conversation doesn't belong in the comments of a closed issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aura-project/aura/issues/97#issuecomment-70545042>.
>



-- 
Christopher Spivey
(Database Administrator)

**Comment by exectails** [comment]
Please use the chat or the forum, I'm gonna stop replying here after this message.

Aura is only compatible to the latest version of NA, please make sure Aura *and* your NA client are up-to-date. If it still doesn't work please open a new issue on GitHub or a thread on the Forum in "Bugs".

There has been some change to the Soul Stream in the last update, though I don't think that would affect anything. I'm still gonna check it out.
