### ISSUE TITLE
Wrong production output/skill training in weaving

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#98]
I used the weaving skill to craft some fabric and silk to check if things were alright there, but it seems that output and skill training are not quite synchronized together. I made 2 fine fabrics and got skill training for making cheap fabric, made 1 fine and 2 common silks and got skill training for making cheap silk. I'm not sure which is wrong, but I am making a guess and believe it would be the skill training. 
![weaving](https://cloud.githubusercontent.com/assets/13089450/11204042/c5b15a60-8cfa-11e5-9056-dd852af7ae5f.PNG)

**Comment by exectails** [comment]
We have to adjust to what the client displays, it is the skill training that's wrong. We don't have control over the training methods. The problem was that the code didn't factor in the random element in weaving, where you can get different results from the same materials.
