### ISSUE TITLE
Missing party rules

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#99]
There's no implemented finishing rules and such in parties. I just wanted to mention it since I made a mistake earlier by overlooking the case of a missing "/whisper" function in the chat system :>

**Comment by exectails** [comment]
I don't quite understand this issue, what is the problem? Party finishes should be working, and what's "/whisper"?

**Comment by Pegwald** [comment]
Sorry, I meant the feature "whisper", you know the one where you type "/" command in chat to whisper to a specified character ^^ ''
I tried to use a finish rule (anyone in the party), but it will only be ignored whenever someone kills a mob. It is supposed to work like when somebody in a party kills a mob, it will semi-die and lie on the ground until someone "executes" it.

**Comment by Pegwald** [comment]
oh, I'm a retard. It's not "/", it's "@" xD
So sorry

**Comment by DeleteIT** [comment]
>Party finishes should be working

https://github.com/aura-project/aura/blob/master/src/ChannelServer/World/Entities/Creature.cs#L1566
Is the only reference to SetFinisher, which I would assume is the flashing "Finish!" packet broadcaster.

I never got around to working with any rules other than Exp, so unless you implemented party finishes, they're not in.
Or party quests, for that matter.

**Comment by exectails** [comment]
Oh, that's what you mean. You're right, that's not in yet, totally forgot about it. I think I don't even have proper logs of that yet =<

**Comment by YaibaToKen** [comment]
How would one log those things? How would I log anything at all actually xD I stumbled upon the project just yesterday, seeing as I play often, might as well try and help.

**Comment by Sairii** [comment]
>How would I log anything at all actually xD

You would need morrighan and mabipale for that.
Both can be found in the forums

**Comment by exectails** [comment]
>Both can be found in the forums

http://aura-project.org/forum/forum/42-tools/

I actually got the necessary packets for this particular issue by now though, forgot to mention it^^

**Comment by exectails** [comment]
I need someone to test this branch: https://github.com/aura-project/aura/tree/fix-99-finisher

It's supposed to fix this, but I don't want to merge this into master until it was properly tested by a second party, potentially breaking combat, skill training, etc. Ideally, of course, it should be tested with multiple party members.

It needs to be tested under various circumstances, finishing with different skills, by different party members, with different rules, etc. the sooner it's tested, the sooner it can be merged.

**Comment by exectails** [comment]
So... nobody tested this yet, right? I guess I'll just merge it and let the master branch users do it =<

**Comment by killer000** [comment]
Well you might as well do that hopefully none thing major goes wrong 🎱

**Comment by Sairii** [comment]
I cant test this alone ;<

**Comment by xCryptic** [comment]
Someone *cough* @Cosrnos should setup a test server like that person did for fishing :>
